### DISCUSSION TITLE
{"level":"ERROR","msg":"unable to fetch index \"falcosecurity\" with URL \"\": unable to fetch index: cannot fetch index: Get \"\": unsupported protocol scheme \"\"","timestamp":"2025-06-12 08:03:21"}

### DISCUSSION THREAD

**Discussion by 13567436138** [falcosecurity/falco#3612] [Q&A]
{"level":"ERROR","msg":"unable to fetch index \"falcosecurity\" with URL \"\": unable to fetch index: cannot fetch index: Get \"\": unsupported protocol scheme \"\"","timestamp":"2025-06-12 08:03:21"}

with helm values
```
image:
  registry: harbor.mark.demo
  repository: falco/falco
  tag: "0.40.0"
scc:
  # -- Create OpenShift's Security Context Constraint.
  create: false
resources:
  requests:
    cpu: 30m
    memory: 212Mi
driver:
  loader:
    enabled: true
    initContainer:
      image:
        registry: harbor.mark.demo
        repository: falco/falco-driver-loader
        tag: "0.40.0"
falcosidekick:
  enabled: true
  image:
    registry: harbor.mark.demo
    repository: falco/falcosidekick
    tag: 2.31.1
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: falcosidekick.mark.demo
        paths:
        - path: /
          pathType: Prefix
  webui:
    enabled: true
    image:
      registry: harbor.mark.demo
      repository: falco/falcosidekick-ui
      tag: "2.2.0"
    initContainer:
      image:
        registry: harbor.mark.demo
        repository: falco/redis-stack
        tag: "7.2.0-v11"
    redis:
      enabled: true
      storageClass: ceph-rbd
      image:
        registry: harbor.mark.demo
        repository: falco/redis-stack
        tag: "7.2.0-v11"
falcotalon:
  enabled: true
falco-talon:
  image:
    registry: harbor.mark.demo
    repository: falco/falco-talon
    tag: "0.2.1"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: falco-talon.mark.demo
      paths:
        - path: /
          pathType: Prefix  
k8s-metacollector:
  image:
    registry: harbor.mark.demo
    repository: falco/k8s-metacollector
    tag: "0.1.1"
collectors:
  kubernetes:
    enabled: true
falcoctl:
  image:
    registry: harbor.mark.demo
    repository: falco/falcoctl
    tag: "0.11.0"
  artifact:
    install:
      enabled: true
#      mounts:
#        volumeMounts: 
#        - mountPath: ~/.config/falcoctl/indexes.yaml
#          name: index-config-volume
    follow:
      enabled: false
  config:
    indexes:
      - name: falcosecurity
        file: "file:///etc/falcoctl/index.yaml"
    artifact:
      install:
        refs: 
        - "harbor.mark.demo/falco/rules/falco-rules:latest"
        - "harbor.mark.demo/falco/plugins/plugin/k8smeta:latest"    
      follow:
        refs: 
        - "harbor.mark.demo/falco/rules/falco-rules:latest"
        - "harbor.mark.demo/falco/plugins/plugin/k8smeta:latest" 
mounts:
  volumes: 
  - name: index-config-volume
    configMap:
      name: index-config
      items:
      - key: index.yaml
        path: index.yaml
  volumeMounts: 
    - name: index-config-volume
      mountPath: /etc/falcoctl
      readOnly: true
  
falco:   
  rules_file:   
  - /etc/falco/k8s_audit_rules.yaml
  - /etc/falco/rules.d
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco-incubating_rules.yaml
  - /etc/falco/falco-sandbox_rules.yaml

  plugins:
    - name: k8saudit
      library_path: /usr/share/falco/plugins/libk8saudit.so
      init_config:
      #   maxEventSize: 262144
      #   webhookMaxBatchSize: 12582912
      #   sslCertificate: /etc/falco/falco.pem
      open_params: "http://:9765/k8s-audit"
    - name: cloudtrail
      library_path: /usr/share/falco/plugins/libcloudtrail.so
      # see docs for init_config and open_params:
      # https://github.com/falcosecurity/plugins/blob/master/plugins/cloudtrail/README.md
    - name: json
      library_path: /usr/share/falco/plugins/libjson.so
      init_config: ""
      
  container_engines:
    cri:
      enabled: true
      sockets: ["/run/containerd/containerd.sock"]
```
