### ISSUE TITLE
Empty values (<NA>) in JSON output fields

### ISSUE THREAD

**Issue by bzurkowski** [falcosecurity/falco#1029]
**Describe the bug**

When using Falco with dynamic K8S auditing enabled, JSON output in Falco alerts has missing values for some attributes, mainly `pod` attribute. These values are marked as `<NA>`.

For example, given the default auditing rule:

```yaml
- rule: Create HostNetwork Pod
  desc: Detect an attempt to start a pod using the host network.
  condition: kevt and pod and kcreate and ka.req.pod.host_network intersects (true) and not ka.req.pod.containers.image.repository in (falco_hostnetwork_images)
  output: Pod started using host network (user=%ka.user.name pod=%ka.resp.name ns=%ka.target.namespace images=%ka.req.pod.containers.image)
  priority: WARNING
  source: k8s_audit
  tags: [k8s]
```

My backend receives an alert with the following content:

```json
{
   "output":"16:00:07.403497984: Warning Pod started using host network (user=system:serviceaccount:kube-system:replicaset-controller pod=<NA> ns=falco-event-generator images=busybox)",
   "priority":"Warning",
   "rule":"Create HostNetwork Pod",
   "time":"2020-01-24T16:00:07.403497984Z",
   "output_fields":{
      "jevt.time":"16:00:07.403497984",
      "ka.req.pod.containers.image":"busybox",
      "ka.resp.name":"<NA>",
      "ka.target.namespace":"falco-event-generator",
      "ka.user.name":"system:serviceaccount:kube-system:replicaset-controller"
   }
}
```

Note `"ka.resp.name":"<NA>"` should contain pod name.

**How to reproduce it**

1. Enable dynamic auditing in API Server.
2. Deploy Falco using Helm chart with dynamic K8S auditing enables:
3. Run K8S [events generator](https://falco.org/docs/event-sources/sample-events/).
4. Observe the payloads of generated alerts.

**Expected behavior**

All attributes of K8S objects used in rule expressions should be provided into the `output_fields` attribute of alert payload with correct values.

**Environment**

- Falco version:
```
Falco version: 0.18.0
```
- System info:
```json
{
  "machine": "x86_64",
  "nodename": "falco-5gqdj",
  "release": "3.10.0-693.el7.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Tue Aug 22 21:09:27 UTC 2017"
}
```
- Cloud provider or hardware configuration: Kubernetes 1.15
- OS:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
- Kernel:
```
Linux node1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method: Helm chart
