### ISSUE TITLE
Not able enable k8s audit logs with falco ,k8s version 1.16 and falco as daemon-set 

### ISSUE THREAD

**Issue by psingh-xav** [falcosecurity/falco#1052]
**enable k8s audit logs**

i m facing this when add audit-policy.yaml in kube-apiserver.yaml ,  kubectl get pod , command not working getting error 

The connection to the server 10.x.x.x:6443 was refused - did you specify the right host or port?

**docker logs kube-api** 

root@ip-10-x-x-x:/home/ubuntu# docker ps |grep api
6edb43503842        k8s.gcr.io/pause:3.1                                                    "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD_kube-apiserver-ip-10-x-x-x.ca-central-1.compute.internal_kube-system_4fa29a1ab60d1420cb8238bc864f009c_0
roo
**kubelet  service status**

root@ip-10-x-x-x:/home/ubuntu# systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; masked; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 20-etcd-service-manager.conf
   Active: active (running) since Tue 2020-02-18 13:55:39 UTC; 5h 32min ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 7200 (kubelet)
    Tasks: 44 (limit: 4915)
   CGroup: /system.slice/kubelet.service
           └─7200 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/con

Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:49.707158    7200 kubelet_node_status.go:388] Error updating node status, will re
Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:49.707177    7200 kubelet_node_status.go:375] Unable to update node status: updat
Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:49.839549    7200 reflector.go:123] object-"default"/"falco": Failed to list *v1.
Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:27:49.910727    7200 kubelet_pods.go:849] Unable to retrieve pull secret default/reg
Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:27:49.911407    7200 kubelet_pods.go:849] Unable to retrieve pull secret default/reg
Feb 18 19:27:49 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:49.911762    7200 pod_workers.go:191] Error syncing pod c03d13b5-6d55-4c40-9215-7
Feb 18 19:27:50 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:50.039627    7200 reflector.go:123] object-"kube-system"/"coredns-token-sszt9": F
Feb 18 19:27:50 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:50.239491    7200 reflector.go:123] object-"default"/"regcred": Failed to list *v
Feb 18 19:27:50 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:50.439438    7200 reflector.go:123] object-"kube-system"/"kube-proxy": Failed to
Feb 18 19:27:50 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:27:50.443645    7200 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Fa
lines 1-21/2

getting error  " E0218 12:15:41.474972   14530 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.RuntimeClass: Get https://10.x.x.x:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.x.x.x:6443: connect: connection refused 

root@ip-10-x-x-x:/home/ubuntu# journalctl -xeu kubelet
Feb 18 19:31:30 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:30.639665    7200 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Fa
Feb 18 19:31:30 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:30.839611    7200 reflector.go:123] object-"kube-system"/"tiller-token-ckw54": Fa
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:31.039693    7200 reflector.go:123] object-"kube-system"/"calico-node-token-lzvqf
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:31.239502    7200 reflector.go:123] object-"kube-system"/"calico-kube-controllers
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:31.263090    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/bl
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:31.263134    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/me
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:31.263153    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/de
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:31.263190    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/pi
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:31.439817    7200 reflector.go:123] object-"default"/"falco-token-bg45c": Failed
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:31.639511    7200 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/config/apiserve
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:31.839465    7200 reflector.go:123] object-"kube-system"/"coredns": Failed to lis
Feb 18 19:31:31 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:31.913451    7200 kubelet_pods.go:849] Unable to retrieve pull secret default/reg
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:32.039506    7200 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:459:
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:32.054144    7200 controller.go:135] failed to ensure node lease exists, will ret
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:32.239493    7200 reflector.go:123] object-"default"/"idp-credentials": Failed to
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:32.439589    7200 reflector.go:123] object-"kube-system"/"calico-config": Failed
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:32.639674    7200 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:450:
Feb 18 19:31:32 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:32.839533    7200 status_manager.go:529] Failed to get status for pod "calico-nod
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.039568    7200 reflector.go:123] object-"default"/"idp-client-secret": Failed
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.239490    7200 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Fa
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.439365    7200 reflector.go:123] object-"kube-system"/"kube-proxy-token-hg9h4"
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.639493    7200 reflector.go:123] object-"default"/"falco": Failed to list *v1.
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.723908    7200 event.go:246] Unable to write event: 'Patch https://10.2.3.222:
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.724523    7200 event.go:191] Unable to write event '&v1.Event{TypeMeta:v1.Type
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.725304    7200 event.go:246] Unable to write event: 'Post https://10.2.3.222:6
Feb 18 19:31:33 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:33.839505    7200 reflector.go:123] object-"kube-system"/"coredns-token-sszt9": F
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:34.039476    7200 reflector.go:123] object-"default"/"regcred": Failed to list *v
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:34.239602    7200 reflector.go:123] object-"kube-system"/"kube-proxy": Failed to
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.325824    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/bl
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.325932    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/me
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.325956    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/de
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.325979    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/pi
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.400163    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/bl
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.400577    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/me
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.400610    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/de
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.400630    7200 watcher.go:87] Error while processing event ("/sys/fs/cgroup/pi
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:34.439868    7200 reflector.go:123] object-"default"/"default-token-vldmp": Faile
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:34.639417    7200 reflector.go:123] object-"default"/"idp-realms-users": Failed t
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:34.839967    7200 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Fa
Feb 18 19:31:34 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: W0218 19:31:34.910854    7200 kubelet_pods.go:849] Unable to retrieve pull secret default/reg
Feb 18 19:31:35 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:35.039721    7200 reflector.go:123] object-"kube-system"/"tiller-token-ckw54": Fa
Feb 18 19:31:35 ip-10-x-x-x.ca-central-1.compute.internal kubelet[7200]: E0218 19:31:35.239579    7200 reflector.go:123] object-"kube-system"/"calico-node-token-lzvqf

**cat audit-policy.yaml** 
ubuntu@ip-10-x-x-x:/etc/kubernetes/pki$ cat audit-policy.yaml
```
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      # Resource "pods" doesn't match requests to any subresource of pods,
      # which is consistent with the RBAC policy.
      resources: ["pods"]
  # Log "pods/log", "pods/status" at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]

  # Don't log requests to a configmap called "controller-leader"
  - level: None
    resources:
    - group: ""
      resources: ["configmaps"]
      resourceNames: ["controller-leader"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or services
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
    - group: "" # core API group
      resources: ["endpoints", "services"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  # Log the request body of configmap changes in kube-system.
  - level: Request
    resources:
    - group: "" # core API group
      resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log configmap and secret changes in all other namespaces at the Metadata level.
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets", "configmaps"]

 ### # Log all other resources in core and extensions at the Request level.
  - level: Request
    resources:
    - group: "" # core API group
    - group: "extensions" # Version of group should NOT be included.

  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"

```
cat kube-apiserver.yaml 

```
root@ip-10-x-x-x:/etc/kubernetes/manifests# cat kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.x.x.x
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --audit-log-format=json
    - --audit-log-maxage=90
    - --audit-log-maxbackup=30
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kubernetes/audit.log
    - --audit-policy-file=/etc/kubernetes/pki/audit-policy.yaml
    - --audit-webhook-config-file=/etc/kubernetes/audit-webhook-kubeconfig
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cloud-provider=aws
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: k8s.gcr.io/kube-apiserver:v1.16.7
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 10.2.x.x
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```

but when comment   "     - --audit-policy-file=/etc/kubernetes/pki/audit-policy.yaml
 " kubectl get pod working 
please help m i missing or wrong configuration
 
**i have install falco as daemonset on kubeadm cluster (k8s 1.16) , if i check my falco pod logs i get only falco pod logs or** 
 this only falco logs , i am not able to track   other activity on kubernetes (like create pod , delete namespace , create configmap with credential etc ) which rule mention in k8s_audit_rule.yaml

**am i missing any configuration?** 
 
19:19:15.962126813: Error File below /etc opened for writing (user=root command=vi kube-apiserver.yaml parent=bash pcmdline=bash file=/etc/kubernetes/manifests/4913 program=vi gparent=su ggparent=sudo gggparent=bash container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
12:49
19:19:15.962194822: Error File below /etc opened for writing (user=root command=vi kube-apiserver.yaml parent=bash pcmdline=bash file=/etc/kubernetes/manifests/kube-apiserver.yaml program=vi gparent=su ggparent=sudo gggparent=bash container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
