### ISSUE TITLE
falco-0.23.0 gets SIGINT after running for a minute on 4.14.171-136.231.amzn2.x86_64

### ISSUE THREAD

**Issue by farshad-hobsons** [falcosecurity/falco#1229]
**Describe the bug**

The image `falcosecurity/falco:0.23.0` when run with the following white-lists.yaml rules returns SIGINT:
Error log:
```
Wed May 20 14:19:57 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed May 20 14:19:57 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed May 20 14:20:04 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed May 20 14:20:09 2020: Loading rules from file /etc/falco/rules.d/white-lists.yaml:
Wed May 20 14:20:14 2020: Starting internal webserver, listening on port 8765
14:20:12.893767000: Notice Privileged container started (user=<NA> command=container:9123ad30f0ea k8s.ns=ops k8s.pod=weave-scope-agent-2km5f container=9123ad30f0ea image=weaveworks/scope:1.13.1) k8s.ns=ops k8s.pod=weave-scope-agent-2km5
f container=9123ad30f0ea k8s.ns=ops k8s.pod=weave-scope-agent-2km5f container=9123ad30f0ea
...
Wed May 20 14:20:19 2020: Falco internal: syscall event drop. 5947 system calls dropped in last second.Wed May 20 14:20:20 2020: Falco internal: syscall event drop. 19374 system calls dropped in last second.Wed May 20 14:20:20 2020: Fal
co internal: syscall event drop. 29480 system calls dropped in last second.Wed May 20 14:20:20 2020: Falco internal: syscall event drop. 14984 system calls dropped in last second.Wed May 20 14:20:21 2020: Falco internal: syscall event d
rop. 7368 system calls dropped in last second.Wed May 20 14:20:21 2020: Falco internal: syscall event drop. 31686 system calls dropped in last second.Wed May 20 14:21:01 2020: SIGINT received, exiting...
Syscall event drop monitoring:
   - event drop detected: 6 occurrences
   - num times actions taken: 6
Events detected: 21
Rule counts by severity:
   ERROR: 8
   INFO: 6
   WARNING: 4
   NOTICE: 3
Triggered rules by rule name:
   Launch Sensitive Mount Container: 2
   Contact K8S API Server From Container: 3
   Launch Privileged Container: 4
   The docker client is executed in a container: 4
   Write below root: 8
rpc error: code = Unknown desc = Error: No such container: af9e3ddfd6e8f78390
```
white-lists.yaml (this rule files runs fine with `falco:0.22.1`
```
        # white list flux doing kubectl apply against api-server
        - macro: k8s_containers
          append: true
          condition: or (container.image.repository contains fluxcd/flux)
        # white list k8s client tool executed inside fluxcd container
        - macro: user_known_k8s_client_container
          append: true
          condition: or (container.image.repository contains fluxcd/flux)
```

**How to reproduce it**

1. On amazon EKS VM( amazon-eks-node-1.15-v20200312 (ami-0dc7713312a7ec987)) load falco-kernel module https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/:falco_amazonlinux2_4.14.171-136.231.amzn2.x86_64_1.ko
2. Deploy falco using helm chart with `SKIP_DRIVER_LOADER=true` & `SKIP_MODULE_LOAD=true` with white-lists.yaml from above.

**Expected behaviour**

The falco pod should continue to run without getting a SIGINT.

**Screenshots**

**Environment**

- Falco version: `falcosecurity/falco:0.23.0`

- System info: 4.14.171-136.231.amzn2.x86_64

- Cloud provider or hardware configuration:
- OS:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

- Kernel:
Linux ip-10-125-71-201.ec2.internal 4.14.171-136.231.amzn2.x86_64 #1 SMP Thu Feb 27 20:22:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
Kubernetes

**Additional context**

**Comment by leogr** [comment]
Hi @farshad-hobsons 

Thanks for reporting this.

Just two question to help me understand better:
- Does the problem occur without `white-lists.yaml` ?
- Could you share with us the exact helm installation command you used? 
   I guess it should be something like `helm install falco --set image.tag=0.23.0,daemonset.env.SKIP_DRIVER_LOADER=true,daemonset.env.SKIP_MODULE_LOAD=true ...`, but having the exact command will help in reproducing the issue.

Thanks in advance.

**Comment by farshad-hobsons** [comment]
Hi @leogr , thanks for a quick response. Below are the answers to your questions.

> * Does the problem occur without `white-lists.yaml` ?

The problem does not occur without the `white-lists.yaml` in `falco:0.23.0`. Also  on `falco:0.22.1`, the `white-lists.yaml` worked fine and I did not encounter the SIGINT

> * Could you share with us the exact helm installation command you used?
>   I guess it should be something like `helm install falco --set image.tag=0.23.0,daemonset.env.SKIP_DRIVER_LOADER=true,daemonset.env.SKIP_MODULE_LOAD=true ...`, but having the exact command will help us in reproducing the issue.

I am using the helmoperator which uses the helmRelease custom resource to deploy the helm chart. Not sure how much it helps but the `helmRelease.yaml` is below:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: falco
  namespace: ops
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: falco
    version: 1.1.7
  values:
    image:
      registry: docker.io
      repository: falcosecurity/falco
      tag: 0.23.0
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 32Mi
    tolerations:
    - operator: "Exists"
    daemonset:
      env:
        SKIP_MODULE_LOAD: true
        SKIP_DRIVER_LOADER: true
    customRules:
      white-lists.yaml: |-
        # white list flux doing kubectl apply against api-server
        - macro: k8s_containers
          append: true
          condition: or (container.image.repository contains fluxcd/flux)

        # white list k8s client tool executed inside fluxcd container
        - macro: user_known_k8s_client_container
          append: true
          condition: or (container.image.repository contains fluxcd/flux)
```
 Not completely sure how ^^ translates to helm command which includes the `white-lists.yaml`. Without `white-lists.yaml`, I was able to test with the following helm command.
```bash
helm --tiller-namespace ops --namespace ops upgrade --set resources.limits.memory=512Mi --set tolerations[0].operator=Exists --set image.tag=0.23.0 um-falco stable/falco -i --version 1.1.7 --set daemonset.env.SKIP_
MODULE_LOAD="true" --set daemonset.env.SKIP_DRIVER_LOADER="true"
```

Side note: The whole point of introducing the custom `white-lists.yaml` in my case was because the service-account tokens were being logged by falco whenever fluxcd talked to the api-server which I think is not a _good security practice_. Below are a few redacted(used X for actual values) falco logs showing the sa-token leak:
```
13:25:32.819368793: Warning Docker or kubernetes client executed in container (user=root k8s.ns=ops k8s.pod=X container=1c89f75f8428 parent=fluxd cmdline=kubectl --server=https://X.X.X.X --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --token=eyJhXXXXXX apply -f - image=fluxcd/flux:1.19.0) k8s.ns=ops k8s.pod=X container=1c89f75f8428

13:25:34.488398244: Notice Unexpected connection to K8s API Server from container (command=kubectl --server=https://X.X.X.X:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --token=eyXXXXXX apply -f - k8s.ns=ops k8s.pod=XXX container=1c89f75f8428 image=fluxcd/flux:1.19.0 connection=X.X.X.X:51328->X.X.X.X:443) k8s.ns=ops k8s.pod=XXX
```

**Comment by farshad-hobsons** [comment]
@leogr , thanks for providing feedback on how to debug this issue. Appreciate it!

I was able to use the following helm cli command to deploy falco with `white-lists.yaml`
```bash
helm --tiller-namespace ops --namespace ops upgrade --set resources.limits.memory=512Mi --set tolerations[0].operator=Exists --set image.tag=0.23.0 um-whitelists-falco stable/falco -i --version 1.1.7 --set daemonset.env.SKIP_MODULE_LOAD="true" --set daemonset.env.SKIP_DRIVER_LOADER="true" -f /tmp/falco-values.yaml 
```
/tmp/falco-values.yaml 
```yaml
customRules:
  white-lists.yaml: |-
    # white list flux doing kubectl apply against api-server
    - macro: k8s_containers
      append: true
      condition: or (container.image.repository contains fluxcd/flux)

    # white list k8s client tool executed inside fluxcd container
    - macro: user_known_k8s_client_container
      append: true
      condition: or (container.image.repository contains fluxcd/flux)
```

It is almost certain that this is not an issue with falco:0.23.0 and rather some issue with helm-operator since I am only able to reproduce it via HelmRelease custom resource.
