### ISSUE TITLE
GKE - Falco Logs not appearing for up to 10 minutes

### ISSUE THREAD

**Issue by danpopSD** [falcosecurity/falco#1291]
**Describe the bug**

GKE - Falco Logs not appearing for up to 10 minutes

**How to reproduce it**

1) deploy a gke cluster
2) use the helm chart to install falco. (helm install falco --set ebpf.enabled=true falcosecurity/falco)
3) tail one of the falco logs (kubectl logs -f *falco-podname*
3) in another terminal try to exec into the pod. or do another falco rule violation.
4) await logs to show up.  (up to 10 minutes)
**Expected behaviour**

logs/falco event notifications to be immediate or close to it vs 9-10 minutes..

**Screenshots**

![image](https://user-images.githubusercontent.com/22457772/86072899-b2e93780-ba50-11ea-89a3-f162082c34a8.png)

**Environment**

- Falco version:
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
- System info:

{
  "machine": "x86_64",
  "nodename": "gke-popfalco1-default-pool-880376cf-qj8n",
  "release": "4.19.109+",
  "sysname": "Linux",
  "version": "#1 SMP Mon Mar 16 06:27:01 PDT 2020"
}
- Cloud provider or hardware configuration:
GKE... Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15". (3 nodes)

**Additional context**

none

**Comment by kris-nova** [comment]
Thanks for the report

Can you share the following 

### The exact helm chart and associated commands

Recently the community ported to this resource https://github.com/falcosecurity/charts/tree/master/falco#installing-the-chart

Can you confirm you are using the must recent version here?

### How are you viewing the logs?

Are you viewing the logs on all nodes in the cluster? Something like

```bash
kubectl logs -l app=falco -f
``` 

### What is your burst set to?

If you look [here](https://github.com/falcosecurity/falco/blob/master/falco.yaml#L90-L104) you can see the following:

Note that 1000 seconds is between 16 and 17 minutes.

```
# A throttling mechanism implemented as a token bucket limits the
# rate of falco notifications. This throttling is controlled by the following configuration
# options:
#  - rate: the number of tokens (i.e. right to send a notification)
#    gained per second. Defaults to 1.
#  - max_burst: the maximum number of tokens outstanding. Defaults to 1000.
#
# With these defaults, falco could send up to 1000 notifications after
# an initial quiet period, and then up to 1 notification per second
# afterward. It would gain the full burst back after 1000 seconds of
# no activity.

outputs:
  rate: 1
  max_burst: 1000
```

Probably the quickest way to debug this is to do send a quick batch of alerts consecutively and see if you start getting real-time alerts. 

When I demo I usually like to violate 10+ rules as quickly as possible. Usually, I do something like this:

```bash
touch /usr/bin/1
touch /usr/bin/2
touch /usr/bin/3
cat /etc/shadow
touch /etc/1
touch /proc/1
cat ~/.bashrc
touch /root/1
touch /root/2
touch /root/3
```

---

Let me know of any of that doesn't help you out and I can spin up a GKE cluster tomorrow and tell you exactly what is going on.
