### ISSUE TITLE
Consice pod security policy template

### ISSUE THREAD

**Issue by Champ-Goblem** [falcosecurity/falco#1304]
I am deploying falco on a set of clusters that all have PSPs enabled, we use a default fairly restrictive PSP across the whole cluster which causes this deployment to fail. For the time being I have created an exclusive pod security policy for the falco components to use which allows me to install them without the deployments being invalidated. What I would prefer is a tailored PSP that only allows the features that falco needs and disables the others for security purposes.

I am not sure if this should be a documentation request or a feature request as we could include this in either the helm chart as a true/false value that automatically applies the policy to the target namespace or as an entry in the documentation that lists the required permissions for falco so that users can create the policy themselves.

**Comment by leodido** [comment]
Hello @Champ-Goblem, I really like this idea and I'd love you to contribute this to our community! 

I think the correct place to provide PSP for Falco and Falco components would be the helm chart (https://github.com/falcosecurity/charts), as a starting point.

Then, since not everyone uses Helm to install Falco, I think that a documentation section on the website (https://github.com/falcosecurity/falco-website) will be needed too.

Strong +1 from me and thanks for proposing it! :)

**Comment by Champ-Goblem** [comment]
@leodido here is the PSP that I found that works with falco, is there anything you think I may be missing?
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.falco
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "docker/default,runtime/default"
    apparmor.security.beta.kubernetes.io/allowedProfileNames: "runtime/default"
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  "runtime/default"
    apparmor.security.beta.kubernetes.io/defaultProfileName:  "runtime/default"
spec:
  privileged: true
  hostNetwork: true
  hostPID: false
  hostIPC: false
  allowPrivilegeEscalation: true
  requiredDropCapabilities:
  - "*"
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  volumes:
  - hostPath
  - emptyDir
  - configMap
  - secret
```

What do you think would be the best to apply this via the helm chart, I think we should create a new role and role binding that binds the PSP to the falco service account? Something like:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role       
metadata: 
  name: psp.falco
rules:
- apiGroups:
  - policy  
  resources:
  - podsecuritypolicies
  resourceNames: 
  - psp.falco   
  verbs:
  - use 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp.falco
roleRef:
  kind: Role       
  name: psp.falco
  apiGroup: rbac.authorization.k8s.io
subjects:    
- kind: ServiceAccount
  name: falco
```
