### ISSUE TITLE
Configurable Authorization HTTP Header for HTTP outputs

### ISSUE THREAD

**Issue by danmx** [falcosecurity/falco#1322]
**Motivation**

Current HTTP Output doesn't allow almost any [customization](https://falco.org/docs/configuration/) apart from enabling it and configuring the destination url. Some log aggregators' HTTP endpoints, e.g. [Splunk's HEC](https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/HECExamples), require `Authorization` HTTP header which currently can't be added. It could be useful for gRPC output too.

**Feature**

Allowing users to configure `Authorization` HTTP header to authenticate to the http output endpoint.

**Alternatives**

An alternative could be adding a HTTP proxy (`nginx`, `envoy`, etc.) in the middle which would inject the header or use the program output with `curl`.

**Additional context**

**Comment by Issif** [comment]
BTW I can definitively add this in `falcosidekick` webhook output (a direct output for Splunk could be great too).

**Comment by Issif** [comment]
@danmx the feature is now available in available in `falcosidekick`, you can declare custom headers in the webhook output:

```yaml
webhook:
  address: "" # Webhook address, if not empty, Webhook output is enabled
  customHeaders: # Custom headers to add in POST, useful for Authentication
    key: value
```

Hope it will help you

Source: https://github.com/falcosecurity/falcosidekick/blob/1ba5f2ca9319a2e1c910df7de22bb12e1b3db7be/config_example.yaml#L117
