### ISSUE TITLE
The outputs throttling mechanism skips notifications without any notice

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1333]
**Motivation**

The current throttling mechanism can be configured within [falco.yaml](https://github.com/falcosecurity/falco/blob/master/falco.yaml) as shown below:

 ```yaml
# A throttling mechanism implemented as a token bucket limits the
# rate of falco notifications. This throttling is controlled by the following configuration
# options:
#  - rate: the number of tokens (i.e. right to send a notification)
#    gained per second. Defaults to 1.
#  - max_burst: the maximum number of tokens outstanding. Defaults to 1000.
#
# With these defaults, falco could send up to 1000 notifications after
# an initial quiet period, and then up to 1 notification per second
# afterward. It would gain the full burst back after 1000 seconds of
# no activity.

outputs:
  rate: 1       
  max_burst: 1000
```

However, when this throttling mechanism takes actions then the user is not informed and AFAIK it's not mentioned anywhere that Falco is just skipping notifications when that happens. This behavior is not related to the very well known "drops" (see #669 for some examples of those).

Furthermore:
- there's no way to disable it
- setting `rate: 0` and `max_burst: 0` just disallow any notifications to be emitted

Finally, it's important to understand that this mechanism affects any output, including the gRPC APIs. Thus, the gRPC consumer must be aware that some events may not arrive. 

**Feature**

Implement a sort of notification or warning message to inform the user that notification could not show up when notification are being rate-limited (as like as we already did with "drops").

Also, add the ability to completely disable the throttling mechanism (ie. no rate-limit).

**Alternatives**

Just document the current behavior to make users aware about it.

**Additional context**

I have discovered this issue when working on https://github.com/falcosecurity/event-generator/pull/36 . Initially, I wrongly thought it was a gRPC problem. Later I got it was just the rate-limit that was affecting all outputs (including gRPC).

Below an example, that shows how notifications are limited up to 1 per second (after an initial burst of 1000 as per the default configuration) though the producer is still generating circa 400 EPS. Please note the timestamps.

[![asciicast](https://asciinema.org/a/350389.svg)](https://asciinema.org/a/350389)
