### ISSUE TITLE
proc.pname is empty for multiple events in Falco 0.24.0

### ISSUE THREAD

**Issue by JPLachance** [falcosecurity/falco#1341]
**Describe the bug**

We did the upgrade from Falco 0.22.1 to Falco 0.24.0 on July 27 2020 in the development environment. Since that date, we saw a very noticeable increase in the number of events reported by Falco. By looking at those events, they all have one thing in common: `proc.pname` is empty. Since multiple macros depends on `proc.pname` value, like the `exe_running_docker_save` macro does, those macros don't do their job anymore and Falco raises multiple false positives.

![Screen Shot 2020-08-04 at 8 41 18 AM](https://user-images.githubusercontent.com/3448802/89295255-b616ab00-d62e-11ea-8f22-df9d4c9212a0.png)

This is a screen capture of all Falco events where `proc.pname` is empty. We see a clear increase since the Falco upgrade near July 27 2020.

We can also see that syscall drop events are increasing.

**How to reproduce it**

Here is a brief description of our setup:
- Create an EKS 1.15 cluster
- Install Falco using a DaemonSet
- On one of the EKS instances, run a container that does Docker in Docker
- Let the Docker in Docker process run for several hours (spinning inner containers, deleting them, creating new ones, etc)

For the Docker in Docker setup, a good example is the Jenkins agent running in EKS and building container images.

**Expected behaviour**

With Falco 0.22.1, `proc.pname` had a value and the `exe_running_docker_save` macro was working.

**Environment**

- Falco version: 0.24.0
- System info:
  ```JSON
  {
    "machine": "x86_64",
    "nodename": "falco-dpm-jwfwr",
    "release": "5.3.0-1030-aws",
    "sysname": "Linux",
    "version": "#32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020"
  }
  ```
- Cloud provider or hardware configuration: AWS
- OS:
  ```SHELL
  PRETTY_NAME="Debian GNU/Linux 10 (buster)"
  NAME="Debian GNU/Linux"
  VERSION_ID="10"
  VERSION="10 (buster)"
  VERSION_CODENAME=buster
  ID=debian
  HOME_URL="https://www.debian.org/"
  SUPPORT_URL="https://www.debian.org/support"
  BUG_REPORT_URL="https://bugs.debian.org/"
  ```
- Kernel: `Linux falco-dpm-jwfwr 5.3.0-1030-aws #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020 x86_64 GNU/Linux`
- Installation method: Kubernetes DaemonSet

**Comment by leogr** [comment]
Hi @JPLachance 

Could you share the DaemonSet manifest? Since this might depend on volume mounts or other options, I would like to reproduce it to dig into this problem.

Thanks in advance!

**Comment by JPLachance** [comment]
Hello!

Here it is:
```YAML
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: falco
  name: falco
  namespace: csec
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: ndev-falco
      labels:
        app: falco
      name: falco
    spec:
      automountServiceAccountToken: true
      containers:
        - image: falcosecurity/falco:0.24.0
          args:
            - /usr/bin/falco
            - -K
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - -k
            - https://kubernetes.default
            - -pk
            - --disable-cri-async
          imagePullPolicy: Always
          name: falco
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              mountPropagation: None
              name: docker-socket
            - mountPath: /host/dev
              mountPropagation: None
              name: dev-fs
            - mountPath: /host/proc
              mountPropagation: None
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              mountPropagation: None
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              mountPropagation: None
              name: lib-modules
              readOnly: true
            - mountPath: /host/usr
              mountPropagation: None
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              mountPropagation: None
              name: etc-fs
              readOnly: true
            - mountPath: /dev/shm
              mountPropagation: None
              name: dshm
            - mountPath: /etc/falco/falco.yaml
              mountPropagation: None
              name: config-volume
              subPath: falco.yaml
            - mountPath: /etc/falco/falco_rules.yaml
              mountPropagation: None
              name: config-volume
              subPath: falco_rules.yaml
            - mountPath: /etc/falco/falco_rules.local.yaml
              mountPropagation: None
              name: config-volume
              subPath: falco_rules.local.yaml
      restartPolicy: Always
      serviceAccount: falco-service-account
      volumes:
        - emptyDir:
            medium: Memory
          name: dshm
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: docker-socket
        - hostPath:
            path: /dev
            type: ""
          name: dev-fs
        - hostPath:
            path: /proc
            type: ""
          name: proc-fs
        - hostPath:
            path: /boot
            type: ""
          name: boot-fs
        - hostPath:
            path: /lib/modules
            type: ""
          name: lib-modules
        - hostPath:
            path: /usr
            type: ""
          name: usr-fs
        - hostPath:
            path: /etc
            type: ""
          name: etc-fs
        - configMap:
            defaultMode: 420
            name: falco-config
          name: config-volume
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
```

Thanks for the help!
