### ISSUE TITLE
Issues getting user_known_package_manager_in_container macro to work properly

### ISSUE THREAD

**Issue by sean-quinn** [falcosecurity/falco#1374]
**Describe the bug**

`user_known_package_manager_in_container` macro is not working to silence legitimate uses of package managers inside of a container. 

**How to reproduce it**
I installed falco via the supported helm chart v1.2.2 and set the custom-rules value in the chart to try and silence alerts we have around a package manager command running in a container that we know about and want to ignore. 

I tried several different iterations to completely silence this alert using a default macro and landed on these to try and stop it from happening:

```
    - macro: user_known_package_manager_in_container
      condition: container
    - macro: user_known_package_manager_in_container
      condition: >
        container.image.repository="myimage"
```
However, the log and alert keeps firing for the host that this container image is running on and looks like `Error Package management process launched in container`.

**Expected behaviour**

I no longer see the `Error Package management process launched in container` log message from Falco.

**Screenshots**

**Environment**

- Falco version:
 0.24.0
- System info:
```
{
  "machine": "x86_64",
  "nodename": "falco-mwj9s",
  "release": "4.19.68-coreos",
  "sysname": "Linux",
  "version": "#1 SMP Wed Sep 4 02:59:18 -00 2019"
}
```
- Cloud provider or hardware configuration:
Kubernetes Cluster on AWS
- OS:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel:
`Linux falco-mwj9s 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 GNU/Linux`
- Installation method:
Kubernetes via Helm

**Additional context**

**Comment by sean-quinn** [comment]
I believe I figured out what was wrong here, if you want to use the same macro on multiple conditions you cannot put them in separate config file entries. 

Ex:
This wont work
```yaml
    - macro: user_known_package_manager_in_container
      condition: >
        container.image.repository="foobar1"
    - macro: user_known_package_manager_in_container
      condition: >
        container.image.repository="foobar2"

```

This will work
```yaml
    - macro: user_known_package_manager_in_container
      condition: >
        (container.image.repository="foobar1" or
        container.image.repository="foobar2")
```
