### ISSUE TITLE
"Error loading rules: unrecognized IPv6 address" although it's an IPv4 address

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/falco#1467]
**Describe the bug**
I'm not able to specify custom IPv4 ranges inside a list. When I run a `helm install` with the `customRules` shown down here, all falco pods crash with the following error:
```bash
* eBPF probe located in /root/.falco/falco_ubuntu-generic_4.15.0-117-generic_118.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o
Tue Nov  3 18:33:46 2020: Falco version 0.26.1 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Tue Nov  3 18:33:46 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Nov  3 18:33:46 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Nov  3 18:33:46 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Nov  3 18:33:46 2020: Loading rules from file /etc/falco/rules.d/rules-example-custom-lists-and-macros:
Tue Nov  3 18:33:46 2020: Loading rules from file /etc/falco/rules.d/rules-enable-unexpected-inbound-connection:
Tue Nov  3 18:33:46 2020: Runtime error: Error loading rules: unrecognized IPv6 address example_allowed_ip_addresses. Exiting.
```

**How to reproduce it**
1. Create the following Helm values:
```yaml
customRules:
  rules-example-custom-lists-and-macros: |-
    - list: example_allowed_ip_addresses
      items: ['"169.254.0.0/24"']

    - list: monitored_directories
      append: true
      items: [/bin, /sbin]

    - list: remote_file_copy_binaries
      append: true
      items: [rcp, ftp]

  rules-enable-unexpected-inbound-connection: |-
    - macro: consider_all_inbound_conns
      condition: (always_true)

    - list: allowed_inbound_source_ipaddrs
      items: ['"0.0.0.0"']

    - list: allowed_inbound_source_networks
      items: [example_allowed_ip_addresses]

    - list: allowed_inbound_source_domains
      items: []

  rules-enable-unexpected-outbound-connection: |-
    - macro: consider_all_outbound_conns
      condition: (always_true)

    - list: allowed_outbound_destination_ipaddrs
      items: ['"0.0.0.0"']

    - list: allowed_outbound_destination_networks
      items: [example_allowed_ip_addresses]

    - list: allowed_outbound_destination_domains
      items: []
```

**Expected behaviour**

Falco should start properly since it works for example with the list `rfc_1918_addresses`. This RFC1918 list uses the exact same syntax to specify the IPv4 address ranges: https://github.com/falcosecurity/falco/blob/294804daf436b4d146731322f46a99e2736feee0/rules/falco_rules.yaml#L331-L332

With this `customRules`, Falco starts without any issues:

```yaml
customRules:
  rules-example-custom-lists-and-macros: |-
    - list: example_allowed_ip_addresses
      items: ['"169.254.0.0/24"']

    - list: monitored_directories
      append: true
      items: [/bin, /sbin]

    - list: remote_file_copy_binaries
      append: true
      items: [rcp, ftp]

  rules-enable-unexpected-inbound-connection: |-
    - macro: consider_all_inbound_conns
      condition: (always_true)

    - list: allowed_inbound_source_ipaddrs
      items: ['"0.0.0.0"']

    - list: allowed_inbound_source_networks
      items: [rfc_1918_addresses]

    - list: allowed_inbound_source_domains
      items: []

  rules-enable-unexpected-outbound-connection: |-
    - macro: consider_all_outbound_conns
      condition: (always_true)

    - list: allowed_outbound_destination_ipaddrs
      items: ['"0.0.0.0"']

    - list: allowed_outbound_destination_networks
      items: [rfc_1918_addresses]

    - list: allowed_outbound_destination_domains
      items: []
```

**Environment**

- Falco version: 0.26.1

- System info: 
```json
{
  "machine": "x86_64",
  "nodename": "node1",
  "release": "4.15.0-117-generic",
  "sysname": "Linux",
  "version": "#118~16.04.1-Ubuntu SMP Sat Sep 5 23:35:06 UTC 2020"
}
```
- Cloud provider or hardware configuration: PKS 1.8.2
- OS: Kubernetes

- Kernel: 4.15.0-117

- Installation method: Kubernetes

**Additional context**

Helm chart version: 1.5.0

Thanks & regards,
Philip

**Comment by PhilipSchmid** [comment]
It must have something to do with the default rule set.

Like this it doesn't complain about anything - it works just perfect:
```yaml
falco:
  ...
  rulesFile:
  - /etc/falco/rules.d
customRules:
  rules-example-custom-lists-and-macros: |-
    - list: example_allowed_ip_addresses
      items: ['"169.254.0.0/24"']
  ...
```

And as soon as I include `/etc/falco/falco_rules.yaml` it breaks and shows the same error again ("unrecognized IPv6 address"):
```yaml
falco:
  ...
  rulesFile:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/rules.d
customRules:
  rules-example-custom-lists-and-macros: |-
    - list: example_allowed_ip_addresses
      items: ['"169.254.0.0/24"']
  ...
```

Any ideas? Thanks!

Regards,
Philip

**Comment by PhilipSchmid** [comment]
I finally found kind of a workaround by simply not assign my `example_allowed_ip_addresses` to another list and use a macro instead:

```yaml
- list: example_allowed_ip_addresses
  items: ['"1.2.3.4/24"']

- list: localhost_linklocal_networks
  items: ['"169.254.0.0/24"', '"127.0.0.0/8"', '"0.0.0.0/32"']

- macro: allowed_internal_ip_communication
  condition: >
    ((fd.cnet in (example_allowed_ip_addresses) or
      fd.cnet in (localhost_linklocal_networks) or
      fd.cnet in (rfc_1918_addresses)) and 
    (fd.snet in (example_allowed_ip_addresses) or
      fd.snet in (localhost_linklocal_networks) or
      fd.snet in (rfc_1918_addresses)))

- rule: Unexpected outbound connection destination
  desc: Detect any outbound connection to a destination outside of an allowed IP networks
  condition: >
    outbound and not (allowed_internal_ip_communication)
  output: Disallowed outbound connection destination (command=%proc.cmdline connection=%fd.name client_ip=%fd.cip destination_ip=%fd.sip user=%user.name user_loginuid=%user.loginuid container_id=%container.id image=%container.image.repository)
  priority: NOTICE
  tags: [network]
  
- rule: Unexpected inbound connection source
  desc: Detect any inbound connection from a source outside of an allowed IP networks
  condition: >
    inbound and not (allowed_internal_ip_communication)
  output: Disallowed inbound connection source (command=%proc.cmdline connection=%fd.name client_ip=%fd.cip destination_ip=%fd.sip user=%user.name user_loginuid=%user.loginuid container_id=%container.id image=%container.image.repository)
  priority: NOTICE
  tags: [network]
```

Nevertheless, I will leave this issue open since to me it still seems like a bug at which a dev should have a look at.

Thanks!

Regards,
Philip
