### ISSUE TITLE
Cannot disable rule with append and enabled

### ISSUE THREAD

**Issue by jemag** [falcosecurity/falco#1510]
**Describe the bug**
Cannot disable rule using documented way, e.g:
``` yaml
- rule: Change thread namespace
  append: true
  enabled: false
```
logs:
```
DKMS: install completed.
* falco module installed in dkms, trying to insmod
* Success: falco module found and loaded in dkms
Mon Dec 14 20:19:49 2020: Falco version 0.26.2 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Mon Dec 14 20:19:49 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Dec 14 20:19:49 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Dec 14 20:19:50 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Dec 14 20:19:51 2020: Loading rules from file /etc/falco/rules.d/custom.local.yaml:
Mon Dec 14 20:19:51 2020: Runtime error: Rule must have property condition
---
- rule: Change thread namespace
  append: true
  enabled: false
---. Exiting.
```
where the custom rules are located in custom.local.yaml and are properly loaded after the falco_rules.yaml file.

It will however work if using the following:
``` yaml
- rule: Change thread namespace
  append: true
  condition: and (never_true)
```
suggesting that the appending is probably working properly and file is loaded in proper order.

**How to reproduce it**
Deploy falco using falco chart with the following values
``` yaml
customRules:
  custom.local.yaml: |-
    - rule: Change thread namespace
      append: true     
      enabled: false
```

**Expected behaviour**

Disables the falco rule

**Environment**

- Falco version:
0.26.2
- System info:
```
Mon Dec 14 20:38:02 2020: Falco version 0.26.2 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Mon Dec 14 20:38:02 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Dec 14 20:38:02 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Dec 14 20:38:03 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Dec 14 20:38:04 2020: Loading rules from file /etc/falco/rules.d/custom.local.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-swwzp",
  "release": "5.4.0-1032-azure",
  "sysname": "Linux",
  "version": "#33~18.04.1-Ubuntu SMP Tue Nov 17 11:40:52 UTC 2020"
}

```
- Cloud provider or hardware configuration:
Azure AKS
