### ISSUE TITLE
kactivity / jevt. rawtime Not Triggering

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/falco#1539]
**Describe the bug**

I was looking at the **k8s_audit_rules.yaml** rules and trying to trigger one the rule **K8s Namespace Created**:

```yaml
- rule: K8s Namespace Created
  desc: Detect any attempt to create a namespace
  condition: (kactivity and kcreate and namespace and response_successful)
  ...
```

However, from my testing, it never triggers. I tested it using the following payload (the exact same payload that the Kubernetes API Server sends):

```json
{"kind":"EventList","apiVersion":"audit.k8s.io/v1","metadata":{},"items":[{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"047a3677-b68c-4f1c-8a10-6e59a5b5ccc7","stage":"ResponseComplete","requestURI":"/api/v1/namespaces?fieldManager=kubectl-create","verb":"create","user":{"username":"kubernetes-admin","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.18.0.1"],"userAgent":"kubectl/v1.19.4 (linux/amd64) kubernetes/d360454","objectRef":{"resource":"namespaces","name":"def","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":201},"requestReceivedTimestamp":"2021-01-27T07:36:30.641811Z","stageTimestamp":"2021-01-27T07:36:30.645337Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}]}
```

by running:

```
curl  -H "Content-Type: application/json" -XPOST -d @/tmp/file.json http://localhost:8765/k8s-audit
```

and I got back a 200 response from the server:

```html
<html><body>Ok</body></html>
```

I know that my rules are working because the "Create Disallowed Namespace" rule triggers

When I removed the **kactivity** requirement in the rule, it triggered. Looking at the definition of kactivity, I found that:

```yaml
- macro: consider_activity_events
  condition: (k8s_audit_always_true)

- macro: kactivity
  condition: (kevt and consider_activity_events)
```

which finally leads me to this:

```yaml
- macro: k8s_audit_always_true
  condition: (jevt.rawtime exists)
```

so it looks like jevt.rawtime doesn't exist. Any ideas?

**How to reproduce it**

See above

**Expected behaviour**

The rule should have triggered

**Screenshots**

**Environment**

- Falco version:

```
$ falco --version
Falco version: 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750
```
- System info:

```json
{
  "machine": "x86_64",
  "nodename": "dell",
  "release": "5.8.0-36-generic",
  "sysname": "Linux",
  "version": "#40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021"
}
```
- Cloud provider or hardware configuration:
- OS:

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel:

```
Linux dell 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:

Linux binary

**Additional context**

**Comment by ossie-git** [comment]
Sorry. It was a silly mistake. I forget to add:

```yaml
- list: k8s_audit_stages
  items: ["ResponseComplete"]

- macro: kevt
  condition: (jevt.value[/stage] in (k8s_audit_stages))
```

to my rules file
