### ISSUE TITLE
First Rule Wins / Rule Priority

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/falco#1541]
**What to document**

The fact that given an event, only the first rule / match triggers isn't currently documented. This is confusing (and makes writing rules more difficult). 

For example, if a user runs the "ls" command with the below rules, only the first rule will run

```yaml
- rule: ls run
  desc: ls run
  condition: spawned_process and proc.name=ls
  output: ls run
  priority: INFO
  tags: [process]
 
- rule: ls run - 2
  desc: ls run - 2
  condition: spawned_process and proc.name=ls
  output: ls run - 2
  priority: INFO
  tags: [process]
```

This is unexpected behavior and not documented anywhere. It would be great if this behavior was documented in:

- the official documentation
- the corresponding rules files as a reminder

to make it clear to users that this is Falco's behavior
