### ISSUE TITLE
ECR repos are not considered in comparisons when provided via list

### ISSUE THREAD

**Issue by lilley2412** [falcosecurity/falco#1582]
**Describe the bug**

ECR repositories (like 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni) are not considered in comparison operations with `container.image.repository` when sourced from a list, therefore the current default ruleset in 0.27.0 is not providing exceptions for AWS EKS images.

It appears to be an issue with how list items are consumed when items begin with digits.

**How to reproduce it**

#### Out of the box default rulesets:

1. Install falco with the default ruleset in EKS 1.18 using the helm chart
1. Observe rules firing for `Launch Sensitive Mount Container` and `Launch Privileged Container` for `.amazonaws.com/amazon-k8s-cni` and `.amazonaws.com/eks/kube-proxy`.

#### Demonstrate string parsing error with a custom rule using a list:

Given a custom rule configured via helm chart (note the order of items in `list: ecr_repo_demo_list`):
```
customRules:
  rules-ecr-defect.yaml: |
    - list: ecr_repo_demo_list
      items:
      - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni"
      - starts-with-string
    - rule: Demonstrate ECR Issue
      desc: Detect the launch of an ECR container
      condition: >
        container_started 
        and container
        and container.image.repository in (ecr_repo_demo_list)
      output: ECR container started (repo=%container.image.repository)
      priority: INFO
```
 1. Deploy falco with the custom rule
 2. Observe a compilation error:
 ```
 falco-m4mks falco Thu Mar 18 14:18:16 2021: Runtime error: Compilation error when compiling "container_started  and container and container.image.repository in (602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni, starts-with-string)
falco-m4mks falco ": 82: syntax error, unexpected 'dkr', expecting ')', ','
```
3. Change the order of list items to eliminate compilation error:
```
customRules:
  rules-ecr-defect.yaml: |
    - list: ecr_repo_demo_list
      items:
      - starts-with-string
      - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni"
```
4. The rule will now load, but it will never fire because it is not considering the second list item that begins with digits.  

#### Demonstrate working rule using string equality without a list

The following rule works as expected:
```
customRules:
  rules-ecr-defect.yaml: |
    - rule: Demonstrate ECR Issue
      desc: Detect the launch of an ECR container
      condition: >
        container_started 
        and container
        and container.image.repository="602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni"
      output: ECR container started (repo=%container.image.repository)
      priority: INFO
```

**Expected behaviour**

Quoted list items should be evaluated as string and behave the same way in rules as non-list string comparisons.

**Screenshots**

**Environment**

- Falco version: 
```
Falco version: 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "falco-44s79",
  "release": "4.14.209-160.339.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Wed Dec 16 22:44:04 UTC 2020"
}
```

- Cloud provider or hardware configuration: 

EKS 1.18

- OS: 

debian

- Kernel: 

Linux falco-44s79 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 GNU/Linux

- Installation method:

In-cluster EKS installed via helm

**Additional context**

**Comment by leodido** [comment]
I confirm that this behavior is misleading and could also be considered a bug.

Some thoughts.

Could you try with?

```yaml
- list: ecr_repo_demo_list
      items:
      - "'602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni'"
      - starts-with-string
```

Notice the single quotes.

This should make the first list item be considered as a single-quoted string literal, not as a bare string (it seems the original double quotes get removed during the YAML parsing) which causes the rule compilation error after the dot (ie, `dkr`).
