### ISSUE TITLE
Running Falco as daemonset fails

### ISSUE THREAD

**Issue by alterEgo123** [falcosecurity/falco#1642]
**Describe the bug**
I'm unable to run Falco as a daemonset in my Kubernetes cluster.

```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.28.0, driver version=5c0b863ddade7a45568c0ac97d037422c9efb750
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to load a system falco module, if present
* Looking for a falco module locally (kernel 4.18.0-240.10.1.el8_3.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/5c0b863ddade7a45568c0ac97d037422c9efb750/falco_centos_4.18.0-240.10.1.el8_3.x86_64_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5c0b863ddade7a45568c0ac97d037422c9efb750/build/make.log (with GCC /usr/bin/gcc)
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5c0b863ddade7a45568c0ac97d037422c9efb750/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5c0b863ddade7a45568c0ac97d037422c9efb750/build/make.log (with GCC /usr/bin/gcc-6)
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5c0b863ddade7a45568c0ac97d037422c9efb750/build/make.log (with GCC /usr/bin/gcc-5)
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
Thu May  6 13:46:53 2021: Falco version 0.28.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Thu May  6 13:46:53 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Thu May  6 13:46:53 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Thu May  6 13:46:53 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu May  6 13:46:53 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Thu May  6 13:46:54 2021: Unable to load the driver.
Thu May  6 13:46:54 2021: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

**How to reproduce it**
Kubectl apply this file: 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-daemonset
  labels:
    app: falco-example
    role: security
spec:
  selector:
    matchLabels:
      app: falco-example
      role: security
  template:
    metadata:
      labels:
        app: falco-example
        role: security
    spec:
      serviceAccount: falco-account
      containers:
        - name: falco
          image: falcosecurity/falco:0.28.0 # Change version to latest or master when Falco is stable
          securityContext:
            privileged: true
# Uncomment the 3 lines below to enable eBPF support for Falco.
# This allows Falco to run on Google COS.
# Leave blank for the default probe location, or set to the path
# of a precompiled probe.
#          env:
#          - name: FALCO_BPF_PROBE
#            value: ""
          args: [ "/usr/bin/falco", "--cri", "/host/run/containerd/containerd.sock", "-K", "/var/run/secrets/kubernetes.io/serviceaccount/token", "-k", "https://$(KUBERNETES_SERVICE_HOST)", "-pk"]
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /host/dev
              name: dev-fs
              readOnly: true
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc/
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco
              name: falco-config
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: falco-config
          configMap:
            name: falco-config
```

**Expected behaviour**

Run Falco as a daemonset

**Screenshots**

**Environment**

- Falco version: 0.28.0

- System info: Thu May  6 09:46:29 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Thu May  6 09:46:29 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Thu May  6 09:46:29 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu May  6 09:46:29 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "master1",
  "release": "4.18.0-240.10.1.el8_3.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Jan 18 17:05:51 UTC 2021"
}

- Cloud provider or hardware configuration:
- OS: NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

- Kernel: Linux master1 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Installation method: Kubernetes

**Additional context**
