### ISSUE TITLE
Unable to monitor syscall open_by_handle_at

### ISSUE THREAD

**Issue by yuchunyu97** [falcosecurity/falco#1670]
**Describe the bug**

Unable to monitor syscall open_by_handle_at. The program cannot be started.

Startup log:

```bash
...
2021-06-08T11:34:38+0000: Runtime error: Could not load rules file /etc/falco/falco_rules.local.yaml: Error loading rules: /usr/share/falco/lua/sinsp_rule_utils.lua:129: Unknown event/syscall "open_by_handle_at" in filter: evt.type=open_by_handle_at. Exiting.
```

**How to reproduce it**

Use the following rule and start falco.

```yaml
- rule: Shocker Attack
  desc: Shocker Attack
  condition: evt.type=open_by_handle_at
  output: Shocker Attack, type=%evt.type, syscall=%syscall.type
  priority: Warning
  tags: []
```

**Expected behaviour**

The program starts normally.

**Screenshots**

**Environment**

- Falco version:

```bash
Falco version: 0.28.2
Driver version: 13ec67ebd23417273275296813066e07cb85bc91
```
- System info: 
```bash
Linux ecs 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Cloud provider or hardware configuration: ECS
- OS: Ubuntu 18.04.5

- Kernel: 4.15.0-20-generic

- Installation method: DEB

**Additional context**
