### ISSUE TITLE
Falco fails with "PERF_EVENT_IOC_SET_BPF: Errno 17."

### ISSUE THREAD

**Issue by eelkonio** [falcosecurity/falco#1703]
**Describe the bug**

When running Falco on EKS 1.18 in a protected VPC (no connections to the outside world permitted), it fails to download or compile without adjustments. That is expected, but after some amendments it compiles succesfully for the system it is in, but fails with error "PERF_EVENT_IOC_SET_BPF: Errno 17."

**How to reproduce it**

1. Download Falco helm chart
2. Add kernel-headers to the node(s) of your cluster, using `sudo yum -y install kernel-devel-$(uname -r)`
3. Add /lib/modules/XYZ and /usr/src/kernels/XYZ as mounted volumes to the falco-daemonset so make can compile
4. adjust the repo/image location to suit our security system (copy it from docker-hub falcosecurity/falco:0.29.1 )
5. go into the pod, run /usr/bin/falco-driver-loader and falco itself (see logs below)
6. watch it fail, weep

See this slightly adjusted daemonset yaml:
```
# Source: falco/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falcoissue
  namespace: monitoring
  labels:
    app: falcoissue
    chart: "falco-1.15.7"
    release: "falcoissue"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: falcoissue
      role: security
  template:
    metadata:
      name: falcoissue
      labels:
        app: falcoissue
        role: security
      annotations:
        checksum/config: 5c50e80b550a38b02b29a0b8dc740d78fc4c64e178909c6740a6968276dbc672
        checksum/rules: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/certs: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        ignore-nodeselector: "1"
    spec:
      serviceAccountName: falco
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: falco
          image: my-internal-repo-proxy.com/k8s/falco:v0.29.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            privileged: true
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30000000000000; done;" ]
          env:
            - name: FALCO_CMD
              value: /usr/bin/falco --cri /run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k https://$(KUBERNETES_SERVICE_HOST) -pk
            - name: FALCO_BPF_PROBE
              value: 
            - name: "PROBE_URL"
              value: ""
          volumeMounts:
            - mountPath: /lib/modules/4.14.238-182.421.amzn2.x86_64
              name: modulelibs
            - mountPath: /usr/src/kernels/4.14.238-182.421.amzn2.x86_64
              name: kernelstuff
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /host/dev
              name: dev-fs
              readOnly: true
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco
              name: config-volume
      volumes:
        # Add /lib/modules/ from the host to this pod
        - name: modulelibs
          hostPath:
            path: /lib/modules/4.14.238-182.421.amzn2.x86_64
            type: Directory
        # Add kernel source stuff from the host to this pod
        - name: kernelstuff
          hostPath:
            # directory location on host
            path: /usr/src/kernels/4.14.238-182.421.amzn2.x86_64
            # this field is optional
            type: Directory
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: config-volume
          configMap:
            name: falcoissue
            items:
              - key: falco.yaml
                path: falco.yaml
              - key: falco_rules.yaml
                path: falco_rules.yaml
              - key: falco_rules.local.yaml
                path: falco_rules.local.yaml
              - key: application_rules.yaml
                path: rules.available/application_rules.yaml
              - key: k8s_audit_rules.yaml
                path: k8s_audit_rules.yaml
  updateStrategy:
    type: RollingUpdate
```

You can go into the pod and manually run /usr/bin/falco-driver-loader and /usr/bin/falco now:

```
root@ip-1-2-3-4:/# /usr/bin/falco-driver-loader 
* Running falco-driver-loader for: falco version=0.29.1, driver version=17f5df52a7d9ed6bb12d3b1768460def8439936d
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/17f5df52a7d9ed6bb12d3b1768460def8439936d/falco_amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.o
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to download.falco.org:443 
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.o)
* eBPF probe located in /root/.falco/falco_amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o

root@ip-1-2-3-4:/# echo $FALCO_CMD
/usr/bin/falco --cri /run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k https://172.20.0.1 -pk

root@ip-1-2-3-4:/# /usr/bin/falco --cri /run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k https://172.20.0.1 -pk
Tue Aug 10 11:03:23 2021: Falco version 0.29.1 (driver version 17f5df52a7d9ed6bb12d3b1768460def8439936d)
Tue Aug 10 11:03:23 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Aug 10 11:03:23 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Aug 10 11:03:23 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Aug 10 11:03:23 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Aug 10 11:03:23 2021: Unable to load the driver.
Tue Aug 10 11:03:24 2021: Runtime error: PERF_EVENT_IOC_SET_BPF: Errno 17. Exiting.

```

**Expected behaviour**

After building the probe and kernel module, falco should run without problems.

**Environment**

- Falco version:
```Falco version: 0.29.1
Driver version: 17f5df52a7d9ed6bb12d3b1768460def8439936d```

- System info:
<!-- Falco has a built-in support command you can use  "falco --support | jq .system_info" -->
```Tue Aug 10 11:47:28 2021: Falco version 0.29.1 (driver version 17f5df52a7d9ed6bb12d3b1768460def8439936d)
Tue Aug 10 11:47:28 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Aug 10 11:47:28 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Aug 10 11:47:28 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Aug 10 11:47:28 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "ip-10-32-178-86.np18.aws.local",
  "release": "4.14.238-182.421.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Jul 12 21:54:23 UTC 2021"
}
```

- Cloud provider or hardware configuration: AWS EKS 1.18
- OS:
```root@ip-10-32-178-86:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel:
```Linux ip-10-32-178-86.np18.aws.local 4.14.238-182.421.amzn2.x86_64 #1 SMP Mon Jul 12 21:54:23 UTC 2021 x86_64 GNU/Linux```

- Installation method: helm chart v0.29.1 from https://github.com/falcosecurity/falco

**Additional context**
