### ISSUE TITLE
Falco daemonset pod fails to retreive container field class values when docker.sock volume mount is removed

### ISSUE THREAD

**Issue by karthikc911** [falcosecurity/falco#1705]
**Description**
Docker is being deprecated in Kubernetes versions 1.20 or above and hence Falco docker container need to depend only on containerd.sock to retrieve container field class values rather than depending on docker.sock.

**How to reproduce it**

1) Setup a Kubernetes cluster running containerd on kubernetes node.
2) Make sure containerd socket path is _/run/containerd/containerd.sock_
```
$ sudo ss -l -p | grep /run/containerd/containerd.sock
u_str             LISTEN              0                    128                                                            /run/containerd/containerd.sock.ttrpc 20956                                                      * 0                   users:(("containerd",pid=3412,fd=12))
u_str             LISTEN              0                    128                                                                  /run/containerd/containerd.sock 20958                                                      * 0                   users:(("containerd",pid=3412,fd=14))
```
3) Deploy Falco as daemonset on a kubernetes cluster using pattern : https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/falco/templates but remove the docker-socket volume mount in https://github.com/falcosecurity/evolution/blob/master/deploy/kubernetes/falco/templates/daemonset.yaml. So the updated daemonset.yaml would be something like below : 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: default
  labels:
    app: falco
    chart: "falco-1.15.7"
    release: "falco"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: falco
      role: security
  template:
    metadata:
      name: falco
      labels:
        app: falco
        role: security
      annotations:
        checksum/config: b3e7235ffa87a7967af2b7acfb01e2f827cc2f50b18c466f64c6bb64b386244b
        checksum/rules: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/certs: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: falco
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: falco
          image: docker.io/falcosecurity/falco:0.29.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            privileged: true
          args:
            - /usr/bin/falco
            - --cri
            - /run/containerd/containerd.sock
            - -K
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - -k
            - https://$(KUBERNETES_SERVICE_HOST)
            - -pk
          env:
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 8765
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 8765
          volumeMounts:
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /host/dev
              name: dev-fs
              readOnly: true
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco
              name: config-volume
      volumes:
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: config-volume
          configMap:
            name: falco
            items:
              - key: falco.yaml
                path: falco.yaml
              - key: falco_rules.yaml
                path: falco_rules.yaml
              - key: falco_rules.local.yaml
                path: falco_rules.local.yaml
              - key: application_rules.yaml
                path: rules.available/application_rules.yaml
  updateStrategy:
    type: RollingUpdate

```
4) Run tests for falco rules dependent on container field class values or print container field class values in any falco alert output.
5) We should observe the issue that Falco rule dependent on container field class values does not execute and if container field class values are printed in Falco alert output then the values would be null : 
```
{"output":"05:02:19.853197342: Alert output shell_id=37591 session_id=3412 user=<NA> command=nc -h parent_process=sh container_id=8975dcaeffae container_name=<NA> image=<NA>:<NA>) k8s.ns=falco-ns k8s.pod=test-deployment-798 container=8975dcaeffae k8s.ns=falco-ns k8s.pod=test-deployment-798 container=8975dcaeffae k8s.ns=falco-ns k8s.pod=test-deployment-798 container=8975dcaeffae","priority":"Alert","rule":"Launch Suspicious Network Tool in Container","time":"2021-08-03T05:02:19.853197342Z", "output_fields": {"container.id":"8975dcaeffae","container.image.repository":null,"container.image.tag":null,"container.name":null,"evt.time":1627966939853197342,"k8s.ns.name":"falco-ns","k8s.pod.name":"test-deployment-798","proc.cmdline":"nc -h","proc.loginshellid":37591,"proc.pname":"sh","proc.sid":3412,"user.name":null}}
```

**Expected behaviour**
Since there is already support for running containerd with falco , there should not be any change in behaviour of falco docker container when docker-socket volume mount is removed.

**Screenshots**

**Environment**

- Falco version: 0.29.1 (All versions)

- System info:

- Cloud provider or hardware configuration: AWS cloud
- OS:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel: Linux ip-10-235-245-87.vpc.internal 4.14.232-176.381.amzn2.x86_64 #1 SMP Wed May 19 00:31:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Installation method: Kubernetes 

**Additional context**
I tried installing Falco agent directly on Kubernetes node running Amazon Linux using instructions  : https://falco.org/docs/getting-started/installation/#centos-rhel and connected to containerd.sock running on host and Falco runs as expected without any issues where container field values are not null.
```
$ sudo rpm --import https://falco.org/repo/falcosecurity-3672BA8F.asc
$ sudo curl -s -o /etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm.repo
$ sudo yum -y install kernel-devel-$(uname -r)
$ sudo yum -y install falco
$ sudo /usr/bin/falco --cri /run/containerd/containerd.sock -pk
Mon Aug  9 20:24:46 2021: Falco version 0.29.1 (driver version 17f5df52a7d9ed6bb12d3b1768460def8439936d)
Mon Aug  9 20:24:46 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Aug  9 20:24:46 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Aug  9 20:24:46 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Aug  9 20:24:46 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Mon Aug  9 20:24:46 2021: Starting internal webserver, listening on port 8765
20:24:46.812282000: Notice Privileged container started (user=root user_loginuid=0 command=container:f49d9335fb7e k8s.ns=kube-system k8s.pod=calico-node-lwdwc container=f49d9335fb7e image=docker.intuit.com/docker-rmt/calico/node:v3.15.1) k8s.ns=kube-system k8s.pod=calico-node-lwdwc container=f49d9335fb7e k8s.ns=kube-system k8s.pod=calico-node-lwdwc container=f49d9335fb7e
20:24:46.814826000: Notice Privileged container started (user=root user_loginuid=0 command=container:6d0dab008feb k8s.ns=kube-system k8s.pod=node-local-dns-8mwgs container=6d0dab008feb image=docker.intuit.com/k8s-rmt/dns/k8s-dns-node-cache:1.16.0) k8s.ns=kube-system k8s.pod=node-local-dns-8mwgs container=6d0dab008feb k8s.ns=kube-system k8s.pod=node-local-dns-8mwgs container=6d0dab008feb
```
