### ISSUE TITLE
Syscall event drop.

### ISSUE THREAD

**Issue by Slezhuk** [falcosecurity/falco#1743]
**Describe the bug**
Falco v0.29.1 installed Debian 10 as deb package generates a lot of syscall drop events. Dropping syscall events can lead to false positive and false negative alerts by Falco. I have followed checklist at #1403, but with no luck, issue still persist.

**How to reproduce it**
- Install Falco v0.29.1 as deb package on Debian 10.
- Run Falco as systemd service with default config.
- Given enough load on host, Falco starts to drop syscall events.

**Expected behaviour**
Falco not drop syscall events

**Screenshots**

**Environment**

- Falco version:

```
Falco version: 0.29.1
Driver version: 17f5df52a7d9ed6bb12d3b1768460def8439936d
```
- System info:

```
{
  "machine": "x86_64",
  "nodename": "s4819",
  "release": "4.19.0-8-amd64",
  "sysname": "Linux",
  "version": "#1 SMP Debian 4.19.98-1 (2020-01-26)"
}
```
- Cloud provider or hardware configuration:
Dedicated hardware server:
`ProLiant DL360 G7`
```
Processor Information
	Socket Designation: Proc 2
	Type: Central Processor
	Family: Xeon
	Manufacturer: Intel
	ID: C2 06 02 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 44, Stepping 2
	Version: Intel(R) Xeon(R) CPU X5650 @ 2.67GHz
	Voltage: 1.4 V
	External Clock: 133 MHz
	Max Speed: 4800 MHz
	Current Speed: 2667 MHz
	Status: Populated, Idle
	Upgrade: Socket LGA1366
	L1 Cache Handle: 0x0716
	L2 Cache Handle: 0x0726
	L3 Cache Handle: 0x0736
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 6
	Core Enabled: 6
	Thread Count: 12
	Characteristics:
		64-bit capable
```
- OS:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel:

```
Linux s4819 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```
- Installation method:

DEB

**Additional context**
Host have moderately high load: LA 15-20 with 24 CPU.
Examples of alerts in logs about dropping events:
```
Sep 29 18:14:43 s4819 falco[22540]: {"output":"Falco internal: syscall event drop. 946850 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"946850","n_drops_buffer":"946846","n_drops_bug":"0","n_drops_pf":"4","n_evts":"981441"},"priority":"Debug","rule":"Falco internal: syscall event drop","time":"2021-09-29T15:14:01.082448282Z"}
Sep 29 18:15:15 s4819 falco[22540]: {"output":"Falco internal: syscall event drop. 639561 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"639561","n_drops_buffer":"639561","n_drops_bug":"0","n_drops_pf":"0","n_evts":"640857"},"priority":"Debug","rule":"Falco internal: syscall event drop","time":"2021-09-29T15:14:31.933908030Z"}
```

Falco run with options:
`/usr/bin/falco --pidfile=/var/run/falco.pid`

Contents of falco.yaml:
```
rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/k8s_audit_rules.yaml
  - /etc/falco/rules.d
time_format_iso_8601: false
json_output: true
json_include_output_property: true
log_stderr: true
log_syslog: true
log_level: info
priority: debug
buffered_outputs: false
syscall_event_drops:
  threshold: .1
  actions:
    - log
    - alert
  rate: .03333
  max_burst: 1
syscall_event_timeouts:
  max_consecutives: 1000
output_timeout: 2000
outputs:
  rate: 1
  max_burst: 1000
syslog_output:
  enabled: true
file_output:
  enabled: false
  keep_alive: false
  filename: ./events.txt
stdout_output:
  enabled: true
webserver:
  enabled: true
  listen_port: 8765
  k8s_audit_endpoint: /k8s-audit
  k8s_healthz_endpoint: /healthz
  ssl_enabled: false
  ssl_certificate: /etc/falco/falco.pem
program_output:
  enabled: false
  keep_alive: false
  program: "jq '{text: .output}' | curl -d @- -X POST https://hooks.slack.com/services/XXX"
http_output:
  enabled: false
grpc:
  enabled: false
  bind_address: "unix:///var/run/falco.sock"
  # when threadiness is 0, Falco automatically guesses it depending on the number of online cores
  threadiness: 0
grpc_output:
  enabled: false
```
