### ISSUE TITLE
falco: the --k8s-node cmdline option doesn't do validation and the example helm chart usage is invalid

### ISSUE THREAD

**Issue by dnwe** [falcosecurity/falco#1786]
**Describe the bug**

Whilst trying to make use of the new `--k8s-node` parameter, we couldn't understand why our deployment integration-tests were all failing. It turns out that the example usage mentioned in the PR https://github.com/falcosecurity/falco/pull/1671 is invalid. When [using environment variables inside of your config](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config) they must be specified in a bracketed templating style of `$(VARIABLE)` and *not* a standard shell style of `$VARIABLE` or `${VARIABLE}`

**How to reproduce it**

Deploy falco with the example given from the PR which uses the correct style for KUBERNETES_SERVICE_HOST but not for MY_NODE_NAME:

```yaml
...
    containers:
        - name: falco
        ...
          args:
            - /usr/bin/falco
            - --cri
            - /run/containerd/containerd.sock
            - -K
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - -k
            - "https://$(KUBERNETES_SERVICE_HOST)"
            - -pk
            - --k8s-node
            - "${MY_NODE_NAME}"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
...
```

As a result Falco ends up passing `${MY_NODE_NAME}` [sic] on its field-selector which of course silently doesn't match any available node(s).

**Expected behaviour**

Ideally falco should fetch the available nodes in the cluster and refuse to startup unless the provided k8s-node option matches one that is available within the cluster. Alternatively it could reject a value that starts with a `$` and indicate to the user that they've likely failed to correct pass a substitution variable to falco's cmdline.
