### ISSUE TITLE
K8s audit: a lot of anonymous user rule outputs for `/readyz` and `/livez`

### ISSUE THREAD

**Issue by brumhard** [falcosecurity/falco#1794]
**Motivation**

I've just tried falco on Kubernetes for the first time and noticed a lot of log messages like the following which polluted the logs.
```
Nov 18 11:16:43 cp falco[28445]: 11:16:34.791667968: Warning Request by anonymous user allowed (user=system:anonymous verb=get uri=/readyz reason=RBAC: allowed by ClusterRoleBinding "system:public-info-viewer" of ClusterRole "system:public-info-viewer" to Group "system:unauthenticated"))
```

I worked around this by adding the following to the anonymous user role in `/etc/falco/k8s_audit_rules.yaml`:
```yaml
- macro: ready_endpoint
  condition: ka.uri=/readyz

- macro: live_endpoint
  condition: ka.uri=/livez

- rule: Anonymous Request Allowed
  condition: kevt and ka.user.name=system:anonymous and ka.auth.decision="allow" and not health_endpoint and not ready_endpoint and not live_endpoint
```

**Feature**

I was wondering if this should be added as a default to the default audit rules shipped with falco, since `/healthz` is already also ignored. If so I'd be glad to open a PR.
