### ISSUE TITLE
Falco sending wrong image name in output

### ISSUE THREAD

**Issue by vennemp** [falcosecurity/falco#1833]
I am running falco in a test EKS with the default rule set and it is generating the wrong the container image name.

Falco rule shown below
```yaml
- rule: Launch Privileged Container
  desc: Detect the initial process started in a privileged container. Exceptions are made for known trusted images.
  condition: >
    container_started and container
    and container.privileged=true
    and not falco_privileged_containers
    and not user_privileged_containers
  output: Privileged container started (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline %container.info image=%container.image.repository:%container.image.tag)
  priority: INFO
  tags: [container, cis, mitre_privilege_escalation, mitre_lateral_movement]
```

Here is the output of the logs:
Event #1
```json
{
    "output": "03:51:37.972294000: Notice Privileged container started (user=root user_loginuid=0 command=container:dc2e2cca4219 k8s.ns=kube-system k8s.pod=kube-proxy-d9nfs container=dc2e2cca4219 image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1) k8s.ns=kube-system k8s.pod=kube-proxy-d9nfs container=dc2e2cca4219",
    "priority": "Notice",
    "rule": "Launch Privileged Container",
    "source": "syscall",
    "tags": [
        "cis",
        "container",
        "mitre_lateral_movement",
        "mitre_privilege_escalation"
    ],
    "time": "2022-01-01T03:51:37.972294000Z",
    "output_fields": {
        "container.id": "dc2e2cca4219",
        "container.image.repository": "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause",
        "container.image.tag": "3.1-eksbuild.1",
        "evt.time": 1641009097972294000,
        "k8s.ns.name": "kube-system",
        "k8s.pod.name": "kube-proxy-d9nfs",
        "proc.cmdline": "container:dc2e2cca4219",
        "user.loginuid": 0,
        "user.name": "root"
    }
}
```
```json
{
    "output": "03:51:37.990816000: Notice Privileged container started (user=<NA> user_loginuid=0 command=container:32e82631daf4 k8s.ns=kube-system k8s.pod=aws-node-nslqw container=32e82631daf4 image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1) k8s.ns=kube-system k8s.pod=aws-node-nslqw container=32e82631daf4",
    "priority": "Notice",
    "rule": "Launch Privileged Container",
    "source": "syscall",
    "tags": [
        "cis",
        "container",
        "mitre_lateral_movement",
        "mitre_privilege_escalation"
    ],
    "time": "2022-01-01T03:51:37.990816000Z",
    "output_fields": {
        "container.id": "32e82631daf4",
        "container.image.repository": "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause",
        "container.image.tag": "3.1-eksbuild.1",
        "evt.time": 1641009097990816000,
        "k8s.ns.name": "kube-system",
        "k8s.pod.name": "aws-node-nslqw",
        "proc.cmdline": "container:32e82631daf4",
        "user.loginuid": 0,
        "user.name": null
    }
}
```
```json
{
    "output": "03:51:38.006493000: Notice Privileged container started (user=<NA> user_loginuid=0 command=container:109a0a15dc7a k8s.ns=default k8s.pod=falco-q4pp8 container=109a0a15dc7a image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1) k8s.ns=default k8s.pod=falco-q4pp8 container=109a0a15dc7a",
    "priority": "Notice",
    "rule": "Launch Privileged Container",
    "source": "syscall",
    "tags": [
        "cis",
        "container",
        "mitre_lateral_movement",
        "mitre_privilege_escalation"
    ],
    "time": "2022-01-01T03:51:38.006493000Z",
    "output_fields": {
        "container.id": "109a0a15dc7a",
        "container.image.repository": "602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause",
        "container.image.tag": "3.1-eksbuild.1",
        "evt.time": 1641009098006493000,
        "k8s.ns.name": "default",
        "k8s.pod.name": "falco-q4pp8",
        "proc.cmdline": "container:109a0a15dc7a",
        "user.loginuid": 0,
        "user.name": null
    }
}
```

Notice that the container.image.repository is showing: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause for all 3 - even for Falco itself!

I am using image: docker.io/falcosecurity/falco:0.30.0 - which appears to be latest and default in the helm chart.
