### ISSUE TITLE
Unconsistent behavior with plugin settings when yaml format is used

### ISSUE THREAD

**Issue by Issif** [falcosecurity/falco#1906]
**Describe the bug**

When we set `init_config` of a plugin, we can use yaml format and it's converted into json by falco directly. I notice an inconsistent behavior when fields have not same order.

**How to reproduce it**

This works:
```yaml
plugins:
  - name: twitter
    library_path: /usr/share/falco/plugins/libtwitter.so
    init_config:
      rules:
        - cat has:images
        - dog has:images
      flushinterval: 1000
```
But this one, crashes:
```yaml
plugins:
  - name: twitter
    library_path: /usr/share/falco/plugins/libtwitter.so
    init_config:
      flushinterval: 1000
      rules:
        - cat has:images
        - dog has:images
```
with this error `Runtime error: Error reading config file(falco.yaml): could not load plugins config: [json.exception.type_error.311] cannot use emplace_back() with number. Exiting.`

**Expected behaviour**

yaml  syntax should work whatever the order of fields

**Screenshots**

**Environment**

- Falco version: 0.31

- System info: 
```json
{
  "machine": "x86_64",
  "nodename": "falco",
  "release": "5.13.0-28-generic",
  "sysname": "Linux",
  "version": "#31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022"
}
```

- Cloud provider or hardware configuration:
- OS: Ubuntu 21.10

- Kernel:

- Installation method:

**Additional context**
