### ISSUE TITLE
Missed events in a short-lived container running as a CronJob

### ISSUE THREAD

**Issue by abroglesc** [falcosecurity/falco#2013]
**Describe the bug**

_Falco_ didn't capture event(s) in a _container_ running as a _CronJob_.

**How to reproduce it**

Create a _shell script_ similar to `test.sh`:
```bash
#!/bin/bash

set -euxo pipefail

touch "/etc/test.txt"
```

Use a _CronJob_ to execute the `test.sh`:
```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: falco-test-cronjob
            image: # YOUR IMAGE
            command: ["/bin/bash", "test.sh"]
            volumeMounts:
            - mountPath: /host
              name: host-mount
            securityContext:
              privileged: true
          restartPolicy: OnFailure
          serviceAccountName: random-sa-name
          volumes:
          - name: host-mount
            hostPath:
              path: /
              type: Directory
```

**Expected behaviour**

The used rule set is correct. Confirmed by observing similar type of events for _containers_ that run for a longer period of time
than the _container_ used to run the test case (in `test.sh`).

Observe (at least):
- creation of a new process
```
execve("/usr/bin/touch", ["touch", "/etc/test.txt"], 0x7fff176111d8 /* 60 vars */) = 0
```
- opening and possibly creation of a file
```
openat(AT_FDCWD, "/etc/test.txt", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 3
```

**Environment**

- System info:
```
# falco --support | jq .system_info
Mon May 23 16:28:03 2022: Falco version 0.31.1
Mon May 23 16:28:03 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Mon May 23 16:28:03 2022: Loading rules from file /rules/falco_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "redacted",
  "release": "5.4.170+",
  "sysname": "Linux",
  "version": "#1 SMP Wed Mar 23 10:13:41 PDT 2022"
}
```

- Cloud provider or hardware configuration:
GKE

- OS:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel:
```
Linux gke-k8s-{redacted} 5.4.170+ #1 SMP Wed Mar 23 10:13:41 PDT 2022 x86_64 GNU/Linux
```
- Installation method:
Kubernetes; Part of a _daemon set_ running in a _non-privileged_ container_.

**Additional context**

Introducing a delay (ex: `sleep 10`) before `touch "/etc/test.txt"` eliminates the issue.

**Comment by cpungasc** [comment]
> Could you try to disable the K8s metadata support by removing `-k` / `-K` ? (just for debugging purposes)
> 
> Thanks in advance.

Thanks for getting back so fast.

I followed your advice and disabled `-k` and `-K`. After 3 manual tests: **the events were successfully captured**.

We are curious, when _falco_ fails to enrich metadata and doesn't find the _pod_ or the _container_, is it silently dropping the events? Can we log the failed state or be aware of it, please?

Thank you!

**Comment by leogr** [comment]
I had a suspect, and you confirmed it :) 
However, I'm not yet sure which is the root cause.

> We are curious, when _falco_ fails to enrich metadata and doesn't find the _pod_ or the _container_, is it silently dropping the events? Can we log the failed state or be aware of it, please?

Falco should not drop in this case. When some metadata is missing, the expected behavior is to emit the alert without the missing metadata. 

The cause of the wrong behavior may be either:

-  Falco is actually dropping the event (because for some reason processing that event takes too long) and the syscall dropping [threshold](https://github.com/falcosecurity/falco/blob/13d70b65ae6839ccb3172720f715a86719eeee26/falco.yaml#L135) setting hides the dropping notification (could you try with `threshold: 0`? you should see all dropping notifications)

OR

- Libsinsp has a bug that skips the event when is not able to fetch K8s metadata in time.

I guess the first. Let me know if you can try. Anyway, whatever the case, I think we have to address this issue.

/cc @jasondellaluce 
/cc @FedeDP 
/cc @Andreagit97

**Comment by FedeDP** [comment]
Yep, i agree with Leo: i'd try with threshold: 0 to see if the event is actually dropped.
Otherwise, we might have a bug in sinsp!

**Comment by cpungasc** [comment]
I tried with the following setup/changes. I have enabled back `-k`/`-K` and set the `syscall_event_drops.threshold` value to `0` (as you can observe lower).
```
root@gke-k8s-runtime-dev--{redacted}:# grep -i -A 5 -B 5 "threshold" falco.yaml
# token bucket. The rate corresponds to one message every 30 seconds
# with a burst of one message (by default).
#
# The messages are emitted when the percentage of dropped system calls
# with respect the number of events in the last second
# is greater than the given threshold (a double in the range [0, 1]).
#
# For debugging/testing it is possible to simulate the drops using
# the `simulate_drops: true`. In this case the threshold does not apply.

syscall_event_drops:
  threshold: 0
  actions:
    - log
    - alert
  rate: .03333
  max_burst: 10
```

I left the cluster to run for more than 15 minutes (with _CronJobs_ executing every 3 minutes). The last log events from _falco_ remained:
```
> kubectl logs -f pods/falco-monitoring -c falco

* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o
Wed May 25 12:11:06 2022: Falco version 0.31.1-{redacted}
Wed May 25 12:11:06 2022: Falco initialized with configuration file /falco.yaml
Wed May 25 12:11:06 2022: Loading rules from file /rules/falco_rules.yaml:
```

Please let me know if I should look somewhere else or apply any other changes. Thank you!
