### ISSUE TITLE
Ability to add custom fields to Falco - like K8S cluster name

### ISSUE THREAD

**Issue by IliaGe** [falcosecurity/falco#2016]
**Motivation**

When running in a multi cluster environment, we want to use a single falco-sidekick with many falco daemonSets from different clusters reporting to the same sidekick.

**Feature**

I would like to add a custom-field to the falco daemonSet, like "cluster.name=XXX" so that each event onthe sidekick will hold this info

**Comment by jasondellaluce** [comment]
I think you can accomplish this by using the `-p` flag of Falco.

This flag allows you to append a string to every alert output arising from a certain Falco instance. So for example `falco -p " cluster.name=staging"` would append ` cluster.name=staging` to the output of all alerts.

If you are deploying Falco with the community Helm charts, you should be able to pass additional CLI parameters to each Falco  with the `extraArgs` configuration option (see https://github.com/falcosecurity/charts/tree/master/falco#configuration).

If I correctly understood your use case, this may be a feasible workaround. Let me know if that works for you.

**Comment by maksim-paskal** [comment]
This can be made with additional configuration in Helm Chart https://github.com/falcosecurity/charts/tree/master/falco#configuration

```yaml
falco:
  jsonOutput: true
  programOutput:
    enabled: true
    program: "jq '.output_fields.cluster.name = \"staging\"' | curl -d @- -XPOST http://public-endpoint-to-falcosidekick"
```

but this a hotfix - I think we need some falco options to transfer some additional information like cluster name, pod name or host to falcosidekick for clear understanding where this event was happens

@jasondellaluce `-p` flag in falco doesn't effect on output fields with `http_output`

**Comment by IliaGe** [comment]
Hey @maksim-paskal, I have added the config you have suggested, but I see on sidekick the "cluster" with a value of "[ object Object]" :0

**Comment by maksim-paskal** [comment]
@IliaGe thanks. Update my comment - just make string escape from 
```
jq '.output_fields.cluster.name
```
to
```
jq '.output_fields.\"cluster.name\"
```

**Comment by rubensf** [comment]
@maksim-paskal if I understand correctly, your hotfix will end up with duplicate info sent to the sidekick?

I'm struggling with figuring out how to turn on the sidekick without enabling `http_output` straight to it through the Helm charts

**Comment by maksim-paskal** [comment]
Hi @rubensf - sorry but I don't understand your question.

We are using multiple clusters, with multiple providers. One of this cluster has `falcosidekick` installed with helm
```bash
helm install falcosidekick falcosecurity/falcosidekick --values falcosidekick.yaml
```

```yaml
#falcosidekick.yaml
...
service:
  type: LoadBalancer
  port: 12345
...
```

all others cluster has `falco` installed with
```bash
helm upgrade falco falcosecurity/falco --values falco.yaml
```

```yaml
#falco.yaml
...
falco:
  jsonOutput: true
  programOutput:
    enabled: true
    program: "jq '.output_fields.\"cluster.name\" = \"somecluster\"' | curl -d @- -XPOST http://<falcosidekick-endpoint>:12345"
...
```

`falcosidekick` now has all falco events from all our clusters
