### ISSUE TITLE
Access to more variables in output_fields

### ISSUE THREAD

**Issue by wdoekes** [falcosecurity/falco#2127]
**Motivation**

Right now, we're parsing the `jsonOutput: true` json generated by falco and feeding it to Slack.

Instead of using the unformatted `"output"`, we use the `"output_fields"`. This way, we can do something like this.

We take this json:
```json
{
  "output": "14:33:48.105952346: Error File below / or /root opened for writing (user=root user_loginuid=-1 command=touch /wjd-test parent=runc:[1:CHILD] file=/wjd-test program=touch container_id=c0a8e388a8c2 image=falcosecurity/falco) k8s.ns=kube-falco k8s.pod=falco-zjsqj container=c0a8e388a8c2",
  "priority": "Error",
  "rule": "Write below root",
  "source": "syscall",
  "tags": [
    "filesystem",
    "mitre_persistence"
  ],
  "time": "2022-07-12T12:33:48.105952346Z",
  "output_fields": {
    "container.id": "c0a8e388a8c2",
    "container.image.repository": "falcosecurity/falco",
    "evt.time": 1657629228105952300,
    "fd.name": "/wjd-test",
    "k8s.ns.name": "kube-falco",
    "k8s.pod.name": "falco-zjsqj",
    "proc.cmdline": "touch /wjd-test",
    "proc.name": "touch",
    "proc.pname": "runc:[1:CHILD]",
    "user.loginuid": -1,
    "user.name": "root"
  }
}
```
And we turn it into this:

![image](https://user-images.githubusercontent.com/1225014/178490776-886bbf90-662f-45f1-9117-91a4ce1868c9.png)

We can create that nicely formatted message because all fields are separately accessible.
```yaml
output: "File below / or /root opened for writing (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline parent=%proc.pname file=%fd.name program=%proc.name container_id=%container.id image=%container.image.repository)"
```
All `%`-fields mentioned in the `output` are available in `output_fields`, as seen above.

*But, we do not have access to -- for instance -- `proc.aname[2]`.*

The easy solution sounds like amending the `output:` in the default rules. But alas, this does not work.
```yaml
    - rule: Write below root
      output: "File below / or /root opened for writing (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline parent=%proc.pname file=%fd.name program=%proc.name container_id=%container.id image=%container.image.repository)"
      append: true
      condition: >
        and not (expected_write_below_root_behaviour)
```
The `condition`s are amended, but the `output` is **not** amended/overwritten: so I cannot get more values in the `output_fields` without copying the entire `Write below root` rule to something _new_.

**Feature**

I'd like to be able to get more values in the `output_fields`.

- This could be by overwriting the rule name and adding them in the `output`,
- or by setting a separate `also_add_these_variables_in_output_fields: [proc.aname[2], ...]` on the rule,
- or through some other means.

Cheers,
Walter Doekes
OSSO B.V.

**Comment by robinlandstrom** [comment]
I just noticed the same thing. Parsing output fields from k8s_audit alerts and wanted to add the source ip of the request to all alerts.

``` yaml
- rule: Attach/Exec Pod
  append: true
  output: src_ip=%json.value[sourceIPs/0]

- rule: K8s Namespace Deleted
  append: true
  output: src_ip=%json.value[sourceIPs/0]
...
```

Falco 0.32.2 fails to load it because it does not contain an `exception` or `condition` property

```
Error: Could not load rules file /etc/falco/rules.d/k8s_audit_rules.z.local.yaml: 1 errors:
Appended rule must have exceptions or condition property
---
- rule: Attach/Exec Pod
  append: true
  output: src_ip=%json.value[sourceIPs/0]
---
```

Would be great to see support for appending to output or even just adding extra fields to output_fields in 0.33.0 😃
