### ISSUE TITLE
Falco starts but nothing happens

### ISSUE THREAD

**Issue by Diliz** [falcosecurity/falco#2172]
**Describe the bug**

I managed to run falco on openshift (not so easy if you try to push it with a least privileged argo instance xD), the problem is it seems stuck at launch, maybe I failed something somewhere, but I got no real state of what's going wrong there :/

**How to reproduce it**

Installed latest falco on openshift with the latest falco helm chart, here the falco values:
```yaml

falco:

  image:
    pullPolicy: *pullPolicy
    pullSecrets: []
    registry: *registry
    repository: falcosecurity/falco
    tag: 0.32.2-slim # tried non slim version as well

  driver:
    enabled: true
    kind: "module"
    loader:
      enabled: true
      initContainer:
        enabled: true
        image:
          pullPolicy: *pullPolicy
          registry: *registry
          repository: falcosecurity/falco-driver-loader
          tag: 0.32.2
        args:
          - "--compile"

  auditLog:
    enabled: true

  falco:
    load_plugins: [json, k8saudit]
    watch_config_files: true
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/k8s_audit_rules.yaml
    json_output: true
    log_level: debug
    priority: debug

    stdout_output:
      enabled: true

  http_output: # enable for sidekick
    enabled: true

  scc: # true here enabled creation of Security Context Constraints in Openshift
    create: false #manually created for testing purpose (can't give the rights to argo for this)

  serviceAccount:
    create: true
```

And here the falco output:
```
Fri Aug 19 14:48:01 2022: Falco version 0.32.2
Fri Aug 19 14:48:01 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Aug 19 14:48:01 2022: Loading plugin (k8saudit) from file /usr/share/falco/plugins/libk8saudit.so
Fri Aug 19 14:48:01 2022: Loading plugin (json) from file /usr/share/falco/plugins/libjson.so
Fri Aug 19 14:48:01 2022: Configured rules filenames:
Fri Aug 19 14:48:01 2022: /etc/falco/falco_rules.yaml
Fri Aug 19 14:48:01 2022: /etc/falco/falco_rules.local.yaml
Fri Aug 19 14:48:01 2022: /etc/falco/k8s_audit_rules.yaml
Fri Aug 19 14:48:01 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Fri Aug 19 14:48:02 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Fri Aug 19 14:48:02 2022: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco.yaml
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco_rules.yaml.
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco_rules.local.yaml.
Fri Aug 19 14:48:02 2022: Watching /etc/falco/k8s_audit_rules.yaml.
Fri Aug 19 14:48:02 2022: Starting internal webserver, listening on port 8765
```

Then nothing more :/

**Expected behaviour**

Events logged by falco

**Environment**

- Falco version:
0.32.2
- System info:
rhcos 4.18.x
- Cloud provider or hardware configuration:
- OS:
rhcos
- Kernel:
4.18.x
- Installation method:
helm chart + argo

**Additional context**

Openshift cluster:
- The security context constraints was manually added for testing purpose
- Machine config with kernel-devel added for kernel module building purpose

**Comment by alacuku** [comment]
Hi @Diliz, 
since `falco 0.32.0` the kubernetes audit events support has been refactored to become a plugin. One thing that changed is that syscalls and k8s audit events sources cannot be active at the same time anymore. I think this is the issue why you are not seeing the syscalls events in the falco output since falco loads the k8s audit plugin. At the time being you need to run two different falco instances: one for the syscalls and the other one for the k8s audit events.

**Comment by jasondellaluce** [comment]
Agree with @alacuku. We expect to restore running both in the same Falco instance in the near future.

**Comment by Diliz** [comment]
Hello! 

Thanks for the replies!

I actually tried to stop split my falco deployment in 2, one for syscalls and one for k8s audit events, but still no events detected, nothing happens, I dunno what's wrong here, got no errors nor clues about what's going on there

**Comment by jasondellaluce** [comment]
Your k8saudit-only setup seems to be working fine, you've only issue with the syscall-only one. That seems fine to me as well, but you need to prevent it from loading the `/etc/falco/k8s_audit_rules.yaml` ruleset. The error codes are indicating that the `/etc/falco/k8s_audit_rules.yaml` ruleset requires the json plugin and it is not loaded (because you don't need it). This should solve your issue.

**Comment by Diliz** [comment]
Hello,

It's stuck there for the k8s only one, even with the falco event generator (which is in loop mode) + manually triggerred events that should be monitored by falco :/

Weird for the json plugin, I'll check it tomorrow, but I'm pretty sure I added it before retrying it.

Thanks for the support 👍

**Comment by BicycleWalrus** [comment]
Wanted to bump this issue. I also am having issues with getting the k8s-audit plugin up and working. The examples shown in the post from @alacuku has some good documentation for kOps, but not much else. 

I had Falco running for syscalls just fine. Beautifully even. But when I attempt to convert it to k8s-audit, when I attempt restarting my api server with the appropriate webhook configured, the API Server never comes up. I'm assuming this may be an authentication issue, but when attempting to pass falco and approved key and cert I generated just for it, it still doesn't work.

It would seem to me that a change of this magnitude some come with some documentation along with it. I've met quite a few organizations which have also struggled with this change since v0.32.0.

**Comment by alacuku** [comment]
Hi @BicycleWalrus, sorry to hear you are struggling to set up Flaco with k8s audit enabled.

It seems that the `api-server` is not able to reach the Falco instance. In the webhook configuration:

```
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://172.16.3.229:8765/k8s-audit # IP Address is the Service ClusterIP
  name: falco
contexts:
- context:
    cluster: falco
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
```
the `ClusterIP` is used to contact the Falco instance. Have you checked that the `api-server` is able to reach the falco instance using that address? Furthermore, it seems that the port  `8765 configured in the webhook` is different from the default one of the falco configured by the chart `9765`. Please be sure that the port and cluster ip address configured in the webhook match the ones configured for falco. 

If for some reason the `api-server` is not able to reach falco over the `ClusterIP` you can use the following server address: `http://localhost:30007/k8s-audit`. If you are asking why that address the answer is clear if you check how we configured the `values.yaml` file of the helm chart:
```
driver:
  enabled: false

collectors:
  enabled: false

controller:
  kind: deployment

services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765 # See plugin open_params
        nodePort: 30007
        protocol: TCP

falco:
  rulesFile:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        ""
        # maxEventBytes: 1048576
        # sslCertificate: /etc/falco/falco.pem
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  load_plugins: [k8saudit, json]
```

It configures a service of type `NodePort` for falco reachable at the nodePort `30007`. If the nodePort 30007 is not available in your cluster then change it and remember to set the new values in the server address in the webhook configuration.

**Comment by leogr** [comment]
> 2. The documentation with appropriate guidance to get it working is not available, thus rendering the product 'unavailable'.

This is likely the real issue and I apologize for that.

> I'm honestly mystified about this change. Falco was a very stable product, but ... it seems v0.32.0 broke it.

Plugins introduced new challenges and we had to change some assumptions in the Falco architecture. Anyway, I'm pretty sure the real issue is that we lack proper documentation.

@BicycleWalrus if you have any feedback on how we can improve that please share. For example, would a blog post have helped in such a case? 

cc @falcosecurity/falco-maintainers

**Comment by leogr** [comment]
@BicycleWalrus thanks for your feedback.

I think the problem is in the documentation because I'm confident the k8saudit plugin works. The helm chart setup should work too, but perhaps some issue is hidden in the configuration, and we are not seeing it. AFAIK, also CKS is not up-to-date with the latest Falco version.

Anyhow, let's try to solve this issue. I want to help. Before debugging it, I want to add a bit of context and what changed with 0.32. Hoping that can clarify and also help to find a solution.

## Before and after Falco 0.32

|  | Falco 0.31.1 | Falco 0.32.2 |
|-|-|-|
| Required chart ver | v1.18.6 |  v2.0.17 |
| Container image | `falcosecurity/falco` | `falcosecurity/falco-no-driver` |
| Chart AuditSink support | yes, used by defult | no |
| Multi-source (syscalls + k8saudit) | yes | no |
| Deploy kind | DaemonSet | Deployment | 
| K8s audit support | built-in | [plugin](https://github.com/falcosecurity/plugins/tree/master/plugins/k8saudit) |
| K8s audit enabled by default | yes | no (`k8saudit` plugin must be configured) |
| Listening ports (default) | 8765 (for both k8saudit and healthz endpoint) | 9765 (for the k8saudit) / 8765 (only for healthz endpoint)
| Service kind (default) | ClusterIP | NodePort |

Important notes:
 - Configuration settings to enable k8s audit are completely different between 0.31 and 0.32
 - Old blog posts and previous documentation won't work with Falco 0.32
 
## Webhook configuration caveats

### **kube-apiserver** `--audit-policy-file` 
If the flag is omitted, no events are logged. (see https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#audit-policy).
This is a common mistake since this configuration was not required for the dynamic webhook (AuditSink), IIRC. It's mandatory now. It's particularly important because, depending on the policy file content, you may or not receive some kind of audit event.

### **kube-apiserver** `--audit-webhook-config-file` 

The webhook config file should be:

```yaml=
apiVersion: v1
kind: Config
clusters:
  - name: # name of your cluster here
    cluster:
      server: # webhook URL, see below
contexts:
  - context:
      cluster: # name of your cluster here
      user: ""
    name: default-context
current-context: default-context
preferences: {}
users: []
```

Now, assuming no SSL (so `http://`) and a NodePort configured in this way:

```yaml=
    type: NodePort
    ports:
      - port: 9765 # This must match the plugin open_params value
        nodePort: 30007
        protocol: TCP
```

There're two alternatives for `server:`:

1. Using the ClusterIP: `http://<ClusterIP>:9765/k8s-audit`
 This is the common configuration. One caveat is that the ClusterIP is not known before starting the kube-apiserver. So one has to start the kube-apiserver, get the ClusterIP, then modify the audit webhook confing file and restart the kube-apiserver. Also, DNS can't be used.

2. Using the local port: `http://localhost:30007/k8s-audit`
 This has the advantage that the URL is known before starting the kube-apiserver. Since the nodePort will be available on all nodes, it will be available also in the kube-apiserver's node. So one can use `localhost` or the node IP (using the node IP may be mandatory depending on the K8s configuration).
 
Using NodePort is preferable for the simplicity of the configuration.

## Troubleshooting

### Is the Falco webhook listening?

Yes, if the Falco start-up log include:
`Loading plugin (k8saudit) from file /usr/share/falco/plugins/libk8saudit.so`

### Is the Falco webhook reachable?

Try curl `http://<ClusterIP>:9765/k8s-audit`.

If you make a GET request, it will reply with `GET method not allowed`.


### Is the API server sending events?

Check the `kube-apiserver` logs, for example:

```
k --namespace kube-system logs -f kube-apiserver-kind-control-plane
```

Audit Log messages and errors should be reported.

### Falco output may be buffered

In such case, events may appear only after a while.

Try [`tty: true`](https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L122).

## Repro

If all tips above have not worked, we need a repro. In particular, we need:
- Exact version of the Falco Helm chart
- Helm values used (please use `helm get values falco`)
- Contents of the policy file and the webhook config file
- Kubernetes version

And any other details (i.e., any customization) you believe can be relevant.

If you can't publicly share some info, you can contact me via DM on Kubernetes Slack (if that works for you).
