### ISSUE TITLE
Add new rule that detect retrieving environment variables from /proc files

### ISSUE THREAD

**Issue by hi120ki** [falcosecurity/falco#2192]
These days, it's common to pass a secret to an application running on a container via an environment variable. Secrets store very sensitive information such as cloud credentials and JWT secretkeys, so it is important to detect when environment variables have been retrieved by an attack.

And if the application has SSRF or path traversal vulnerabilities, the attacker can steal the environment variables of the application process by reading `/proc/self/environ` and `/proc/1/environ` under the `/proc` directory.

<https://linux.die.net/man/5/proc>

For example, SSRF:

```
curl -X POST -d "url=file:///proc/self/environ" https://example.com/ssrf
curl -X POST -d "url=file:///proc/1/environ" https://example.com/ssrf
```

Path traversal:

```
curl --path-as-is https://example.com/path/../../proc/self/environ
curl --path-as-is https://example.com/path/../../proc/1/environ
```

In MITRE ATT&CK, this technique is categorised as [T1552 : Unsecured Credentials](https://attack.mitre.org/techniques/T1552/), and Sub-technique [T1552.001 : Unsecured Credentials: Credentials In Files](https://attack.mitre.org/techniques/T1552/001/), and Detection is [DS0022 - File - File Access](https://attack.mitre.org/datasources/DS0022/), and component is [T1003.007 OS Credential Dumping: Proc Filesystem](https://attack.mitre.org/techniques/T1003/007/).

I propose the following as a rule to detect environment variable reading from files under the `/proc` directory.

```yaml
- list: proc_environ_file_names
  items: [/proc/self/environ, /proc/1/environ]

- macro: proc_environ_files
  condition: >
    fd.name in (proc_environ_file_names)

- rule: Read environment variable from /proc files
  desc: An attempt to read process environment variables from /proc files
  condition: >
    container and open_read and proc_environ_files
  enabled: true
  output: >
    Environment variables were retrieved from /proc files (user=%user.name user_loginuid=%user.loginuid program=%proc.name
    command=%proc.cmdline file=%fd.name parent=%proc.pname gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)
  priority: WARNING
  tags: [filesystem, mitre_credential_access, mitre_discovery]
```

> Adding a host to the detection target causes false positives by `systemd`, so limited to container.

I'm waiting for your comments on detecting reading these files and my proposed rules.

I would appreciate it if I could create a Pull Request about this rule.

Thank you.
