### ISSUE TITLE
Enabling default rules

### ISSUE THREAD

**Issue by Diliz** [falcosecurity/falco#2314]
**Describe the bug**

As told in the documentation: https://falco.org/docs/rules/#via-custom-rule-definition
I should be able to enable a default rule with a custom rule definition

Rules already present:
```yaml
- rule: Disallowed SSH Connection
  desc: Detect any new ssh connection to a host other than those in an allowed group of hosts
  condition: (inbound_outbound) and ssh_port and not allowed_ssh_hosts
  enabled: false
  output: Disallowed SSH Connection (command=%proc.cmdline pid=%proc.pid connection=%fd.name user=%user.name user_loginuid=%user.loginuid container_id=%container.id image=%container.image.repository)
  priority: NOTICE
  tags: [network, mitre_remote_service]
```

My custom rule:
```yaml
- rule: Disallowed SSH Connection
  append: true
  enabled: true
```
With the append, got the following error:
```
Error: /etc/falco/rules.d/falco_rules.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/falco_rules.yaml:0:0)
rule 'Disallowed SSH Connection': (/etc/falco/rules.d/falco_rules.yaml:48:2)
------
- rule: Disallowed SSH Connection
^
------
LOAD_ERR_VALIDATE (Error validating rule/macro/list/exception objects): Appended rule must have exceptions or condition property
```

Without the append:
```
Error: /etc/falco/rules.d/falco_rules.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/falco_rules.yaml:0:0)
rule 'Read ssh information': (/etc/falco/rules.d/falco_rules.yaml:50:2)
------
- rule: Read ssh information
^
------
LOAD_ERR_VALIDATE (Error validating rule/macro/list/exception objects): Appended rule must have exceptions or condition property
```

**How to reproduce it**

In a custom-rules.yaml file as stated in the documentation, just enable a disabled rule.

**Expected behaviour**

The rule should be enabled

**Screenshots**

**Environment**

- Falco version:
0.33.1

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

Openshift
**Additional context**

It's a pure falco error, no more context needed I think.
