### ISSUE TITLE
version 0.33.1, chart 2.4.3 EKS: k8saudit-eks plugin does not load

### ISSUE THREAD

**Issue by rtalipov** [falcosecurity/falco#2341]
**Describe the bug**

I have successfully deployed falco for syscall events on EKS and wanted to enable support for EKS audit events in the same deployment. However it does not work because k8saudit-eks and json plugins do not load. I followed the documentation https://falco.org/blog/k8saudit-eks-plugin/

**How to reproduce it**

Here are the configuration of the initial deployement:
```
falco:
  plugins:
    - name: k8saudit-eks
      library_path: libk8saudit-eks.so
      init_config:
        shift: 10
        polling_interval: 10
        use_async: false
        buffer_size: 500
      open_params: "sandbox-1"
    - name: json
      library_path: libjson.so
      init_config: ""

  load_plugins: [json, k8saudit-eks]

  falcosidekick:
    config:
      customfields: "environment:sandbox,source:falco"
      datadog: 
        apikey: ""
        minimumpriority: warning
        host: "https://api.datadoghq.com"
    enabled: true
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    webui:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  http_output:
    enabled: true
    url: "http://falcosidekick:2801/"
  image:
    tag: "0.33.1"
  json_output: true
  json_include_output_property: true
  log_level: debug
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  tty: true

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/FalcoAuditEKS
    create: true
    name: falco-audit-eks
  customRules:
    syscall_custom_rules.yaml: |-
```

There are no logs showing that the plugins are loading:
```
k logs -l app.kubernetes.io/name=falco -f                                                                                                                                                                         
Thu Jan  5 13:40:53 2023: Falco version: 0.33.1 (x86_64)
Thu Jan  5 13:40:53 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Thu Jan  5 13:40:53 2023: Loading rules from file /etc/falco/falco_rules.yaml
Thu Jan  5 13:40:54 2023: Loading rules from file /etc/falco/falco_rules.local.yaml
Thu Jan  5 13:40:55 2023: Loading rules from file /etc/falco/rules.d/syscall_custom_rules.yaml
Thu Jan  5 13:40:56 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Thu Jan  5 13:40:56 2023: Starting health webserver with threadiness 4, listening on port 8765
Thu Jan  5 13:40:56 2023: Enabled event sources: syscall
Thu Jan  5 13:40:56 2023: Opening capture with Kernel module
Thu Jan  5 13:40:56 2023: Falco version: 0.33.1 (x86_64)
Thu Jan  5 13:41:04 2023: Falco version: 0.33.1 (x86_64)
Thu Jan  5 13:41:04 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Thu Jan  5 13:41:04 2023: Loading rules from file /etc/falco/falco_rules.yaml
Thu Jan  5 13:41:05 2023: Loading rules from file /etc/falco/falco_rules.local.yaml
Thu Jan  5 13:40:56 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Thu Jan  5 13:40:56 2023: Loading rules from file /etc/falco/falco_rules.yaml
Thu Jan  5 13:40:57 2023: Loading rules from file /etc/falco/falco_rules.local.yaml
Thu Jan  5 13:40:58 2023: Loading rules from file /etc/falco/rules.d/syscall_custom_rules.yaml
Thu Jan  5 13:40:59 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Thu Jan  5 13:40:59 2023: Starting health webserver with threadiness 4, listening on port 8765
Thu Jan  5 13:40:59 2023: Enabled event sources: syscall
Thu Jan  5 13:40:59 2023: Opening capture with Kernel module
Thu Jan  5 13:41:06 2023: Loading rules from file /etc/falco/rules.d/syscall_custom_rules.yaml
Thu Jan  5 13:41:07 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Thu Jan  5 13:41:07 2023: Starting health webserver with threadiness 4, listening on port 8765
Thu Jan  5 13:41:07 2023: Enabled event sources: syscall
Thu Jan  5 13:41:07 2023: Opening capture with Kernel module
```
I tried to install on another cluster following the documentation https://github.com/falcosecurity/charts/tree/master/falco and have the same problem

```
driver:
  enabled: false

collectors:
  enabled: false

controller:
  kind: deployment

falco:
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
    - name: k8saudit-eks
      library_path: libk8saudit-eks.so
      init_config:
        region: "us-east-1"
        profile: "default"
        shift: 10
        polling_interval: 10
        use_async: false
        buffer_size: 500
      open_params: "my-cluster"
    - name: json
      library_path: libjson.so
      init_config: ""

  load_plugins: [k8saudit-eks, json]
```

**Expected behaviour**

Plugins specified under load_plugins should load 

**Screenshots**

**Environment**

- Falco version: 0.33.1

- System info: EKS 1.21/1.22

- Cloud provider or hardware configuration:
- OS: AmazonLinux2

- Kernel: 5.4.226-129.415.amzn2.x86_64

- Installation method: Helm

**Additional context**

**Comment by rtalipov** [comment]
Hi @Issif,

Glad to hear that you're working on loading the plugins.

I the meantime I've created a custom image with `libk8saudit-eks.so` under `/usr/share/falco/plugins`. 
```
# cd /usr/share/falco/plugins
# ls
libcloudtrail.so  libjson.so  libk8saudit-eks.so  libk8saudit.so
```
However the plugins still not loading with the config 
```
  plugins:
    - name: k8saudit-eks
      library_path: libk8saudit-eks.so
      init_config:
        shift: 10
        polling_interval: 10
        use_async: false
        buffer_size: 500
      open_params: "sandbox-1"
    - name: json
      library_path: libjson.so
      init_config: ""
  load_plugins: [json, k8saudit-eks]
```
I've loaded custom rules and the pod is in CrashLoopBackOff with the error `Error: Plugin requirement not satisfied, must load one of: k8saudit (>= 0.1.0), k8saudit-eks (>= 0.1.0)`

**Comment by Issif** [comment]
Have you tried with the absolute path `/usr/share/falco/plugins/k8saudit-eks` ?

Take care, you can't use the k8saudit rules out of the box, you must update them with:

```yaml
- required_engine_version: 15
- required_plugin_versions:
  - name: k8saudit
    version: 0.1.0
    alternatives:
      - name: k8saudit-eks
        version: 0.1.0
```

**Comment by rtalipov** [comment]
I've tried the absolute path and it did not help. I guess I will be waiting for the dynamic loading feature in the future releases.

**Comment by jasondellaluce** [comment]
Looking at the Falco logs, the plugin is not being loaded at all, meaning that the plugin-related configuration does not reach Falco. What version of the our Helm Charts are you running?

cc @alacuku

**Comment by rtalipov** [comment]
I'm using the latest chart version `2.4.3`

**Comment by trallnag** [comment]
@rtalipov, so at the moment we can't use the chart to monitor audit logs from clusters using Amazon EKS?

**Comment by trallnag** [comment]
I will hijack this issue and use this comment to document me trying to get it to work.

---

I download the plugin and built my own image. For now I am using the stable version of the plugin. I get it from here:

- https://download.falco.org/plugins/stable/k8saudit-eks-0.1.0-linux-x86_64.tar.gz

**Comment by piteros83** [comment]
I'm confused with this setup for eks plugin. Where the rules should be placed in the values.yaml or where to point to the  k8s_audit_rules.yaml file? I already set up the plugin itself but when I try to deployed it I got this error:
```sh
falco restart count: 2
falco waiting reason: CrashLoopBackOff
falco termination reason: Error
falco-nt5jz/falco.log
 
Mon Mar 27 15:29:07 2023: Falco version: 0.34.1 (x86_64)
Mon Mar 27 15:29:07 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Mon Mar 27 15:29:07 2023: Loading plugin 'k8saudit-eks' from file /usr/share/falco/plugins/libk8saudit-eks.so
Mon Mar 27 15:29:07 2023: Loading plugin 'json' from file /usr/share/falco/plugins/libjson.so
Error: You must specify at least one rules file/directory via -r or a rules_file entry in falco.yaml
```

configuration files resides in /rulesfiles dir and falco.yaml is empty:
```sh
# ls rulesfiles/
falco.yaml            k8s_audit_rules.yaml
```

**Comment by Issif** [comment]
Here's my whole `values.yaml` I'm using for my demos:

```yaml=
tty: true
kubernetes: false

customRules:
  override-k8saudit.yaml: |-
    - list: allowed_k8s_users
      append: true
      items: [eks:cloud-controller-manager, eks:vpc-resource-controller, eks:az-poller]
    - macro: live_endpoint
      append: true
      condition: or ka.uri="/readyz?exclude=kms-provider-0" or ka.uri="/livez?exclude=kms-provider-0"

falco:
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
    - name: k8saudit-eks
      library_path: libk8saudit-eks.so
      init_config:
        region: "us-east-1"
        # profile: "default"
        shift: 10
        polling_interval: 10
        use_async: false
        buffer_size: 500
      open_params: "falco-demo"
    - name: json
      library_path: libjson.so
      init_config: ""
  load_plugins: [k8saudit-eks, json]
  json_output: true
  json_include_output_property: true
  json_include_tags_property: true
  http_output:
    enabled: true
    url: "http://falco-falcosidekick.falco:2801"

driver:
  enabled: false
collectors:
  enabled: false

controller:
  kind: deployment
  deployment:
    replicas: 1

falcoctl:
  indexes:
  - name: falcosecurity
    url: https://falcosecurity.github.io/falcoctl/index.yaml
  artifact:
    install:
      enabled: true
    follow:
      enabled: true
  config:
    artifact:
      allowedTypes:
        - plugin
        - rulesfile
      install:
        resolveDeps: false
        refs: [k8saudit-rules:0.5, k8saudit-eks:0.1, json:0]
      follow:
        refs: [k8saudit-rules:0.5]
```

I've a different daemonset for falco + falcosidekick + falcosidekick-ui, this is why I set also the `json_*` and `http_output` values.

I think your missing config is :

```yaml=
falco:
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
```

**Comment by piteros83** [comment]
> Here's my whole `values.yaml` I'm using for my demos:
> 
> ```
> tty: true
> kubernetes: false
> 
> customRules:
>   override-k8saudit.yaml: |-
>     - list: allowed_k8s_users
>       append: true
>       items: [eks:cloud-controller-manager, eks:vpc-resource-controller, eks:az-poller]
>     - macro: live_endpoint
>       append: true
>       condition: or ka.uri="/readyz?exclude=kms-provider-0" or ka.uri="/livez?exclude=kms-provider-0"
> 
> falco:
>   rules_file:
>     - /etc/falco/k8s_audit_rules.yaml
>     - /etc/falco/rules.d
>   plugins:
>     - name: k8saudit-eks
>       library_path: libk8saudit-eks.so
>       init_config:
>         region: "us-east-1"
>         # profile: "default"
>         shift: 10
>         polling_interval: 10
>         use_async: false
>         buffer_size: 500
>       open_params: "falco-demo"
>     - name: json
>       library_path: libjson.so
>       init_config: ""
>   load_plugins: [k8saudit-eks, json]
>   json_output: true
>   json_include_output_property: true
>   json_include_tags_property: true
>   http_output:
>     enabled: true
>     url: "http://falco-falcosidekick.falco:2801"
> 
> driver:
>   enabled: false
> collectors:
>   enabled: false
> 
> controller:
>   kind: deployment
>   deployment:
>     replicas: 1
> 
> falcoctl:
>   indexes:
>   - name: falcosecurity
>     url: https://falcosecurity.github.io/falcoctl/index.yaml
>   artifact:
>     install:
>       enabled: true
>     follow:
>       enabled: true
>   config:
>     artifact:
>       allowedTypes:
>         - plugin
>         - rulesfile
>       install:
>         resolveDeps: false
>         refs: [k8saudit-rules:0.5, k8saudit-eks:0.1, json:0]
>       follow:
>         refs: [k8saudit-rules:0.5]
> ```
> 
> I've a different daemonset for falco + falcosidekick + falcosidekick-ui, this is why I set also the `json_*` and `http_output` values.
> 
> I think your missing config is :
> 
> ```
> falco:
>   rules_file:
>     - /etc/falco/k8s_audit_rules.yaml
> ```

@Issif, yes that was the case, now it's working, thanks a lot!

**Comment by piteros83** [comment]
How to check if this plugin works properly? (that it's getting the logs from the cloudwatch eks logs)

**Comment by Issif** [comment]
Here's the minimal policy you need: https://github.com/falcosecurity/plugins/tree/master/plugins/k8saudit-eks#aws-iam-policy-permissions

**Comment by piteros83** [comment]
Thx a lot again. Now I'm looking for tutorial how to write proper Exceptions. I went thru [docs](https://falco.org/docs/rules/exceptions/#exception-syntax-shortcuts) but it's unclear to me from where I should pick value for **name** key from example:
```yaml
 exceptions:
   **- name: proc_writer**
     fields: [proc.name, fd.directory]
     comps: [=, =]
     values:
       - [my-custom-yum, /usr/bin]
       - [my-custom-apt, /usr/local/bin]
```
