### ISSUE TITLE
Falco validation does not catch an exception that is not defined correctly

### ISSUE THREAD

**Issue by ben-m-lucas** [falcosecurity/falco#2354]
**Describe the bug**

If a falco rule is appending an exception and defines the exception with a property of `value`, it passes falco validation even though it is not valid.

**How to reproduce it**
The following test file can be used:
testCase.yaml
```
- rule: Test rule with exception append
  desc: A shell was used as the entrypoint/exec point into a container with an attached terminal.
  condition: >
    evt.type=setuid
  output: >
    Test output
  exceptions:
  - name: image_suffix
    fields: [container.image.repository]
    comps: [endswith]
    values:
    - [test]
  priority: NOTICE
  tags: [container]
  
- rule: Test rule with exception append
  exceptions:
    - name: image_suffix
      value: secure-inline-scan
  append: true
```

Run `falco -V testCase.yaml`

Falco responds that this file is ok.

**Expected behaviour**
An error message should be returned that the rule is not valid.

- Falco version:
Falco version: 0.33.1
Libs version:  0.9.2
Plugin API:    2.0.0
Driver:
  API version:    2.0.0
  Schema version: 2.0.0
  Default driver: 3.0.1+driver

- System info:
Falco version: 0.33.1
Libs version:  0.9.2
Plugin API:    2.0.0
Driver:
  API version:    2.0.0
  Schema version: 2.0.0
  Default driver: 3.0.1+driver

- Cloud provider or hardware configuration:
- OS:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel:
Linux 678de6959a21 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux
- Installation method:
used docker image `falcosecurity/falco;latest`

**Additional context**
