### ISSUE TITLE
falco-k8saudit: Pod getting OOM - Memory leak ?

### ISSUE THREAD

**Issue by Lowaiz** [falcosecurity/falco#2369]
**Describe the bug**

Few days back, I deployed, via the helm chart, falco with the k8saudit plugin, and once the kube-apiserver succeed to send its log to the pod, this one started to consume more and more memory until it hits the limit and get OOM killed.

**How to reproduce it**

Deploy Falco with k8s plugin and plug it as the audit webhook of the Kubernetes cluster

**Expected behaviour**

No leaks

**Screenshots**

![image](https://user-images.githubusercontent.com/43639116/214096268-faffb3c4-827b-42e5-b414-5afe24514739.png)

**Environment**

- Falco version: 0.33.1
- Installation method: Official Helm Chart
- Plugins: k8saudit, json

**Additional context**

Values used:
```
falco:
  selectLabels:
    - app.kubernetes.io/name: falco-audit
    - app.kubernetes.io/instance: falco-audit
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        ""
      open_params: "http://0.0.0.0:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  webserver:
    enabled: false
  http_output:
    enabled: true
    url: URL
  load_plugins: [ k8saudit, json ]
  libs_logger:
      enabled: true
  stdout_output:
      enabled: false
  json_output: true
  priority: error
```

**Comment by FedeDP** [comment]
Whoa this seems a bad bad memleak/bug. Thanks for reporting!
/milestone 0.34.0

**Comment by jasondellaluce** [comment]
Hi @Lowaiz, would you be able to share a log of one of the Falco pods?

**Comment by FedeDP** [comment]
In the meantime, i started falco with `dummy` plugin under valgrind massif tool.
I hope to understand whether the memleak is in the plugin framework or one between json and k8saudit plugins.

**Comment by leogr** [comment]
We can't reproduce this issue. We need more detail, such as the helm chart version and a full log example.
Considering that, and since we are close to releasing Falco 0.34, I propose postponing this to the next milestone (or a hotfix release eventually).

/milestone 0.35.0

**Comment by Lowaiz** [comment]
I guess, it's my bad, but I can't find why:

I was using Chart v2.4.6, and the log wasn't giving any info except spamming "[libs]: Flushing container table", even on debug log level.
So I updated the chart to latest, changing nothing.
But a helm uninstall + reinstall, apparently stopped the leak issue.

I just can't find how a mess up of he Helm Chart install could lead a pod to leak that bad.

**Comment by Lowaiz** [comment]
After letting the pod running for a day, its look like there is a real problem:

![image](https://user-images.githubusercontent.com/43639116/214526870-3b4eaf1b-296b-46a2-a4bb-189167c40042.png)

To be a bit more precise for the config:
```
falco:
  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 2048Mi

  driver:
    enabled: false

  collectors:
    enabled: false

  controller:
    kind: deployment

  image:
    pullPolicy: IfNotPresent
    registry: registry.numberly.in
    repository: docker-images/falco/no-driver
    tag: "0.33.0"

  containerSecurityContext:
    runAsUser: 65534

  services:
    - name: k8saudit-webhook
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 9765 # See plugin open_params
          protocol: TCP

  customRules:
    "falco-k8s-exceptions.yaml": # 2 exceptions on a rules

  falco:
    selectLabels:
      - app.kubernetes.io/name: falco-audit
      - app.kubernetes.io/instance: falco-audit
    rules_file:
      - /etc/falco/k8s_audit_rules.yaml
      - /etc/falco/rules.d
    plugins:
      - name: k8saudit
        library_path: libk8saudit.so
        init_config:
          ""
        open_params: "http://0.0.0.0:9765/k8s-audit"
      - name: json
        library_path: libjson.so
        init_config: ""
    webserver:
      enabled: false
    http_output:
      enabled: true
      url: http://falco-sidekick.numberly.dev
    load_plugins: [ k8saudit, json ]
    libs_logger:
        enabled: true
    stdout_output:
        enabled: false
    json_output: true
    priority: error
```
