### ISSUE TITLE
plugin "k8saudit-eks" No such file or directory. Exiting. issue

### ISSUE THREAD

**Issue by eranp22** [falcosecurity/falco#2395]
Hi,
The new plugin "k8saudit-eks" is not working as expected, causing a "CrashLoopBackOff" error with the message "Runtime error: cannot load plugin /usr/share/falco/plugins/libk8saudit-eks.so: can't load plugin dynamic library: /usr/share/falco/plugins/libk8saudit-eks.so: cannot open shared object file: No such file or directory. Exiting." when trying to get audit logs from EKS.

The steps to reproduce the bug are as follows:

The configuration file is used.
values-falco-syscall-k8saudit.yaml
`driver:
  enabled: false

collectors:
  enabled: false

controller:
  kind: deployment

services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765 # See plugin open_params
        nodePort: 30007
        protocol: TCP

falco:
  rules_file:
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  plugins:
  - name: k8saudit-eks
    library_path: libk8saudit-eks.so
    init_config:
      region: "<<region>>"
      profile: "default"
      shift: 10
      polling_interval: 10
      use_async: false
      buffer_size: 500
    open_params: "<<cluster>>"
  - name: json
    library_path: libjson.so
    init_config: ""
  load_plugins: [k8saudit-eks, json]`
Run the following command: "sudo helm install --values=values-falco-syscall-k8saudit.yaml --set falcosidekick.enabled=true --set auditLog.enabled=true --namespace falco --create-namespace falco falcosecurity/falco".

Screenshots

![image](https://user-images.githubusercontent.com/106144718/216015245-32fef11b-8664-4528-bcfb-dbce90e3e402.png)

Environment

Falco version: 0.33.1 (x86_64)
Cloud provider or hardware configuration: AWS
Installation method: Helm

I attempted to retrieve triggered rules using the "k8saudit" plugin. However, the plugin is not functioning as expected for eks environment, and I have not been able to receive events from the audit logs (such as namespace creation, deletion, etc.).

Thanks,
Eran

**Comment by Issif** [comment]
Hi,

The k8saudit-eks plugin has been released after the last release of Falco (0.33), this is why is not yet included in the Falco image. It will be in the 0.34 that will be out this week and we've also integrated ‘falcoctl’ as a loader for plugins. The doc and a blog post will be written soon to explain this new behavior.

**Comment by eranp22** [comment]
Thank you for your quick response. I understand that the k8saudit-eks plugin was released after the last release of Falco (0.33) and that it will be included in the next release of Falco (0.34).

Could you please provide an estimated date for the release of Falco version 0.34?

Thanks, 
Eran

**Comment by Issif** [comment]
Falco 0.34 will be released before the end of this week.

**Comment by eranp22** [comment]
Cool, Thank you!

**Comment by eranp22** [comment]
Any updates?

**Comment by Issif** [comment]
The release has been postponed a little, you can follow here https://github.com/falcosecurity/falco/releases/tag/0.34.0

**Comment by eranp22** [comment]
Hi,
I saw that the Falco has updated but still I have the same error.
![image](https://user-images.githubusercontent.com/106144718/217526258-b5b8442a-866e-4e2c-8bc8-28762b29c490.png)

**Comment by Issif** [comment]
I was wrong as the behavior changed with 0.34.0.

Let me quote @alacuku from Slack:

---

Hi,

using the latest chart version v0.3.0  arbitrary `artifacts` can be installed thanks to the `falcoctl` tool. Please have a look to the `falcoctl` [docs](https://github.com/falcosecurity/falcoctl#-falcoctl) and to its configuration in the `Falco` [chart](https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/values.yaml#L333-L405).

We did not enable the downloading of `plugins artifacts` by default since they are loaded and executed by `Falco`. We are working on a solution to distribute those artifacts securely by signing them and make sure that what you are downloading comes from a trusted author. If you are interested here you will find more info about the [supply chain security](https://kubernetes.slack.com/archives/CMWH3EH32/p1669826621187329).

Coming back to your problem, you can configure `falcoctl` tool to download the `k8saudit-eks plugin` by:
* First enable `falcoctl` to download `artifacts` of type `plugin` by adding it [here](https://github.com/falcosecurity/charts/blob/4c138561e773cb011bec62b96e943d6d2c22b8b1/falco/values.yaml#L382-L383)
* Add the `plugin artifacts` that you want to install under `falcoctl.config.install.refs`

The following config snippet shows how to install the `plugin`:

```yaml
 falcoctl:
    artifact:
      install:
        # -- Enable the init container. We do not recommend installing plugins for security reasons since they are executable objects.
        # We install only "rulesfiles".
        enabled: true
      follow:
        # -- Enable the sidecar container. We do not support it yet for plugins. It is used only for rules feed such as k8saudit-rules rules.
        enabled: true
    config:
      artifact:
        # -- List of artifact types that falcoctl will handle. If the configured refs resolves to an artifact whose type is not contained
        # in the list it will refuse to downloade and install that artifact.
        allowedTypes:
          - rulesfile
          - plugin
        install:
          # -- Do not resolve the depenencies for artifacts. By default is true, but for our use case we disable it.
          resolveDeps: false
          # -- List of artifacts to be installed by the falcoctl init container.
          # We do not recommend installing (or following) plugins for security reasons since they are executable objects.
          refs: [k8saudit-rules:0.5, k8saudit-eks:0.1, json:0.6]
        follow:
          # -- List of artifacts to be followed by the falcoctl sidecar container.
          # We do not recommend installing (or following) plugins for security reasons since they are executable objects.
          refs: [k8saudit-rules:0.5]
```
When you enable the `plugin` type you need to download each plugin needed by `Falco`. As you can see, we added also the `json  plugin`. Then make sure to configure `Falco` to load the downloaded plugins.
