### ISSUE TITLE
Expections to rules not taken into account

### ISSUE THREAD

**Issue by Blamas** [falcosecurity/falco#2429]
**Describe the bug**

Expections to rules are not taken into account and are still sent to alertmanager.

**How to reproduce it**

Deploy the falco helm chart with those parameters :
```
falco:
  json_output: true
  grpc:
    enabled: true
collectors:
  kubernetes:
    enabled: true
falcosidekick:
  enabled: true
  config:
    alertmanager:
      hostport: http://alertmanager.prometheus.svc.cluster.local:9093
      endpoint: /api/v2/alerts
      expireafter: "3600"
      minimumpriority: warning
customRules:
  exceptions_warning.yaml: |-
    - rule: Launch Package Management Process in Container
      append: true
      exceptions:
        - name: ignore_npm_in_ns_test
          fields: [k8s.ns.name, proc.cmdline, container.image.repository]
          comps: [=, =, =]
          values:
          - [test, npm, custom.registry.io/npm]
```

**Expected behaviour**
The `Launch Package Management Process in Container` warning is ignored in the `test` namespace when the cmdline is `npm`.

**Observed behaviour**
We receive those alerts coming from alertmanager :
```
Labels:
 - container_id = xxxxxxxxx
 - container_image_repository = custom.registry.io/npm
 - container_image_tag = 1.0
 - container_name = npm-test
 - eventsource = syscall
 - evt_time = xxxxxxxxxxxxxx
 - hostname = falco-xxxxx
 - k8s_ns_name = test
 - k8s_pod_name = npm-test-xxxxxxxxx-xxxx
 - priority = Error
 - proc_cmdline = npm                                   
 - proc_pid = xxxxxxx
 - rule = Launch Package Management Process in Container
 - source = falco
 - tags = mitre_persistence,process
 - user_loginuid = -1
 - user_name = <NA>
```

**Environment**

- Falco version:

- System info: docker.io/falcosecurity/falco-no-driver:0.33.1 (x86_64)

- Cloud provider or hardware configuration: Azure AKS
- OS: AKSUbuntu-2204gen2containerd-2023.01.20

- Installation method: Helm

**Additional context**

We have other rules of the same type but this one is the only one to pass our filter.

Thanks,
Blamas.
