### ISSUE TITLE
[Feature Request] Parse event fields on the right hand side of the operator in conditions

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/falco#2496]
**Motivation**

I want to identify containers which are misconfigured and start as a wrong user ID (where the user doesn't exist in the /etc/passwd of the container, or /etc/passwd is missing)

**Feature**

I want to create a rule that can notify me of this. For ex: `user.name == evt.arg.uid`
Right now, no rules in falco's rules repo do that. But there's an issue in falco as noted below.

**Alternatives**

**Additional context**

When testing for this, @terylt suggested to create a rule with condition `evt.num == evt.num` to see if falco fires any events.

I created the following values and applied it:

```yaml
falco:
  customRules:
    02_falco_rules.test.yaml: |-
      ## Add any NEW custom conquest rules/macros (no overrides) here
      ## NOTE: New custom conquest rule overrides (different from new custom conquest rules) go in falco_rules.values.yaml
      - rule: Test whether event fields can be used on both sides of the operator in a condition rule
        desc: >
          The upstream falco rules do not currently contain a rule with an event field on both sides of the operator.
          When asked in the Falco Slack whether this works, nobody knew the answer but this condition was suggested as a test.
        condition: evt.num == evt.num
        output: The test worked (evt.num=%evt.num)
        priority: INFORMATIONAL
        source: syscall
```

The result was falco failing to parse the rules because it took the `evt.num` on the right side of the operator as a literal:

```
In rules content: (/etc/falco/rules.d/02_falco_rules.test.yaml:0:0)
    rule 'Test whether event fields can be used on both sides of the operator in a condition rule': (/etc/falco/rules.d/02_falco_rules.test.yaml:2:2)
    rule condition: (/etc/falco/rules.d/02_falco_rules.test.yaml:6:13)
    condition expression: ("evt.num == evt.num":7:25)
------
evt.num == evt.num
                 ^
------
LOAD_ERR_COMPILE_CONDITION (Error compiling condition): evt.num is not a valid number
```
