### ISSUE TITLE
Add ability to append to lists

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#255]
It'd be good if at the falco rules level you could define a list in a secondary rules file which is automatically appended to a list with a given name in an earlier file, for example:

```
- list: shell_binaries
  items: [bash, csh, ksh, sh, tcsh, zsh, dash]

- list: user_shell_binaries
  append_to: shell_binaries
  items: [xcsh]
```
It also might be desirable to have the new list replace the existing list rather than define a list with a different name, for example:

```
- list: shell_binaries
  append_to: shell_binaries
  items: [xcsh]
```

**Comment by dkerwin** [comment]
I'd prefer the second option

**Comment by argh128** [comment]
For the second option, is the semantics then if "append_to" not present, its a replace? in which case why not make it a boolean with a default false?
`- list: shell_binaries
  append: yes
  items: [xcsh]`

Otherwise the repeating of the name on the append is awkward; and makes the first option a bit more comprehendible as to whats going on.

**Comment by mstemm** [comment]
@argh128 agreed that it'd be nice to have a compact syntax for "append to this list and then replace it". And now that I think about it, there's already an easy way to append to an existing list and give it a new name:

```
- list: user_shell_binaries
  items: [shell_binaries, xcsh]
```

So sounds like the best approach will be that list elements will have an optional `append` boolean, defaulting to false. If true, it appends to a previously found list with the same name (and probably errors if no previously found list exists).

**Comment by mstemm** [comment]
Btw, I added some wiki docs for this feature: https://github.com/draios/falco/wiki/Falco-Rules#appending-to-lists.

**Comment by carestad** [comment]
I am trying to do this now but I keep getting a `Undefined macro kk_acme used in filter.. Exiting.`

I am trying to append to the `write_etc_common` macro in my local.yaml file, like so:

```yaml
 - macro: kk_acme
   condition: >
     user.name=root and
     (proc.name="acme.sh" or
     proc.pname="acme.sh")
 
 # Append to /etc write macro
 - macro: write_etc_common
   append: true
   condition: >
     and not kk_acme
```

Any ideas?

**Comment by carestad** [comment]
However, it seems to work if I put everything from my `kk_acme` macro's condition and use as a condition in the appended `write_etc_common` macro:

```yaml
- macro: write_etc_common
  append: true
  condition: >
    and not (user.name=root and (proc.name="acme.sh" or proc.pname="acme.sh"))
```

But that kind of defeats the purpose of the macros and reusable config code though.
