### ISSUE TITLE
How to obtain the raw syscall sequence for analysis

### ISSUE THREAD

**Issue by zhang-xh95** [falcosecurity/falco#2601]
Excuse me. I'm new to falco. I‘m wondering if  i could directly obtain the raw syscall sequence like sysdig -p? I want to analyze this sequence using Python.

**Comment by Andreagit97** [comment]
ei @zhang-xh95 let's say yes and no. Falco works with rules so you always need to specify some rules, but you could write some rules to emulate the sysdig behavior, for example, something like

```yaml
- rule: Event
  desc: Event
  condition: evt.num >= 0
  output: >
    [type=%evt.type] dir=%evt.dir
  priority: NOTICE
```
