### ISSUE TITLE
Installation Error - Permission Denied and Compilation Failures during Falco eBPF probe Installation on EKS Bottlerocke

### ISSUE THREAD

**Issue by spothound** [falcosecurity/falco#2605]
**Describe the bug**

While installing Falco version 0.34.1 with driver version 4.0.0+driver on Amazon EKS running on a Bottlerocket OS with kernel version 5.15.108, the following error was encountered. The system architecture is x86_64.

During the falco-driver-loader execution, the debugfs mounting process fails with a "permission denied" error. Subsequently, the download of a prebuilt eBPF probe fails with a 404 error as the requested URL returns an error.

Further, an attempt to compile the eBPF probe also fails. The error "fatal error: opening dependency file /host/usr/src/kernels/5.15.108/tools/objtool/.fixdep.o.d: Permission denied" is returned, causing the compilation to terminate.

The series of errors lead to the unsuccessful compilation of the eBPF probe, as indicated by the message "Unable to load the Falco eBPF probe".

These errors prevent the successful installation and setup of Falco on the EKS Bottlerocket environment. A potential cause could be the lack of necessary permissions or the absence of a prebuilt eBPF probe for this specific kernel version and architecture.

```
❯ k logs falco-dftwg  -c falco-driver-loader
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.15.108, kernel version=1
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
mount: /sys/kernel/debug: permission denied.
* Filename 'falco_bottlerocket_5.15.108_1_1.14.1-aws.o' is composed of:
 - driver name: falco
 - target identifier: bottlerocket
 - kernel release: 5.15.108
 - kernel version: 1_1.14.1-aws
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_bottlerocket_5.15.108_1_1.14.1-aws.o
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_bottlerocket_5.15.108_1_1.14.1-aws.o)
fixdep.c:170:1: fatal error: opening dependency file /host/usr/src/kernels/5.15.108/tools/objtool/.fixdep.o.d: Permission denied
 }
 ^
compilation terminated.
make[5]: *** [/host/usr/src/kernels/5.15.108/tools/build/Makefile.build:97: /host/usr/src/kernels/5.15.108/tools/objtool/fixdep.o] Error 1
make[4]: *** [Makefile:47: /host/usr/src/kernels/5.15.108/tools/objtool/fixdep-in.o] Error 2
make[3]: *** [/host/usr/src/kernels/5.15.108/tools/build/Makefile.include:5: fixdep] Error 2
make[2]: *** [Makefile:69: objtool] Error 2
make[1]: *** [Makefile:2023: tools/objtool] Error 2
make: *** [Makefile:38: all] Error 2
mv: cannot stat '/usr/src/falco-4.0.0+driver/bpf/probe.o': No such file or directory
Unable to load the falco eBPF probe
```

**How to reproduce it**

Install Falco using helm, chart version 3.1.5, values:

```
driver:
  enabled: true
  kind: ebpf
  loader:
    securityContext:
      privileged: true
      runAsUser: 0  # Running as root
      runAsGroup: 0 # Running as root group
      allowPrivilegeEscalation: true # Allowing to escalate privileges

podPriorityClassName: falco-agent
collectors: # -- Metadata collectors.
  enabled: true
  containerd:
    enabled: true
    socket: /run/dockershim.sock
  # disabled collectors
  docker:
    enabled: false
  crio:
    enabled: false

podSecurityContext:
  seLinuxOptions:
    user: system_u
    role: system_r

falco:
  json_output: true
  log_level: debug
  ```

**Expected behaviour**

The same installation was working a few days back using noces with [falco_bottlerocket_5.15.108_1_1.14.0-aws.o](https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_bottlerocket_5.15.108_1_1.14.0-aws.o) but since the testing nodes were updated to falco_bottlerocket_5.15.108_1_1.14.1, there is no prebuilt eBPF probe available to download and the installation fails.

Although one possible solution would be to wait/ask for or generate a new version of the prebuilt probe for my nodes, I think it would be interesting to configure/fix this in a way the init container can build the probe themselves if there is no one available for the kernel version.

I wonder why those permission denied appear and how to fix them, any help would be appreciated.

**Environment**

    Falco version:
        Version: 0.34.1
        Driver Version: 4.0.0+driver

    System info:
        Architecture: x86_64
        Kernel Release: 5.15.108
        Kernel Version: 1_1.14.1-aws

    Cloud provider or hardware configuration:
        Cloud Provider: Amazon EKS

    OS:
        Bottlerocket OS

    Kernel:
        Kernel Release: 5.15.108
        Kernel Version: 1_1.14.1-aws

    Installation method:
        Kubernetes
