### ISSUE TITLE
Modern-ebpf lib fails to load in COS(GKE)

### ISSUE THREAD

**Issue by vvsandeepreddy** [falcosecurity/falco#2616]
**Describe the bug**

I am trying to deploy falco-no-driver image with modern-ebpf directly as a daemon set in GKE(cluster/node details below) does not work as expected. It fails to load the BPF module and throws the following error:

```
Tue Jun  6 14:15:44 2023: Falco version: 0.34.1 (x86_64)
Tue Jun  6 14:15:44 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Tue Jun  6 14:15:44 2023: Loading rules from file /etc/falco/falco_rules.yaml
Rules match ignored syscall: warning (ignored-evttype):
Loaded rules match the following events: write, mlock2, fsconfig, send, getsockname, getpeername, setsockopt, recv, sendmmsg, recvmmsg, semop, getrlimit, page_fault, sendfile, fstat, io_uring_enter, getdents64, mlock, pwrite, ppoll, mlockall, io_uring_register, copy_file_range, getegid, fstat64, semget, munlock, signaldeliver, access, stat64, epoll_wait, lseek, poll, munmap, mprotect, getdents, lstat64, pluginevent, getresgid, getresuid, geteuid, getuid, semctl, munlockall, mmap, read, splice, brk, switch, pwritev, getgid, nanosleep, preadv, writev, readv, pread, mmap2, getcwd, select, llseek, lstat, stat, futex
These events might be associated with syscalls undefined on your architecture (please take a look here: https://marcin.juszkiewicz.com.pl/download/tables/syscalls.html). If syscalls are instead defined, you have to run Falco with `-A` to catch these events
Tue Jun  6 14:15:44 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Tue Jun  6 14:15:44 2023: Starting health webserver with threadiness 2, listening on port 8765
Tue Jun  6 14:15:44 2023: Enabled event sources: syscall
Tue Jun  6 14:15:44 2023: Opening capture with modern BPF probe.
Tue Jun  6 14:15:44 2023: One ring buffer every '2' CPUs.
libbpf: prog 't1_execve_x': BPF program load failed: Invalid argument
libbpf: prog 't1_execve_x': -- BEGIN PROG LOAD LOG --
arg#0 type is not a struct
Unrecognized arg#0 type PTR
; int BPF_PROG(t1_execve_x,
0: (79) r7 = *(u64 *)(r1 +8)
1: (79) r6 = *(u64 *)(r1 +0)
func 'sys_exit' arg0 has btf_id 82 type STRUCT 'pt_regs'
; u32 cpu_id = (u32)bpf_get_smp_processor_id();
----
----
----
-- END PROG LOAD LOG --
libbpf: prog 't1_execve_x': failed to load: -22
libbpf: failed to load object 'bpf_probe'
libbpf: failed to load BPF skeleton 'bpf_probe': -22
libpman: failed to load BPF object (errno: 22 | message: Invalid argument)
Tue Jun  6 14:15:44 2023: An error occurred in an event source, forcing termination...
Error: 

```

Node details:

```
architecture: amd64
    containerRuntimeVersion: containerd://1.6.18
    kernelVersion: 5.10.162+
    kubeProxyVersion: v1.24.11-gke.1000
    kubeletVersion: v1.24.11-gke.1000
    machineID: c8e92330b9322a74cf9af25ef1ca7db8
    operatingSystem: linux
    osImage: Container-Optimized OS from Google
```

**How to reproduce it**

Deploy the daemon set using following spec in GKE cluster with COS nodes. 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco-test
  labels:
    app.kubernetes.io/name: falco
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falco
  template:
    metadata:
      name: falco
      labels:
        app.kubernetes.io/name: falco
    spec:
      serviceAccountName: falco
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      containers:
      - args:
        - /usr/bin/falco
        - --cri
        - /run/containerd/containerd.sock
        - --cri
        - /run/crio/crio.sock
        - -K
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        - -k
        - https://$(KUBERNETES_SERVICE_HOST)
        - --k8s-node
        - $(FALCO_K8S_NODE_NAME)
        - -pk
        - --modern-ebpf
        env:
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SKIP_DRIVER_LOADER
        - name: FALCO_BPF_PROBE
        image: docker.io/falcosecurity/falco-no-driver:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8765
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: falco
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8765
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - BPF
            - SYS_RESOURCE
            - PERFMON
            - SYS_PTRACE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.falco
          name: root-falco-fs
        - mountPath: /host/proc
          name: proc-fs
        - mountPath: /sys/kernel/debug
          name: debugfs
        - mountPath: /host/var/run/docker.sock
          name: docker-socket
        - mountPath: /host/run/containerd/containerd.sock
          name: containerd-socket
        - mountPath: /host/run/crio/crio.sock
          name: crio-socket
        - mountPath: /etc/falco
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: falco
      serviceAccountName: falco
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - emptyDir: {}
        name: plugins-install-dir
      - emptyDir: {}
        name: rulesfiles-install-dir
      - emptyDir: {}
        name: root-falco-fs
      - hostPath:
          path: /boot
          type: ""
        name: boot-fs
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /usr
          type: ""
        name: usr-fs
      - hostPath:
          path: /etc
          type: ""
        name: etc-fs
      - hostPath:
          path: /dev
          type: ""
        name: dev-fs
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
      - hostPath:
          path: /sys/kernel/debug
          type: ""
        name: debugfs
      - hostPath:
          path: /run/containerd/containerd.sock
          type: ""
        name: containerd-socket
      - hostPath:
          path: /run/crio/crio.sock
          type: ""
        name: crio-socket
      - hostPath:
          path: /proc
          type: ""
        name: proc-fs
      - configMap:
          defaultMode: 420
          items:
          - key: falcoctl.yaml
            path: falcoctl.yaml
          name: falco-falcoctl
        name: falcoctl-config-volume
      - configMap:
          defaultMode: 420
          items:
          - key: falco.yaml
            path: falco.yaml
          name: falco
        name: falco-yaml
      - configMap:
          defaultMode: 420
          items:
          - key: falco.yaml
            path: falco.yaml
          - key: falco_rules.yaml
            path: falco_rules.yaml
          name: falco
        name: config-volume

```

The above daemon set was pulled from the following repo, use other falco resource specs like configmap, cluster role etc from the same location to replicate the issue. 

https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes/falco/templates

**Expected behaviour**

modern-ebpf should load with out any issues and falco should start running. 

**Environment**

- Falco version:
0.34.1 (x86_64)
- System info:

architecture: amd64
    containerRuntimeVersion: containerd://1.6.18
    kernelVersion: 5.10.162+
    kubeProxyVersion: v1.24.11-gke.1000
    kubeletVersion: v1.24.11-gke.1000
    operatingSystem: linux
    osImage: Container-Optimized OS from Google

- Cloud provider or hardware configuration:
- OS
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=3db1b2d6a249eff0e52d0964503af751941088d3
GOOGLE_CRASH_ID=Lakitu
VERSION=97
VERSION_ID=97
BUILD_ID=16919.235.30
```

- Kernel:
5.10.162+
- Installation method:
Kubernetes yaml, source: https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes/falco/templates

**Additional context**

Tried to build ebpf module, ran in to issues. I read here: https://falco.org/docs/getting-started/running/#modern-ebpf, that I can run modern-ebpf with out building any additional libraries by just using falco-no-driver image. That is what I was trying to do above but run in to issues there. 

I've attached the full output log here for your reference. 
[modern-ebpf.log](https://github.com/falcosecurity/falco/files/11666082/modern-ebpf.log)

**Comment by Andreagit97** [comment]
not sure why it is reporting `Unrecognized arg#0 type PTR` but the real errror seems at the end of the log you posted

```
id=0,off=131072,ks=4,vs=131088,imm=0) R7_w=map_value(id=0,off=131080,ks=4,vs=131088,imm=0) R8_w=map_value(id=0,off=0,ks=4,vs=131088,imm=0) R9_w=ptr_task_struct(id=0,off=0,imm=0) R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmm???? fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=map_value fp-96=ptr_ fp-104=inv fp-112=mmmmmmmm fp-120=ptr_ fp-128=00000000
parent didn't have regs=8 stack=0 marks
last_idx 1632 first_idx 1601
regs=8 stack=0 before 1632: (18) r3 = 0x9e
; READ_TASK_FIELD_INTO(loginuid, task, loginuid.val);
1635: <invalid CO-RE relocation>
failed to resolve CO-RE relocation <byte_off> [53] struct task_struct.loginuid.val (0:123:0 @ offset 2992)
processed 2186 insns (limit 1000000) max_states_per_insn 1 total_states 116 peak_states 116 mark_read 110
-- END PROG LOAD LOG --
libbpf: prog 't1_execve_x': failed to load: -22
libbpf: failed to load object 'bpf_probe'
libbpf: failed to load BPF skeleton 'bpf_probe': -22
libpman: failed to load BPF object (errno: 22 | message: Invalid argument)
Tue Jun  6 14:15:44 2023: An error occurred in an event source, forcing termination...
```

if it is the case we should have already fixed it and Falco 0.35 will be shipped with the fix, at the moment the only thing you could do to help us is to test the `master` image tag of Falco.

So in your `values.yaml` you should put

```
image:
  # -- The image pull policy.
  pullPolicy: IfNotPresent
  # -- The image registry to pull from.
  registry: docker.io
  # -- The image repository to pull from
  repository: falcosecurity/falco-no-driver
  # -- The image tag to pull. Overrides the image tag whose default is the chart appVersion.
  tag: "master" ## <------------------- here
```

**Comment by vvsandeepreddy** [comment]
Thanks @Andreagit97 for looking in to this. I just tried updating the tag from latest to master. I get the following error. I only specified ```--modern-bpf``` in my args, my spec does not have an env var ```FALCO_BPF_PROBE``` set as well, wonder why it throws the following. I pasted the spec below for your reference, let me know if I need to change anything. Thanks!


```
Error: You can not specify more than one of -e, -u (--userspace), -g (--gvisor-config), --modern-bpf, --nodriver, and the FALCO_BPF_PROBE env var
2023-06-06 11:52:15.084 EDT
Error: You can not specify more than one of -e, -u (--userspace), -g (--gvisor-config), --modern-bpf, --nodriver, and the FALCO_BPF_PROBE env var
2023-06-06 11:52:15.403 EDT
Error: You can not specify more than one of -e, -u (--userspace), -g (--gvisor-config), --modern-bpf, --nodriver, and the FALCO_BPF_PROBE env var

```

Args from spec:
```
  - args:
        - /usr/bin/falco
        - --cri
        - /run/containerd/containerd.sock
        - --cri
        - /run/crio/crio.sock
        - -K
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        - -k
        - https://$(KUBERNETES_SERVICE_HOST)
        - --k8s-node
        - $(FALCO_K8S_NODE_NAME)
        - -pk
        - --modern-bpf
        env:
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SKIP_DRIVER_LOADER
        - name: FALCO_BPF_PROBE
        image: docker.io/falcosecurity/falco-no-driver:master
```
