### ISSUE TITLE
Falco is blocked when a large list of domain names is used in a rule

### ISSUE THREAD

**Issue by emilgelman** [falcosecurity/falco#2680]
**Describe the bug**

On startup, Falco appears to completely hang when using a rule that includes a large list of domains as a condition. Throughout this period, it appears as though Falco is entirely frozen, with no validation of other rules occurring and no logging of stats.

**How to reproduce it**

Overwrite the default rule `Outbound Connection to C2 Servers` with the following rule configuration:

```yaml
- rule: Outbound Connection to C2 Servers
  enabled: true

- list: c2_server_fqdn_list
        append: true
        items: 
        <insert a list of domains>
```

**A list of 1000 domains seems to result in a 5 minute hang in my setup.**

<details>
<summary>falco.yaml</summary>

```
base_syscalls:
  custom_set: []
  repair: false
buffered_outputs: false
file_output:
  enabled: true
  filename: ./events.txt
  keep_alive: true
grpc:
  bind_address: unix:///run/falco/falco.sock
  enabled: true
  threadiness: 0
grpc_output:
  enabled: true
http_output:
  ca_bundle: ""
  ca_cert: ""
  ca_path: /etc/ssl/certs
  enabled: false
  insecure: false
  url: ""
  user_agent: falcosecurity/falco
json_include_output_property: true
json_include_tags_property: true
json_output: true
libs_logger:
  enabled: false
  severity: debug
load_plugins: []
log_level: info
log_stderr: true
log_syslog: true
metadata_download:
  chunk_wait_us: 1000
  max_mb: 100
  watch_freq_sec: 1
metrics:
  convert_memory_to_mb: true
  enabled: false
  include_empty_values: false
  interval: 1h
  kernel_event_counters_enabled: true
  libbpf_stats_enabled: true
  output_rule: true
  resource_utilization_enabled: true
modern_bpf:
  cpus_for_each_syscall_buffer: 2
output_timeout: 2000
plugins:
- init_config: null
  library_path: libk8saudit.so
  name: k8saudit
  open_params: http://:9765/k8s-audit
- library_path: libcloudtrail.so
  name: cloudtrail
- init_config: ""
  library_path: libjson.so
  name: json
priority: debug
program_output:
  enabled: false
  keep_alive: false
  program: 'jq ''{text: .output}'' | curl -d @- -X POST https://hooks.slack.com/services/XXX'
rules_file:
- /etc/falco/falco_rules.yaml
- /etc/falco/falco_rules.local.yaml
- /etc/falco/rules.d
stdout_output:
  enabled: true
syscall_buf_size_preset: 4
syscall_drop_failed_exit: false
syscall_event_drops:
  actions:
  - log
  - alert
  max_burst: 1000000000
  rate: 1000000000
  simulate_drops: false
  threshold: 0.1
syscall_event_timeouts:
  max_consecutives: 1000
syslog_output:
  enabled: true
time_format_iso_8601: false
watch_config_files: true
webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  ssl_certificate: /etc/falco/falco.pem
  ssl_enabled: false
  threadiness: 0
```
</details>

**Expected behaviour**

According to [this](https://falco.org/docs/rules/fd-sip-name/), domain name resolution should happen in a background thread and should not affect other rules.

**Environment**

- Falco version:
Falco version: 0.35.1 (x86_64)
- System info:
```
Sun Jul  9 18:51:20 2023: Falco version: 0.35.1 (x86_64)
Sun Jul  9 18:51:20 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Sun Jul  9 18:51:20 2023: Loading rules from file /etc/falco/falco_rules.yaml
Sun Jul  9 18:51:20 2023: Loading rules from file /etc/falco/falco_rules.local.yaml
{
  "machine": "x86_64",
  "nodename": "falco-t75wm",
  "release": "5.15.0-1040-azure",
  "sysname": "Linux",
  "version": "#47-Ubuntu SMP Thu Jun 1 19:38:24 UTC 2023"
}
```

- Installation method:
AKS
