### ISSUE TITLE
Unix Socket Abuse Detection Rules

### ISSUE THREAD

**Issue by louka-jc** [falcosecurity/falco#2940]
Hi,
Thank you for the awesome tooling, support and documentation so far!

Recently, I've been struggling a lot to match a specific type of socket interaction.

Catching "socket interaction" per say can be done through `evt.type=socket` and `fd.sockfamily = unix` or `evt.arg[0] contains AF_UNIX`. 
But filtering on the socket path, I just can't get it working, I tried with everything path related, but it's either not present, not set, or not with the right info...

So here I am, wondering if this is the right kind of event and I miss a field, of if I'm not using the right type of event to catch commands (not based on cmdline) like `docker ps` or `docker exec`), or something else...

Help will be much appreciated, and have a nice day! :rose:

**Comment by louka-jc** [comment]
Adding an exemple here: 

![image](https://github.com/falcosecurity/falco/assets/124785045/2d0f4206-21dd-4045-a49a-d9e7eca3e4c6)

With a rule like

```yaml
- rule: PoC socket unix
  desc: PoC socket unix
  condition: >
    evt.type=socket and (fd.sockfamily = unix)
  output: Infos (evt_type=%evt.type fs.path.name=%fs.path.name fs.path.nameraw=%fs.path.nameraw fs.path.source=%fs.path.source fs.path.sourceraw=%fs.path.sourceraw fs.path.target=%fs.path.target fs.path.targetraw=%fs.path.targetraw evt.info=%evt.info evt.arg.fd=%evt.arg.fd evt.abspath=%evt.abspath evt.is_io=%evt.is_io fs.path.target=%fs.path.target evt.arg.name=%evt.arg.name evt.arg.path=%evt.arg.path socket_info=%evt.args user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty exe_flags=%evt.arg.flags %container.info)
  priority: DEBUG
  tags: [test]
```

Here again, fs-related fiedsfields are not pupolated :(

**Comment by Andreagit97** [comment]
ei @louka-jc looking at your rule:
```yaml
- rule: PoC socket unix
  desc: PoC socket unix
  condition: >
    evt.type=socket and (fd.sockfamily = unix)
  output: Infos (evt_type=%evt.type fs.path.name=%fs.path.name fs.path.nameraw=%fs.path.nameraw fs.path.source=%fs.path.source fs.path.sourceraw=%fs.path.sourceraw fs.path.target=%fs.path.target fs.path.targetraw=%fs.path.targetraw evt.info=%evt.info evt.arg.fd=%evt.arg.fd evt.abspath=%evt.abspath evt.is_io=%evt.is_io fs.path.target=%fs.path.target evt.arg.name=%evt.arg.name evt.arg.path=%evt.arg.path socket_info=%evt.args user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty exe_flags=%evt.arg.flags %container.info)
  priority: DEBUG
  tags: [test]
```
I noticed that you use the `socket` event. Still, unfortunately, when you create a socket using just the `socket` syscall you don't have the info on the UNIX socket path...you need to use another event like `connect` or `bind` for example. You can try to modify your condition in the following way `evt.type=connect and (fd.sockfamily = unix)`

For what concern the output, the right field to see the UNIX socket path is `%fd.name`

**Comment by louka-jc** [comment]
I'll try that soon, but I tried to capture all kind of events and display most (would be nice to have a flag for all?) the info available, without success... But I'll try and keep you posted, thanks for having a look into this! :heart_decoration:

**Comment by louka-jc** [comment]
Right. This works like a charm, thank you a lot, and I'm a moron for loosing so much time on this one.. :clown_face: 

```yaml
- rule: PoC socket unix
  desc: PoC socket unix
  condition: >
    evt.type in (connect,bind) and (fd.sockfamily = unix) and not (fd.name contains "->")
  output: Infos (evt_type=%evt.type fd.name=%fd.name evt.arg.name=%evt.arg.name evt.arg.path=%evt.arg.path socket_info=%evt.args user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty exe_flags=%evt.arg.flags %container.info)
  priority: DEBUG
  tags: [network, k8s, debug]
```

![image](https://github.com/falcosecurity/falco/assets/124785045/2ab931cc-2aa3-4cfe-8a2f-da00cbb36c8d)


I suggest adding one or a few socket examples in the doc, it's a nice thing to monitor and afaik isn't covered much! ^.^
Have a nice day and feel free to close this issue! :sunflower:
