### ISSUE TITLE
Use `proc.exe` and `proc.aexe` Instead of `proc.name` and `proc.aname`

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/falco#2942]
**Motivation**

Hi,

Given that `proc.name` truncates process names, it there any reason that the  **defautl rules** use it instead of `proc.exe`? I noticed the following:

```
# cat falco_rules.yaml | grep -i "proc.name" | wc
     55     712   10852
# cat falco_rules.yaml | grep -i "proc.aname" | wc
     27     291    4690
```

and then you have things like this:

```yaml
- list: deb_binaries
  items: [dpkg, dpkg-preconfigu, dpkg-reconfigur, dpkg-divert, apt, apt-get, aptitude,
    frontend, preinst, add-apt-reposit, apt-auto-remova, apt-key,
    apt-listchanges, unattended-upgr, apt-add-reposit, apt-cache, apt.systemd.dai
    ]
- list: python_package_managers
  items: [pip, pip3, conda]
```

which isn't ideal. Thanks

**Feature**

See above

**Alternatives**

See above

**Additional context**
