### ISSUE TITLE
[BUG] rules validation depends on loading files order

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#2999]
**Describe the bug**

add a new list at the beginning of `falco-incubating_rules.yaml` file.

```yaml
  - list: dev_creation_binaries
    append: true
    items: ["csi-provisioner", "csi-attacher", "csi-resizer"]
```

`dev_creation_binaries` is a list defined in the `falco-incubating_rules.yaml` file, but it is defined after this `append`. Now run Falco with the `falco-incubating_rules.yaml` file loaded.

```bash
sudo ./userspace/falco/falco -c ../falco.yaml -r ../rules/falco-incubating_rules.yaml -o engine.kind=modern_ebpf
```

You should face this error:

```
Tue Jan  9 12:19:36 2024: Falco version: 0.37.0-231+ad964c0 (x86_64)
Tue Jan  9 12:19:36 2024: Falco initialized with configuration file: ../falco.yaml
Tue Jan  9 12:19:36 2024: System info: Linux version 6.2.0-39-generic (buildd@lcy02-amd64-045) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2
Tue Jan  9 12:19:36 2024: Loading rules from file ../rules/falco-incubating_rules.yaml
Error: ../rules/falco-incubating_rules.yaml: Invalid
1 Errors:
In rules content: (../rules/falco-incubating_rules.yaml:0:0)
    list 'dev_creation_binaries': (../rules/falco-incubating_rules.yaml:34:2)
------
- list: dev_creation_binaries
  ^
------
LOAD_ERR_VALIDATE (Error validating rule/macro/list/exception objects): List has 'append' key but no list by that name already exists

1 Warnings:
In rules content: (../rules/falco-incubating_rules.yaml:0:0)
    list 'dev_creation_binaries': (../rules/falco-incubating_rules.yaml:34:2)
------
- list: dev_creation_binaries
  ^
------
LOAD_DEPRECATED_ITEM (Used deprecated item): 'append' key is deprecated. Add an 'append' entry (e.g. 'condition: append') under 'override' instead.
```

Now if you move the `append` after the list definition, all works well!

**Expected behaviour**

The `append` behavior shouldn't depend on where we put it in the file

**NOTE**

The new `override` key seems to resolve the issue so users should have an alternative in Falco 0.37.0 but it is important to track it!

If we replace the append definition seen before, with the new `override` key, all should work out of the box

```yaml
- list: dev_creation_binaries
  items: ["csi-provisioner", "csi-attacher", "csi-resizer"]
  overridde:
    items: append
```
