### ISSUE TITLE
Getting <NA> for k8s.ns.name and k8s.pod.name

### ISSUE THREAD

**Issue by shirongsheng** [falcosecurity/falco#3018]
Falco version 0.35.1 is deployed in daemonset mode on the k8s cluster in version 1.19.10, with - pk as the args. In the output, only k8s. ns. name and k8s. pod. name are<NA>

**Comment by Andreagit97** [comment]
ei! thank you for reporting, could you try Falco 0.36.2?

**Comment by shirongsheng** [comment]
@Andreagit97 I still have the same issue after updating Falco to version 0.36.2

**Comment by incertum** [comment]
Could you share example logs? Is the CRI container runtime socket mounted? Are container.id and container.image also empty? We retrieve these fields from the container runtime socket.

**Comment by incertum** [comment]
We will soon publish a thorough debugging guide, give me 2-3 weeks.

**Comment by shirongsheng** [comment]
@incertum sry,my environment cannot retrieve logs. 
CRI container runtime socket already mounted
container.id and container.image not empty,only k8s.ns.name and k8s.pod.name is <NA>
```
volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
```
