### ISSUE TITLE
Falco pod constantly restarts after upgrading to 0.37.0

### ISSUE THREAD

**Issue by kenlasko** [falcosecurity/falco#3043]
After upgrading Falco to 0.37.0 via Helm chart v4.0, the Falco security pods all are constantly restarting with the following errors:

```
Tue Jan 30 14:24:27 2024: Falco version: 0.37.0 (x86_64)
Tue Jan 30 14:24:27 2024: Falco initialized with configuration file: /etc/falco/falco.yaml
Tue Jan 30 14:24:27 2024: System info: Linux version 6.5.0-14-generic (buildd@lcy02-amd64-110) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2
Tue Jan 30 14:24:27 2024: Loading plugin 'k8saudit' from file /usr/share/falco/plugins/libk8saudit.so
Tue Jan 30 14:24:27 2024: Runtime error: cannot load plugin /usr/share/falco/plugins/libk8saudit.so: can't load plugin dynamic library: /usr/share/falco/plugins/libk8saudit.so: cannot open shared object file: No such file or directory. Exiting.
```

**Environment**
- Falco version: 0.37.0
- Cloud provider or hardware configuration:  Bare-metal K3S
- OS: Ubuntu 22.04.3 LTS
- Kernel: 6.5.0-14-generic
- Installation method: K3S via Helm/ArgoCD

**values.yaml**
```
driver:
  kind: modern-bpf
collectors:
  enabled: true
  docker:
    enabled: false
  crio:
    enabled: false
  containerd:
    enabled: true
    socket: /run/k3s/containerd/containerd.sock
falco:
  load_plugins:
  - k8saudit
```

**Comment by leogr** [comment]
Here's the relevant Helm Chart config :point_down: 

https://github.com/falcosecurity/charts/blob/0274949af664f5b9c7ba5f5d5ea6a54c31447beb/charts/falco/values-syscall-k8saudit.yaml#L21-L36

**Comment by kenlasko** [comment]
Ah, didn't see the breaking changes list. I've updated my values.yaml to include ```collectors.kubernetes.enabled=true``` and removed ```falco.load_plugins```.  Seems to be working OK with that. One last thing though, I saw the warning about deprecating ```append=true``` in custom rules. It seems that I need to replace it with:

```
override:
  condition: append
```
I tried it with one rule:
```
    - rule: Clear Log Activities
      exceptions:
      - name: allowed_to_clear
        fields: [container.name, proc.pname, proc.name] 
        comps: [=,=,=]
        values:
        - [host, k3s-agent, containerd]
        - [host, k3s-server, containerd]
        - [engine-manager, longhorn-instan, tee]
      override:
        condition: append
```

However, this causes the pod to throw an error and not start:
```
Error: /etc/falco/rules.d/custom-rules.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/custom-rules.yaml:0:0)
    rule 'Clear Log Activities': (/etc/falco/rules.d/custom-rules.yaml:47:2)
------
- rule: Clear Log Activities
  ^
------
LOAD_ERR_YAML_VALIDATE (Error validating internal structure of YAML file): An append override for 'condition' was specified but 'condition' is not defined
```

I can't find any docs that show the new format, so I'm flying a bit blind here.
