### ISSUE TITLE
Error: parse error at (falco/templates/_helpers.tpl:406): unclosed action

### ISSUE THREAD

**Issue by jobinmat** [falcosecurity/falco#3130]
I am getting the error while doing helm installation "Error: parse error at (falco/templates/_helpers.tpl:406): unclosed action"

**Comment by Andreagit97** [comment]
it's not clear to me what you are trying to do here, can you please provide the steps to reproduce it?

**Comment by jobinmat** [comment]
`helm install falco falcosecurity/falco \
--create-namespace \
--namespace falco-new2 \
--set driver.kind=modern-ebpf `

**Comment by jobinmat** [comment]
I am trying to install falco in my eks cluster. But failing with above error. I used old versions of helm and it went through, but containers were failing with "unable to load driver error"

**Comment by Andreagit97** [comment]
Using the latest Falco chart:
```
apiVersion: v2
appVersion: 0.37.1
dependencies:
- condition: falcosidekick.enabled
  name: falcosidekick
  repository: https://falcosecurity.github.io/charts
  version: 0.7.11
- condition: collectors.kubernetes.enabled
  name: k8s-metacollector
  repository: https://falcosecurity.github.io/charts
  version: 0.1.*
description: Falco
home: https://falco.org
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: cncf-falco-dev@lists.cncf.io
  name: The Falco Authors
name: falco
sources:
- https://github.com/falcosecurity/falco
version: 4.2.3
```

I tried your command, please note that is `modern_ebpf` and not `modern-ebpf`

```bash
helm install falco falcosecurity/falco --create-namespace --namespace falco-new2 --set driver.kind=modern_ebpf
```

and it works fine!
