### ISSUE TITLE
libk8saudit.so: can't load plugin dynamic library

### ISSUE THREAD

**Issue by myugan** [falcosecurity/falco#3261]
**Describe the bug**

When attempting to enable **libk8saudit** in Falco, the following error occurs: 

```bash
Runtime error: cannot load plugin /usr/share/falco/plugins/libk8saudit.so: can't load plugin dynamic library: /usr/share/falco/plugins/libk8saudit.so: cannot open shared object file: No such file or directory. Exiting.
```

The documentation lacks clarity.

**How to reproduce it**

The cluster is set up using Kubeadm and it uses version 1.29.5.

```
cat > falco-syscall-k8saudit.yaml<<EOF
driver:
  enabled: true
  kind: ebpf

collectors:
  enabled: true

controller:
  kind: daemonset

services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765
        nodePort: 30007
        protocol: TCP

falcoctl:
  artifact:
    install:
      enabled: true
    follow:
      enabled: true
  config:
    artifact:
      allowedTypes:
        - rulesfile
        - plugin
      install:
        resolveDeps: false
        refs: [falco-rules:3, k8saudit-rules:0.5, json:0.6]
      follow:
        refs: [falco-rules:3, k8saudit-rules:0.5, json:0.6]

falco:
  load_plugins: [k8saudit, json]
  jsonOutput: true
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d

tty: true
EOF

helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
helm install falco --values=falco-syscall-k8saudit.yaml falcosecurity/falco --version 4.2.2
```

**Expected behaviour**

Successfully integrated Kubernetes Audit Logs with Falco.

**Screenshots**

<img width="1249" alt="image" src="https://github.com/falcosecurity/falco/assets/20453528/555de3b1-2d93-4d4e-ac97-23c426eac4c3">

**Environment**

- Falco version: 4.2.2

- System info: -

- Cloud provider or hardware configuration:
- OS: Ubuntu

- Kernel: 6.5.0-1020-aws

- Installation method: Helm

**Additional context**
