### ISSUE TITLE
Falco driver loader init container fails to download artifacts behind proxy

### ISSUE THREAD

**Issue by MaciekLeks** [falcosecurity/falco#3339]
**Describe the bug**

The Falco driver loader init container, which uses the `falcosecurity/falco-driver-loader` image, fails to download the required artifacts when running behind a proxy. It seems that the init container does not properly use the provided proxy settings, resulting in an error:

```
{"level":"ERROR","msg":"unable to fetch index \"falcosecurity\" with URL \"https://falcosecurity.github.io/falcoctl/index.yaml\": unable to fetch index: Stream closed EOF for cybersec/falco-zq8dq (falcoctl-artifact-install)
```

**How to reproduce it**

1. Set up a Kubernetes cluster behind a proxy.
2. Configure the proxy settings in the Falco Helm chart values file:

```yaml
initContainers:
  - args:
    - auto
    env:
    - name: https_proxy
      value: http://proxy:3128
    - name: http_proxy  
      value: http://proxy:3128
    - name: no_proxy
      value: localhost,127.0.0.1,.local
    image: docker.io/falcosecurity/falco-driver-loader:0.38.2
```

3. Install Falco using the Helm chart with the configured proxy settings.

**Expected behavior**

The Falco driver loader init container (`falcosecurity/falco-driver-loader`) should respect the provided proxy settings and successfully download the required artifacts.

**Actual behavior**

The `falcosecurity/falco-driver-loader` init container fails to download the artifacts, and there is no traffic observed on the configured proxy, indicating that the init container is not using the proxy settings.

**Environment**

- Falco version: 0.38.2
- Installation method: Helm chart
- Affected image: `falcosecurity/falco-driver-loader:0.38.2`

**Additional context**

It is unclear why the `falcosecurity/falco-driver-loader` init container attempts to download the artifacts in the first place, as this behavior is not documented. Furthermore, the init container does not seem to respect the provided proxy settings, leading to the download failure.
