### ISSUE TITLE
Falco 0.38.2 crashed with 139

### ISSUE THREAD

**Issue by chenliu1993** [falcosecurity/falco#3404]
**Describe the bug**

we are running falco on rhel os both deployed on physical and cloud, while running falco will crashed due to 139. like once per week.

```yaml
Last State:     Terminated
      Reason:       Error
      Exit Code:    139
      Started:      Fri, 15 Nov 2024 08:05:39 +0800
      Finished:     Fri, 15 Nov 2024 10:15:38 +0800
```

**How to reproduce it**

deployed through deamonset, kmod and modern_ebpf are used.  but this is not reproducible on test env, only with nodes where high traffic and high number of contianers. before crash, cpu usage spiked and only on physical servers, evts buffer drop count suddenly increase

**Expected behaviour**

**Screenshots**
this crash should not happen

**Environment**

- Falco version: 0.38.2

- System info: 9.4

- Cloud provider or hardware configuration:
- OS: rhel

- Kernel: Linux master-2 5.14.0-427.22.1.el9_4.x86_64 Mon Jun 10 09:23:36 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

- Installation method: kubernetes 

**Additional context**
