### ISSUE TITLE
delayed logs from stdout_output

### ISSUE THREAD

**Issue by witalisoft** [falcosecurity/falco#3477]
**Describe the bug**

I'm using Falco to analyze data from the EKS Audit Log by pushing matched events to Falcosidekick. Recently, I've noticed that there is a delay
between events received by Falcosidekick and the logged events in Falco itself (stdout). It looks like the `stdout_output` is being buffered, but I cannot find anything related in the config.

```yaml
append_output: []
base_syscalls:
  custom_set: []
  repair: false
buffered_outputs: false
config_files:
- /etc/falco/config.d
falco_libs:
  thread_table_size: 262144
file_output:
  enabled: false
  filename: ./events.txt
  keep_alive: false
grpc:
  bind_address: unix:///run/falco/falco.sock
  enabled: false
  threadiness: 0
grpc_output:
  enabled: false
http_output:
  ca_bundle: ""
  ca_cert: ""
  ca_path: /etc/falco/certs/
  client_cert: /etc/falco/certs/client/client.crt
  client_key: /etc/falco/certs/client/client.key
  compress_uploads: false
  echo: false
  enabled: true
  insecure: false
  keep_alive: false
  mtls: false
  url: http://falco-falcosidekick:2801
  user_agent: falcosecurity/falco
json_include_message_property: false
json_include_output_property: true
json_include_tags_property: true
json_output: true
libs_logger:
  enabled: false
  severity: debug
load_plugins:
- k8saudit-eks
- json
log_level: info
log_stderr: true
log_syslog: true
metrics:
  convert_memory_to_mb: true
  enabled: false
  include_empty_values: false
  interval: 1h
  kernel_event_counters_enabled: true
  kernel_event_counters_per_cpu_enabled: false
  libbpf_stats_enabled: true
  output_rule: true
  resource_utilization_enabled: true
  rules_counters_enabled: true
  state_counters_enabled: true
output_timeout: 2000
outputs_queue:
  capacity: 0
plugins:
- init_config:
    buffer_size: 5000
    polling_interval: 10
    shift: 40
    use_async: false
  library_path: libk8saudit-eks.so
  name: k8saudit-eks
  open_params: production
- init_config: ""
  library_path: libjson.so
  name: json
priority: debug
program_output:
  enabled: false
  keep_alive: false
  program: 'jq ''{text: .output}'' | curl -d @- -X POST https://hooks.slack.com/services/XXX'
rule_matching: first
rules_files:
- /etc/falco/k8s_audit_rules.yaml
- /etc/falco/rules.d
stdout_output:
  enabled: true
syscall_event_drops:
  actions:
  - log
  - alert
  max_burst: 1
  rate: 0.03333
  simulate_drops: false
  threshold: 0.1
syscall_event_timeouts:
  max_consecutives: 1000
syslog_output:
  enabled: true
time_format_iso_8601: false
watch_config_files: true
webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  prometheus_metrics_enabled: false
  ssl_certificate: /etc/falco/falco.pem
  ssl_enabled: false
  threadiness: 0
```

**How to reproduce it**

Use the config and trigger some events.

**Expected behaviour**

Option to disable "buffering" the `stdout_output`

**Environment**

- Falco version: 0.39.2 (x86_64)

- System info: Linux version 5.10.230-223.885.amzn2.x86_64 (mockbuild@ip-10-0-38-89) (gcc10-gcc (GCC) 10.5.0 20230707 (Red Hat 10.5.0-1), GNU ld version 2.35.2-9.amzn2.0.1) #1 SMP Tue Dec 3 14:36:00 UTC 2024

- Cloud provider or hardware configuration: AWS

- OS: Amazon Linux 2

- Kernel: 5.10.230-223.885.amzn2.x86_64

- Installation method: Official Helm Chart
