### ISSUE TITLE
error with k8smeta plugin in version 0.40.  It wasn't a problem with 0.39

### ISSUE THREAD

**Issue by data-dude** [falcosecurity/falco#3512]
I get this error:
Runtime error: error in plugin k8smeta init config: In <root> , Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints:  'hostProc' .. Exiting

I also noticed I had to manually add the plugin config info for 0.40.0 but 0.39 added it for me.

The only difference between 0.39 configuration (working) and 0.40 configuration (not working) is the container_engine section replaced the engine section.

```
falco.yaml

   plugins:
    - init_config: null
      library_path: libk8saudit.so
      name: k8saudit
      open_params: http://:9765/k8s-audit
    - library_path: libcloudtrail.so
      name: cloudtrail
    - init_config: ""
      library_path: libjson.so
      name: json
    - init_config:
        collectorHostname: falco-k8s-metacollector.default.svc
        collectorPort: 45000
        hostProc: /host
        nodeName: ${FALCO_K8S_NODE_NAME}
        verbosity: info
      library_path: libk8smeta.so
      name: k8smeta
```

- Falco version:
0.40.0
- System info:
Kubernetes and Redhat 9.4. Kernel 5.14

**Additional context**
