### ISSUE TITLE
Rule is triggered although an exception/allowlist is present

### ISSUE THREAD

**Issue by movd** [falcosecurity/falco#3560]
**Describe the bug**

On April 29th, we updated our Falco installations to 0.38.1 and 0.40.0. Since then, sometimes rules that have allowlists/exemptions in place get triggered. We installed Falco from the official apt sources and added the sandbox rules. 

We have custom a rule that alerts if a process is not excluded (`and not`) and connects to an internal S3 endpoint.

```yaml
  - list: s3_destination_domains
    items: [s3.example.com]

  - list: s3_destination_ipaddrs
    items: ['"123.123.123.123"']

  - rule: Disallowed S3 Connections from non some_redacted_app binaries
    desc: Detect any new HTTPS connection to the S3 Bucket endpoint from other processes than some_redacted_app itself
    condition: >
      outbound and
      ((fd.sip in (s3_destination_ipaddrs)) or
      (fd.sip.name in (s3_destination_domains)))
      and not (user.name=www-data and (proc.name=apache2 or proc.cmdline startswith "php /var/www/html/src/redacted_a.php"))
      and not (user.name=www-data and (proc.name=apache2 or proc.cmdline startswith "php /var/www/html/src/redacted_b.php"))
    enabled: true
    output: Disallowed S3 Connection (command=%proc.cmdline pid=%proc.pid connection=%fd.name user=%user.name user_loginuid=%user.loginuid container_id=%container.id image=%container.image.repository)
    priority: EMERGENCY
    tags: [network, some_redacted_app, s3]
```

* `s3.example.com` is the redacted hostname of the internal s3 endpoint
* `123.123.123.123` is the redacted IPv4 Adress of the s3 endpoint
* `some_redacted_app` is the redacted application name

The rule uses the `outbound` macro from the sandbox rules. This macro has not changed in the last few releases that i've checked.

The rule gets triggered because of an empty user.name (see screenshot in Screenshot section)

**How to reproduce it**

Reproduction wasn't possible yet. When using e.g. `sudo -u www-data curl s3.example.com` the rule got triggered (like we want to).

**Expected behaviour**

The rule does not get triggered.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8b06e9a3-941a-4e2b-82be-10c6d790d26c)

**Environment**

- Falco version:

```
Thu May 15 11:13:15 2025: Falco version: 0.40.0 (x86_64)
Thu May 15 11:13:15 2025: Falco initialized with configuration files:
Thu May 15 11:13:15 2025:    /etc/falco/config.d/engine-kind-falcoctl.yaml | schema validation: ok
Thu May 15 11:13:15 2025:    /etc/falco/falco.yaml | schema validation: ok
Thu May 15 11:13:15 2025: System info: Linux version 5.15.0-136-generic (buildd@lcy02-amd64-034) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025
{"default_driver_version":"8.0.0+driver","driver_api_version":"8.0.0","driver_schema_version":"3.5.0","engine_version":"46","engine_version_semver":"0.46.0","falco_version":"0.40.0","libs_version":"0.20.0","plugin_api_version":"3.10.0"}
```

- System info:

```
root@redacted_hostname:~# falco --support | jq .system_info
Thu May 15 11:13:36 2025: Falco version: 0.40.0 (x86_64)
Thu May 15 11:13:36 2025: Falco initialized with configuration files:
Thu May 15 11:13:36 2025:    /etc/falco/config.d/engine-kind-falcoctl.yaml | schema validation: ok
Thu May 15 11:13:36 2025:    /etc/falco/falco.yaml | schema validation: ok
Thu May 15 11:13:36 2025: System info: Linux version 5.15.0-136-generic (buildd@lcy02-amd64-034) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025
Thu May 15 11:13:36 2025: Loading rules from:
Thu May 15 11:13:36 2025:    /etc/falco/falco_rules.yaml | schema validation: ok
Thu May 15 11:13:36 2025:    /etc/falco/falco-sandbox_rules.yaml | schema validation: ok
Thu May 15 11:13:37 2025:    /etc/falco/falco_rules.local.yaml | schema validation: ok
{
  "machine": "x86_64",
  "nodename": "redacted_hostname",
  "release": "5.15.0-136-generic",
  "sysname": "Linux",
  "version": "#147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025"
}
```

- Cloud provider or hardware configuration:
- OS:

```
root@redacted_hostname:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- Kernel:

```
root@redacted_hostname:~# uname -a
Linux redacted_hostname 5.15.0-136-generic #147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

- Installation method: apt sources managed by systemd

**Additional context**

Private cloud / on premise setting
