### ISSUE TITLE
feat: ability to record `.scap` files

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#3595]
**Motivation**

When a Falco rule is triggered, users currently lack an easy, automated way to collect runtime evidence for post-mortem analysis or rule fine-tuning.
This makes it harder to understand the context of alerts, especially in noisy or ambiguous detection scenarios.

**Feature**

Introduce a new capture recording feature in Falco to enable the generation of `.scap` files when a rule is triggered. Optionally, the ability to record the whole session.

Key elements:

* **On-trigger recording**: Only events occurring *after* the rule is triggered are captured.
* **Rule-level configuration**:

  * Enable or disable recording per rule.
  * Set a custom capture window per rule (e.g., 30 seconds, 1 minute).
* **Global configuration**:

  * Enable the feature globally
  * Set a default time window for rules that do not specify it
  * Specify whether to record full sessions or only short post-trigger windows.
  * Configure output path for the generated `.scap` files.

Example config `falco.yaml`:

```yaml
recordings:
  enabled: true
  path: /tmp/falco_recordings # must be a dir, filenames will be generated using a timestamp 
  full_session: false # if true, the whole session will be recorded, regardless of specific rules configuration
  rule_default_window: 60 # default value (in seconds) for those rules that do not specify a time window
```

Example rule `falco_rules.yaml`:

```yaml
- rule: Terminal shell in container
  desc: Detects interactive shell in a container
  condition: >
    spawned_process
    and container
    and shell_procs
    and proc.tty != 0
    and container_entrypoint
    and not user_expected_terminal_shell_in_container_conditions
  output: ...
  record: true # if true, a scap file will be recorded when this rule matches
  record_window: 30 # recording time window in seconds
```

**Alternatives**

Use an external program to trigger capture collection (less reliable, less performant, more complex). Falco Talon already does something similar.

**Additional context**

* This would enable the easy replay of real-world attack traces for debugging and improving detection.
* Useful for integration with analysis tools like [Stratoshark](https://github.com/falcosecurity/stratoshark)(https://github.com/falcosecurity/stratoshark).

/milestone 0.42.0

**Comment by EraKin575** [comment]
Hi @leogr , can I work on this one.

**Comment by leogr** [comment]
> Hi @leogr , can I work on this one.
> 


I was thinking of working on this but it is not planned yet.


That said, any help is welcome. 

Have you a plan on how to tackle this yet?
Also, have you familiarity with the code areas involved?

**Comment by leogr** [comment]
Update. While implementing the changes, I refined the naming convention. This piece of docs should be self-expanatory:

```
##################
# Falco captures #
##################

# [Sandbox] `capture`
#
# --- [Description]
#
# Falco captures allow you to record events and their associated data for
# later analysis. This feature is particularly useful for debugging and
# forensics purposes.
#
# Captures operate in two modes:
#
# 1. `rules`: Captures events only when specific rules are triggered.
#    Enable capturing for individual rules by adding `capture: true` to the rule.
#
# 2. `all_rules`: Captures events when any enabled rule is triggered.
#
# When a capture starts, Falco records events from the moment the triggering rule
# fires until the deadline is reached. The deadline is determined by the rule's
# `capture_duration` if specified, otherwise the `default_duration` is used.
# If additional rules trigger during an active capture, the deadline is extended
# accordingly. Once the deadline expires, the capture stops and data is written
# to a file. Subsequent captures create new files with unique names.
#
# Captured data is stored in files with a `.scap` extension, which can be
# analyzed later using:
#   falco -o engine.kind=replay -o replay.capture_file=/path/to/file.scap
#
# --- [Usage]
#
# Enable captures by setting `capture.enabled` to `true`.
#
# Configure `capture.path_prefix` to specify where capture files are stored.
# Falco generates unique filenames based on timestamp and event number for
# proper ordering. For example, with `path_prefix: /tmp/falco`, files are
# named like `/tmp/falco_00000001234567890_00000000000000042.scap`.
#
# Use `capture.mode` to choose between `rules` and `all_rules` modes.
#
# Set `capture.default_duration` to define the default capture duration
# in milliseconds.
#
# --- [Suggestion]
#
# When using `mode: rules`, configure individual rules to enable capture by
# adding `capture: true` and optionally `capture_duration` to specific rules.
# For example:
#
# - rule: Suspicious File Access
#   desc: Detect suspicious file access patterns
#   condition: >
#     open_read and fd.name startswith "/etc/"
#   output: >
#     Suspicious file access (user=%user.name command=%proc.cmdline file=%fd.name)
#   priority: WARNING
#   capture: true
#   capture_duration: 10000  # Capture for 10 seconds when this rule triggers
#
# This configuration will capture events for 10 seconds whenever the
# "Suspicious File Access" rule is triggered, overriding the default duration.

capture:
  enabled: false
  path_prefix: /tmp/falco
  mode: rules # or "all_rules"
  default_duration: 5000 # in milliseconds
```
