### ISSUE TITLE
Custom rules silent default rules

### ISSUE THREAD

**Issue by antonionappi88** [falcosecurity/falco#3604]
**Describe the bug**

Hello,
I have a similar issue to what is described in https://github.com/falcosecurity/falco/issues/2535.
As soon as I try to override the rule `Contact K8S API Server From Container` the other rules are not matched anymore (e.g. exec to a pod). The syntax seems correct (at least Falco is not complaining). When I remove the customization, everything start to work again (exec to container are now logged).
Do you know what could be wrong ? 

```yaml
customRules:
  my-rules.yaml: |-
    - list: kyverno_process_names
      items: ["reports-control", "cleanup-control", "kyverno"]
    - rule: Contact K8S API Server From Container
      # Tried with and without >
      condition: >
                 and not (proc.name="flb-pipeline" and k8s.ns.name="logging")
                 and not (proc.name="haproxy-ingress")
                 and not (proc.name in (kyverno_process_names) and k8s.ns.name="kyverno")
      override:
        condition: append
```

**How to reproduce it**

Installed Falco via community helm chart and added the above piece of YAML to the values.yaml file

**Expected behaviour**

That other rules are triggered.

**Environment**

```bash
System info: Linux version 6.8.4-200.fc39.x86_64 (mockbuild@ea9727ef4ac046558fb6c0e9fa407113) (gcc (GCC) 13.2.1 20240316 (Red Hat 13.2.1-7), GNU ld version 2.40-14.fc39) #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:45:21 UTC 2024
Falco version: 0.41.1
Libs version:  0.21.0
Plugin API:    3.11.0
Engine:        0.50.0
Driver:
  API version:    8.0.0
  Schema version: 3.6.0
  Default driver: 8.1.0+driver
```
