### ISSUE TITLE
container.name shows container.id in Falco 0.41.x

### ISSUE THREAD

**Issue by Xavelyn** [falcosecurity/falco#3631]
**Describe the bug**

Falco version 0.41.2, also tested with 0.41.0, is not correctly extracting the container.name property. Instead of resolving the actual container name, Falco assigns the container.id value to container.name in the alert output.

In previous versions (e.g., 0.40.0), Falco correctly extracted and displayed the container name that triggered the alert.

**How to reproduce it**

- Set up a Kubernetes cluster
- Install Calico as the CNI
- Deploy Falco via Helm (Chart-version: 6.0.1, falco version: 0.41.2)
- Trigger a Falco alert (e.g., open a shell into a container)

**Expected behaviour**

Falco should correctly extract and display the actual container name in the container.name field of the alert, as it did in version 0.40.0. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/fd76ffe4-9c09-43cd-9f64-a308ab76ba67)

**Environment**

- Falco version:
0.41.2
- System info:
{
  "machine": "x86_64",
  "nodename": "falco-zvk79",
  "release": "6.8.0-62-generic",
  "sysname": "Linux",
  "version": "#65-Ubuntu SMP PREEMPT_DYNAMIC Mon May 19 17:15:03 UTC 2025"
}
- OS:
Ubuntu 24.04.2 LTS
- Kernel:
6.8.0-62-generic #65-Ubuntu
- Installation method:
Kubernetes

**Comment by fad3t** [comment]
Ah great, I was about to post an issue about this one :) this was discussed in Slack: https://kubernetes.slack.com/archives/CMWH3EH32/p1751011217918159

I tried switching container engines on and off, but didn't get the expected results:

> containerd ON, crio ON and docker ON: container.name is the container ID
containerd ON, crio ON and docker OFF: container.name is the container ID
containerd ON, crio OFF and docker ON: container.name is "host"
containerd ON, crio OFF and docker OFF: container.name is "host"
containerd OFF, crio ON and docker OFF: container.name is empty
containerd OFF, crio ON and docker ON: container.name is empty

I also tried configuring the crio container engine with the containerd socket path, but it didn't help.

**Comment by Ghamms92** [comment]
We are currently having the same issues with our deployments. We have quite a few rules built out that include the use of container.name so this is breaking our alerting quite severely.

**Comment by wangwillian0** [comment]
same issue: https://github.com/falcosecurity/plugins/issues/850

**Comment by ekoops** [comment]
Hey. Thank you for reporting it. I'm gonna look into that starting from tomorrow and come back to you!

**Comment by leogr** [comment]
Hey @wangwillian0 

> same issue: [falcosecurity/plugins#850](https://github.com/falcosecurity/plugins/issues/850)

This seems to be a different problem, or am I missing something? 🤔

**Comment by ekoops** [comment]
Could you please try to override the container plugin configuration and enabling the `start` hook beside the `create` hook?
You can achieve that with something like:
```YAML
plugins:
  - name: container
    library_path: path-to-libcontainer.so
    init_config:
      hooks: ["create", "start"]
      engines:
        # Provide your engines configuration ...
```
EDIT:
Specifically, I tried it with this engine configuration:
```YAML
     # ...
      engines:
        docker:
          enabled: true
          sockets: [ '/var/run/docker.sock' ]
        podman:
          enabled: false
          sockets: [ '/run/podman/podman.sock', '/run/user/1000/podman/podman.sock' ]
        containerd:
          enabled: false
          sockets: [ '/run/containerd/containerd.sock' ]
        cri:
          enabled: true
          sockets: [ '/run/crio/crio.sock' ]
        lxc:
          enabled: false
        libvirt_lxc:
          enabled: false
        bpm:
          enabled: false
```

EDIT 2:
Enabling containerd seems to bring back the problem. Btw, take into account that containerd doesn't seem to provide any notion of name, and for this reason, in that case, the short ID is provided. This is consistent to the Falco behaviour before the container plugin release.

**Comment by Xavelyn** [comment]
Hi,
thank you for having a look.

As requested i tried it with:
```
falco:
  load_plugins: [container]
  plugins:
    - name: container
      library_path: libcontainer.so
      init_config:
        hooks: ["create", "start"]
        engines:
          docker:
            enabled: true
            sockets: [ '/var/run/docker.sock' ]
          podman:
            enabled: false
            sockets: [ '/run/podman/podman.sock', '/run/user/1000/podman/podman.sock' ]
          containerd:
            enabled: false
            sockets: [ '/run/containerd/containerd.sock' ]
          cri:
            enabled: true
            sockets: [ '/run/crio/crio.sock' ]
          lxc:
            enabled: false
          libvirt_lxc:
            enabled: false
          bpm:
            enabled: false
```

As a result i get no information at all regarding the fields: container_name, container_image_repository, container_image_tag, k8s_pod_name and k8s_ns_name.

When enabling containerd (with both hooks) same issue as i started with: only the container_name is the container_id. 

> EDIT 2: Enabling containerd seems to bring back the problem. Btw, take into account that containerd doesn't seem to provide any notion of name, and for this reason, in that case, the short ID is provided. This is consistent to the Falco behaviour before the container plugin release.

I'm a little bit confused: doesn't containerd provides the container_name as it is set by k8s as a label ("io.kubernetes.container.name")
`ctr -n k8s.io c info` gives me for the kube-proxy container the following lables:
```
"Labels": {
        "io.cri-containerd.kind": "container",
        "io.kubernetes.container.name": "kube-proxy",
        "io.kubernetes.pod.name": "kube-proxy-kfnnv",
        "io.kubernetes.pod.namespace": "kube-system",
        "io.kubernetes.pod.uid": "eb1ad1b2-7081-4ed8-8da5-188fe315f5b2"
},
```
