### ISSUE TITLE
Fix Kubernetes daemonset example to include /host/etc

### ISSUE THREAD

**Issue by mfdii** [falcosecurity/falco#473]
In order for the eBPF probe loader to work properly on COS and minikube, /etc from the host needs to be mounted inside the Falco container.

The below needs added to the [daemonset](https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L37):

```
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco
              name: falco-config
...
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: falco-config
          configMap:
            name: falco-config
```

Opening this to remind myself to fix this.
