### ISSUE TITLE
How to get the user name in container?

### ISSUE THREAD

**Issue by imp0wd3r** [falcosecurity/falco#487]
I write the following rule to detect `wget` in container:

```yaml
- rule: Command executed with wget and curl
  desc: Command executed with wget and curl
  condition: evt.type = execve and container and proc.name in (wget, curl)
  output: "Command executed with wget and curl (%container.info user=%user.name cwd=%proc.cwd cmdline=%proc.cmdline)"
  priority: NOTICE
```

And I test it with user `admin` in a ubuntu container, but the `user.name` in result is not `admin` but `p0wd3r` which is the username on host:

```
$ whoami
admin
$ wget www.baidu.com
```

```
root@ubuntu:/tmp# falco -r /etc/falco/falco_rules.yaml -r /tmp/rules.yaml 
Tue Dec 25 00:29:41 2018: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Dec 25 00:29:41 2018: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Dec 25 00:29:41 2018: Loading rules from file /tmp/rules.yaml:
{"output":"00:29:49.613899964: Notice Command executed with wget and curl (ubuntu (id=e5d2306d0ee1) user=p0wd3r cwd=/ cmdline=wget www.baidu.com)","priority":"Notice","rule":"Command executed with wget and curl","time":"2018-12-25T08:29:49.613899964Z", "output_fields": {"container.id":"e5d2306d0ee1","container.name":"ubuntu","evt.time":1545726589613899964,"proc.cmdline":"wget www.baidu.com","proc.cwd":"/","user.name":"p0wd3r"}}
```

```
root      70626  0.0  0.1   7500  3828 ?        Sl   00:29   0:00      \_ docker-containerd-shim -namespace moby -workdir /v
root      70650  0.0  0.1  18508  2792 pts/0    Ss   00:29   0:00          \_ /bin/bash
root      70713  0.0  0.1  49272  2936 pts/0    S    00:29   0:00              \_ su - admin
p0wd3r    70715  0.0  0.0   4628   828 pts/0    S+   00:29   0:00                  \_ -su
```

How could I get the username in container (`admin` in the example)?
