### ISSUE TITLE
Can't find configuration file after installing falco on kubernetes

### ISSUE THREAD

**Issue by janbeerden** [falcosecurity/falco#656]
~It would be really nice to get falco up and running in [kind](https://github.com/kubernetes-sigs/kind).~

**editor note:** This issue initially happened to talk about an issue with Kind but then the OP used a different approach with a Vagrant machine. We are now trying to help them on getting Falco work in their environment.

**Comment by fntlnz** [comment]
@janbeerden thanks for bringing this up 🙌
My understanding kind does not use a different kernel than the underlying one where docker is running so unless I’m missing something we already work with kind.
Can you expand a bit more ?

**Comment by janbeerden** [comment]
@fntlnz, these are the logs from the falco pod after launching it in a kind Kubernetes 1.13 cluster:
```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.125-linuxkit cannot be found at
/lib/modules/4.9.125-linuxkit/build or /lib/modules/4.9.125-linuxkit/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.1/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.125-linuxkit
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.15.1-x86_64-4.9.125-linuxkit-598c2d809165b47f38383b83b6ff4798.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Mon Jun 10 20:30:26 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Jun 10 20:30:26 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Jun 10 20:30:27 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Jun 10 20:30:27 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Mon Jun 10 20:30:28 2019: Unable to load the driver. Exiting.
Mon Jun 10 20:30:28 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

I am using the k8s-with-rbac config files form [https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-daemonset](https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-daemonset)

Perhaps I am missing something?

**Comment by fntlnz** [comment]
Ok thanks for getting back with the log,
by looking at it I can understand a few things:

- You are probably using docker for mac or docker for windows to run your kind cluster, `4.9.125-linuxkit` seems the one built by Docker for those products.
- Given the previous consideration, the docker for mac operating system built with LinuxKit does not have the kernel headers built-in, this is why you are not able to build the module and you get this line
```
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.1/build/make.log
```
- Then, since the Falco probe is not built for linuxkit kernels you don't find it in the s3 bucket and thus you don't have the `/dev/falcoN` devices


Said that, as I was saying, Kind would just work, the problem here seems to be that there's no way for you to obtain or compile the adequate kernel module for your kernel.
 

I'm opening a new issue for that, but I think that it is good to keep this issue open to investigate if Kind truly works. Would you be able to test Falco and kind on another kernel @janbeerden ?

**Comment by janbeerden** [comment]
In the previous attempt I was using kind in combination with Docker Desktop Edge 2.0.4.1 (on macOS 10.14.5) with Docker 19.03.0-beta3.

When I spin up a VirtualBox with CoreOS version 2079.5.1, the module compiles but cannot be loaded due to CoreOS having a readonly filesystem.

I then tried it on a Debian Stretch VM and it gave the following output even though the kernel headers were installed:
```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.0-9-amd64 cannot be found at
/lib/modules/4.9.0-9-amd64/build or /lib/modules/4.9.0-9-amd64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.1/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.0-9-amd64
Cannot find kernel config
Tue Jun 11 18:54:28 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Jun 11 18:54:28 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Jun 11 18:54:29 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Jun 11 18:54:29 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Jun 11 18:54:29 2019: Unable to load the driver. Exiting.
Tue Jun 11 18:54:29 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

After that I tried on a CentOS 7 VM which gave the following output:
```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 3.10.0-957.5.1.el7.x86_64 cannot be found at
/lib/modules/3.10.0-957.5.1.el7.x86_64/build or /lib/modules/3.10.0-957.5.1.el7.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.1/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 3.10.0-957.5.1.el7.x86_64
Cannot find kernel config
Tue Jun 11 19:25:23 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Jun 11 19:25:23 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Jun 11 19:25:24 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Jun 11 19:25:24 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Jun 11 19:25:24 2019: Unable to load the driver. Exiting.
Tue Jun 11 19:25:24 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

In both Debian and CentOS I was using Docker-CE 18.09.6

**Comment by mfdii** [comment]
I compiled the other day on Debian stretch and it worked just fine. How are you installing the kernel headers? 

In both the Centos and Debian instances, the probe loader can't find headers, and it's typically fairly reliable at this check. How are you running Falco (please provide the command).

**Comment by janbeerden** [comment]
I started from https://app.vagrantup.com/debian/boxes/stretch64 followed by:
```
apt-get update && apt-get upgrade
apt-get install curl linux-headers-4.9.0-9-amd64
reboot
```
The apt-get upgrade installed linux-image-4.9.0-9-amd64

Next I installed Docker and used kind to setup a cluster:
```
apt install apt-transport-https ca-certificates gnupg2 software-properties-common
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get update && apt-get install docker-ce
curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64
chmod +x kind
mv kind /usr/local/bin/kind
kind create cluster
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/local/bin
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
```

Once the cluster is up and running I used the following yaml files to deploy Falco:
namespace.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
```

falco-account.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-account
  labels:
    app: falco
    role: security
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-cluster-role
  labels:
    app: falco
    role: security
rules:
  - apiGroups: ["extensions",""]
    resources: ["nodes","namespaces","pods","replicationcontrollers","replicasets","services","daemonsets","deployments","events","configmaps"]
    verbs: ["get","list","watch"]
  - nonResourceURLs: ["/healthz", "/healthz/*"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-cluster-role-binding
  namespace: falco
  labels:
    app: falco
    role: security
subjects:
  - kind: ServiceAccount
    name: falco-account
    namespace: falco
roleRef:
  kind: ClusterRole
  name: falco-cluster-role
  apiGroup: rbac.authorization.k8s.io
```

falco-service.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: falco-service
  labels:
    app: falco
    role: security
spec:
  selector:
    app: falco
  ports:
  - protocol: TCP
    port: 8765
```

falco-daemonset-configmap.yaml
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: falco-daemonset
  labels:
    app: falco
    role: security
spec:
  template:
    metadata:
      labels:
        app: falco
        role: security
    spec:
      serviceAccount: falco-account
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          securityContext:
            privileged: true
# Uncomment the 3 lines below to enable eBPF support for Falco.
# This allows Falco to run on Google COS.
# Leave blank for the default probe location, or set to the path
# of a precompiled probe.
#          env:
#          - name: SYSDIG_BPF_PROBE
#            value: ""
          args: [ "/usr/bin/falco", "--cri", "/host/run/containerd/containerd.sock", "-K", "/var/run/secrets/kubernetes.io/serviceaccount/token", "-k", "https://$(KUBERNETES_SERVICE_HOST)", "-pk"]
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /host/dev
              name: dev-fs
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc/
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco
              name: falco-config
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: falco-config
          configMap:
            name: falco-config
```

The rules files I copied from https://github.com/falcosecurity/falco/tree/dev/rules to falco-rules.

```
kubectl create -f namespace.yaml
kubectl config set-context $(kubectl config current-context) --namespace=falco
kubectl create configmap falco-config --from-file=falco-rules
kubectl apply -f falco-account.yaml -f falco-daemonset-configmap.yaml -f falco-service.yaml
```

When I fetch the logs for the created falco-daemonset pod, this is what I get:
```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.0-9-amd64 cannot be found at
/lib/modules/4.9.0-9-amd64/build or /lib/modules/4.9.0-9-amd64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.3/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.0-9-amd64
Cannot find kernel config
Wed Jun 19 20:31:46 2019: Falco initialized. No configuration file found, proceeding with defaults
Wed Jun 19 20:31:46 2019: Runtime error: You must specify at least one rules file/directory via -r or a rules_file entry in falco.yaml. Exiting.
```

I also confirmed the kernel version that was running:
```
root@stretch:~# uname -r
4.9.0-9-amd64
```
