### ISSUE TITLE
Falco crashing on Kubernetes with connection timeout

### ISSUE THREAD

**Issue by hus787** [falcosecurity/falco#680]
**What happened**:

Falco crashing. ~Once every 15mins.

**What you expected to happen**:

Falco not crash and handle and prevent connection timeouts gracefully.

**How to reproduce it (as minimally and precisely as possible)**:

```
helm install --name falco -f deployment/falco_config.yaml stable/falco
cat deployment/falco_config.yaml
```

```
ebpf:
  enabled: true
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 600Mi
image:
  tag: dev
falco:
  jsonOutput: true
fakeEventGenerator:
  enabled: false
customRules:
  rules-fluentd.yaml: |-
    - rule: Clear Log Activities
      append: true
      condition: and not k8s.ns.name=kube-system
```

**Environment**:
- Falco version (use `falco --version`):
- System info 
- Cloud provider or hardware configuration: Google (GKE)
- OS (e.g: `cat /etc/os-release`): COS (build 11647.121.0)
- Install tools (e.g. in kubernetes, rpm, deb, from source): Kubernetes 1.13.5-gke.10
- Node type: g1-small
