### ISSUE TITLE
Multiple slack notifications

### ISSUE THREAD

**Issue by seanmcrw** [falcosecurity/falco#930]
**What happened**:
Default installation on k8s(AWS EKS x7 EC2 nodes in cluster) with helm ```helm install --name falco stable/falco``` creates x7 duplicate notifications when using the slack integration.

**What you expected to happen**:
Only one notification should be posted to slack.

**How to reproduce it (as minimally and precisely as possible)**:
Default helm install, with slack notifications enabled.
```
jsonOutput: true
  ....
    programOutput:
    enabled: true
    keepAlive: false
    program: "\"jq '{text: .output}' | curl -d @- -X POST https://hooks.slack.com/services/xxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx\""
```

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`):
falco version 0.15.3
- System info 
```
{
  "machine": "x86_64",
  "nodename": "falco-6l9sz",
  "release": "4.14.146-119.123.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Sep 23 16:58:43 UTC 2019"
}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2
```
- Kernel (e.g. `uname -a`):

```
Linux ip-10-0-73-85.eu-west-1.compute.internal 4.14.146-119.123.amzn2.x86_64 #1 SMP Mon Sep 23 16:58:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools (e.g. in kubernetes, rpm, deb, from source):
- Others:
